### ISSUE TITLE
Use ferrum instead of helix-shared where possible

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1003]
Most of the functional utilities were moved to https://www.npmjs.com/package/ferrum.
In order to be able to deprecate and eventually remove them from helix-shared, helix-cli should use ferrum instead.

**Comment by stefan-guggisberg** [comment]
Hmm, both npm module and github repo are completely undocumented :(

**Comment by tripodsan** [comment]
> Hmm, both npm module and github repo are completely undocumented :(

I added jsdoc: https://github.com/adobe/ferrum/blob/master/docs/API.md and updated the README.

I don't have publish rights for npm, so the npm page is still behind.
see https://github.com/adobe/ferrum/issues/5#issuecomment-503796917
