### ISSUE TITLE
Remove local helix-static

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1048]
**Description**
With #850 the new dynamic linked static was introduced. I think we can now remove the locally provided one.

**Comment by rofe** [comment]
Do we consider this to be a breaking change? I think not, because from a user's perspective, which static action is being invoked is an implementation detail. but maybe i'm missing something 😬

**Comment by tripodsan** [comment]
no, the user doesn't really notice. so far, our only customer doesn't use a special helix-static handling setting....

**Comment by tripodsan** [comment]
btw, you can also remove the `src/openwhisk/static.js`
