### ISSUE TITLE
[hlx init] remove completely or replace

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#107]
`hlx init` doesn't really do much but copy some demo files. so it's not really a init, but rather a quickstart / demo and could be removed.

suggestion
-----------
- remove `hlx init`
- create `hlx demo` which will install a minimal demo; maybe with a `--simple` / `--full` switch.

instead of bundling the demo into `helix-cli` we could manage the demos independently on github. eg: `helix-project/archetypes/simple`, `helix-project/archetypes/full`. not sure about the git-repo to use and/or how versioning affects the demos, etc.

**Comment by trieloff** [comment]
I like the idea of just cloning an example repository. We could maintain a list of known example repositories, which would also encourage people to contribute their examples of Helix + <whatever pet peeve tech they'd like to show off> 

Versioning could be handled by inspecting the `package.json` of the demo. If the `@adobe/helix-cli` version in the `package.json` is greater than the current version, we show a warning or error.
