### ISSUE TITLE
[hlx] warn: unable to resolve ref to non-github repository

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#1086]
**Is your feature request related to a problem? Please describe.**
When running `hlx up` the following warning is logged to the console on every request:

```
[hlx] warn: unable to resolve ref to non-github repository: http://127.0.0.1:56868/raw/
```

**Describe the solution you'd like**
The warning is confusing/misleading and should be avoided.

**Context**
```
$ hlx --version
4.9.5
```

**Comment by stefan-guggisberg** [comment]
related: https://github.com/adobe/helix-pipeline/pull/384
https://github.com/adobe/helix-pipeline/blob/master/src/utils/resolve-ref.js#L69-L73

**Comment by tripodsan** [comment]
I guess, pipeline should not send the warning, for localhost.

**Comment by stefan-guggisberg** [comment]
The `resolveRef` step in the Pipeline doesn't really fit into the local dev use case. I guess for local dev you don't need/want stable git url's. Not sure how we can deal with this in the pipeline.

**Comment by tripodsan** [comment]
>  I guess for local dev you don't need/want stable git url's. Not sure how we can deal with this in the pipeline.

on the contrary, for local dev, using a non-local content repository, you really want to see the latest content changes.
