### ISSUE TITLE
Run Integration Tests on Windows

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#1098]
We are now part of the CircleCI Windows beta (docs here: https://github.com/CircleCI-Public/windows-preview-docs) and should have a build stage that runs on Windows to rule out compatibility issues.

### Issues

- [x] tests only run with `npm run test | cat` due to a problem with the `testAuthcmd.js`
- [x] failing: Integration test for demo + up command / up command delivers expected output with simple demo:
- [x] failing: Integration test for demo + up command / up command delivers expected output with full demo:
- [x] failing: hlx deploy (Integration) / Dry-Running works with cgi-bin:
- [x] failing: Testing GitUtils / isDirty #unit with submodules:
- [x] failing: Tests against the helix-cli repo / resolveCommit resolves the correct commit for tags:
- [x] failing: Tests against the helix-cli repo / getRawContent gets the correct version:
- [x] failing: hlx package (Integration) / package creates correct package:
- [x] failing: hlx package (Integration) / package reports bundling errors and warnings:
- [x] failing: hlx perf #unittest / formatScore() #unittest:
- [x] failing: hlx perf #unittest / formatMeasure() #unittest:
- [x] failing: Integration test for up command / up command delivers correct response.:
- [x] failing: Integration test for up command / "before each" hook: before:
- [x] failing: Integration test for up command with helix pages / up command delivers correct response.:
- [x] failing: Integration test for up command / up command delivers correct response for JSX templates.:
- [x] failing: "before each" hook in "Integration test for up command with helix pages"

**Comment by tripodsan** [comment]
I can look into the test failures today...

**Comment by tripodsan** [comment]
down to 8 failing tests:

```
  262 passing (3m)
  5 pending
  8 failing

  1) hlx deploy (Integration)
       deploy reports affected strains with default proxy:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\tripod\codez\helix-cli\test\testDeployCmd.js)


  2) hlx package (Integration)
       package creates correct package:
     Error: No entries found.
      at Bundler.bundle (node_modules\parcel-bundler\src\Bundler.js:275:17)

  3) hlx package (Integration)
       package reports bundling errors and warnings:
     Error: No entries found.
      at Bundler.bundle (node_modules\parcel-bundler\src\Bundler.js:275:17)

  4) Integration test for up command
       up command delivers correct response.:
     Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\tripod\codez\helix-cli\test\tmp\f2a48c748e515974c2c1774e6a30095a\logs\request.log'


  5) Integration test for up command
       "after each" hook:
     Uncaught Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
      at doWrite (_stream_writable.js:411:19)
      at writeOrBuffer (_stream_writable.js:399:5)
      at WriteStream.Writable.write (_stream_writable.js:299:11)
      at Array.logRequest (node_modules\morgan\index.js:130:14)
      at listener (node_modules\on-finished\index.js:169:15)
      at onFinish (node_modules\on-finished\index.js:100:5)
      at callback (node_modules\ee-first\index.js:55:10)
      at ServerResponse.onevent (node_modules\ee-first\index.js:93:5)
      at onFinish (_http_outgoing.js:671:10)
      at process._tickCallback (internal/process/next_tick.js:61:11)

  6) Integration test for up command
       up command delivers correct response with different host.:
     TypeError: Cannot read property 'call' of undefined


  7) Integration test for up command
       "before each" hook in "Integration test for up command":
     TypeError: Cannot read property 'call' of undefined


  8) Integration test for up command with helix pages
       "after each" hook in "Integration test for up command with helix pages":
     TypeError: Cannot read property 'call' of undefined
```


The _problem_ is, that all of those tests work when executed individually, or even by suite.

**Comment by tripodsan** [comment]
eg:
```
tripod@DESKTOP-4C7NLM2 MINGW64 ~/codez/helix-cli (win-ci)
$ ./node_modules/.bin/mocha test/testUpCmd.js
...
  9 passing (30s)
  1 pending
```

**Comment by tripodsan** [comment]
**Note**: there is a problem in `nyc` that we cannot execute `npm` from within the code: https://github.com/istanbuljs/nyc/issues/760

the windows CI tests are run w/o nyc, so this should not be a problem. 
otherwise we would need to exclude the helix-pages test.
