### ISSUE TITLE
Demo, Fails if .gitconfig doesn't exist, but says Git isn't installed.

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-cli#1111]
**Description**
When running the demo; hlx demo [demo_name] fails if .gitconfig doesn't exist.

**To Reproduce**
1) Move .gitconfig out of home directory. To figure out what dir this is, fire node and see what os.homedir() prints. 

2) cd to helix-cli root, and run hlx demo [demo_name], it will fail and say to install Git

**Expected behavior**
Helix CLI should know that Git is installed, but a .gitconfig isn't there! 

**Screenshots**
![Screen Shot 2019-08-06 at 2 34 11 PM](https://user-images.githubusercontent.com/12217245/62579438-9badc400-b858-11e9-8e3e-0d22c11db26e.png)

**Version:**
4.9.10

**Additional context**
Super easy fix, just convenience things!

**Comment by stefan-guggisberg** [comment]
nitpicking:

The title of this issue states 

> but says Git isn't installed.

The error message however says

> It seems like Git has not yet been setup on this system. 

and the provided link refers to [First Time Git Setup](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup).

There's a difference between [Installing Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) and [First Time Git Setup](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup) as illustrated by the 2 separate chapters in the Git documentation.

The error message and documentation link are concise and correct.
