### ISSUE TITLE
hlx publish command rename

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-cli#1112]
**Description**
hlx publish command needs service id not namespace: --fastly-namespace <service-ID>

**To Reproduce**
Make a tiny change in a MD, commit and publish to github
deploy the project, hlx deploy --fastly-namespace <namespace>
publish project , hlx publish --fastly-namespace <service-ID> 

**Expected behavior**
parameter name should reflect what command needs.

**Screenshots**
![Screen Shot 2019-08-07 at 3 00 17 PM](https://user-images.githubusercontent.com/12217245/62660834-17287780-b924-11e9-9ccd-6895e3450722.png)

**Version:**
4.9.10

**Additional context**
Nada!

**Comment by tripodsan** [comment]
so we should probably name it `--fastly-serviceid`

**Comment by trieloff** [comment]
Please make sure that the old name stays as an alias, so that we don't break compatibility.

**Comment by MarquiseRosier** [comment]
Got it!
