### ISSUE TITLE
Unclear error when publishing without activating fastly service

### ISSUE THREAD

**Issue by moritzraho** [adobe/helix-cli#1127]
**Description**
If fastly service is not activated the `hlx publish` command fails

**To Reproduce**
Create a fastly service and do not activate it
then run `hlx deploy`
then run `hlx publish`
the error is
```
error: Error while running the Publish command: FastlyError: Couldn't find Version '[<my_service_id>, undefined, 0000-00-00 00:00:00]'
```

**Expected behavior**
A clear error message on why this failed

**Screenshots**

**Version:**
3.2.0

**Additional context**

**Comment by trieloff** [comment]
The version number is determined by Helix CLI, moving the issue.
