### ISSUE TITLE
Weird error if fastly-serviceid parameter is empty

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1135]
**Description**
I lost plenty of time on this stupid issue. If fastly-serviceid is empty, you get the following error message:

```
Error while running the Publish command
preparing fastly transaction
error: Error while running the Publish command: FastlyError
    at request.then (/Users/acapt/.nvm/versions/node/v10.16.0/lib/node_modules/@adobe/helix-cli/node_modules/@adobe/fastly-native-promises/src/httpclient.js:107:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
1. Run `hlx publish --fastly-serviceid ""` (assuming you have other parameters properly set)

**Expected behavior**
An error message like when no parameter at all is provided: 

```
Missing required argument: fastly-serviceid
Fastly Service ID is required.
```

**Version:**
run: `$ hlx --version`
4.10.0

**Comment by trieloff** [comment]
@MarquiseRosier that might be something for you.

**Comment by kptdobe** [comment]
@tripodsan No. I think I was fine with the param names, I discovered the issue accidentally on CircleCI where my env variable was not transferred from one step to another thus value was empty. I was doing:
```
hlx publish --fastly-serviceid $TEST_SERVICE
```
and `TEST_SERVICE` was empty. In the previous step, I was setting it properly and echo worked. It is just not "exported" automatically.

 It just took me a while to realise the pb was the value and not something related to my npm setup or a weird issue in the cli.
