### ISSUE TITLE
[auth] no longer works

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#1141]
**Description**
`hlx auth` is currently broken.

**To Reproduce**
1. Run `hlx auth` on a Helix project (e.g. `hlx demo`)
2. Browser opens to https://app.project-helix.io/login?p=54594 with the following output:
`Cannot GET null`
3. `hlx auth` hangs in the console

**Expected behavior**
`hlx auth` generates a GitHub token

**Version:**
v5.0.2

**Comment by tripodsan** [comment]
I fixed the respective backend action.
