### ISSUE TITLE
Exclude smoke tests for forked pull requests

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1173]
CircleCI allows to run the build workflow for PR coming from fork repos via the `Build forked pull requests` setting on the project. 
Main issue is that our smoke tests require several environment variables which are NOT shared to the build workflow in the case of a PR coming from a fork: option 
"Pass secrets to builds from forked pull requests" because it would allow anyone doing a PR via a fork to have access to our env vars which contains multiple secrets.

The result is that the smoke tests job fails for all the forked PRs. To workaround that, we should not run the smoke tests for forked PRs. This introduces a risk that the PR introduces a regression but there is not simple solution for the moment. We could introduce a "warning" step to inform the reviewer that more care needs to be taken. Also, when we merge to master, the smoke tests will be executed and we could then see a potential failure there.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
