### ISSUE TITLE
hlx up on remote repo not found with private repo

### ISSUE THREAD

**Issue by Acidham** [adobe/helix-cli#1199]
**Description**
Starting hlx on the remote repo (`hlx up --no-local-repo`) not found error of markdown when repo is set to private

**To Reproduce**
1. Create **private** repo and push hello-helix to Github
2. start helix `hlx up --no-local-repo`
3. See error: `[hlx] error: Could not find Markdown at https://raw.github.com...`

**Expected behavior**
Start hello-helix in the browser showing git remote content

**Version:**
5.7.4

**Additional context**
1. The error tries to find markdown https://raw.github.com/... but raw content of md file should be https://raw.githubusercontent.com/...
2. Changing hello-helix repo from **private** to **public** hlx starts without errors and shows remote content

**Comment by tripodsan** [comment]
thanks for reporting, @Acidham.
private repo support is not fully tested :-) 
I created a corresponding bug: https://github.com/adobe/helix-simulator/issues/330

**Comment by tripodsan** [comment]
you could probably set it via `--dev-params` eg:

`hlx up --dev-params GITHUB_TOKEN xxxxxx-xxxxx-xxxx-xxxxx`

which is obviously not so great :-)

**Comment by Acidham** [comment]
I tried it for testing purpose and it works!

But it seems `--dev-params` is unknown...I get it to work with: `hlx up --dev-default GITHUB_TOKEN xxxxxxxxxxxx`

**Comment by tripodsan** [comment]
> I tried it for testing purpose and it works!
> 
> But it seems `--dev-params` is unknown...I got it to work with: `hlx up --dev-default GITHUB_TOKEN xxxxxxxxxxxx`

of course...my fault

**Comment by trieloff** [comment]
@Acidham if you don't like seeing your private GitHub token in your command line every time you run `hlx up`, you can also `export HLX_DEV_DEFAULT …`.

**Comment by rofe** [comment]
I think this should be documented properly.

**Comment by tripodsan** [comment]
> @Acidham if you don't like seeing your private GitHub token in your command line every time you run `hlx up`, you can also `export HLX_DEV_DEFAULT …`.

@trieloff unfortunately this doesn't work. since the environment variables don't support arrays.

**Comment by tripodsan** [comment]
### Suggestion

if a `HLX_GITHUB_TOKEN` is set, propagate it automatically to the simulator via the action params.

**Comment by tripodsan** [comment]
another problem seems to be that the authorization header is not preserved after the redirect (which is IMO correct). they fixed that in https://github.com/request/request/issues/450. 

so I wonder, how you got this to work, @Acidham
