### ISSUE TITLE
[hlx up] add support to specify http port

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#12]
### suggest 

`--port, -p option`

eg:

```
hlx up --port 4502
```

**Comment by tripodsan** [comment]
an additional improvement would be to automatically select a new port, if the current one is taken.

```
# use 3000 as http port but find next free one if already taken.
hlx up --port 3000+

# use 3000 as http port but fail if already taken
hlx up --port 3000
```

**Comment by koraa** [comment]
@tripodsan How would `--port 3000+` affect usability? Can you describe cases where this happens in practice and the use would not prefer to close the service blocking the port?
Maybe using `reuseaddr` would be a better option?

**Comment by koraa** [comment]
reuseaddr+reuseport I mean

**Comment by tripodsan** [comment]
the `--3000+` was just an attempt to save an extra option argument.. I don't think that we should confuse this with `SO_REUSEADDR` and `SO_REUSEPORT`, because those are used differently and are not very intuitive.

> How would --port 3000+ affect usability? Can you describe cases where this happens in practice and the use would not prefer to close the service blocking the port?

the idea is that `hlx up` should start the server and open the browser with the correct address. if port 3000 is already used by another application, the developer will get an error and might be annoyed. so for a better experience, we should just open on the next free port. if we let the OS choose the port, we get _any_ free port, which might not look _nice_. so hence the ability to indicate the base. 

alternatively, we would specify several ports, like:

`--port 3000,8000,8080,3001+`

try: `3000` then `8000` then `8080` then one after 3000`

but this might be overkill.
