### ISSUE TITLE
Configurable helix-pipeline for build

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1200]
this is a followup issue for #1197.

It would be cool if the helix-pipeline is not bundled with helix-cli but installed on demand when building the scripts. this allows for a more detailed control on which pipeline is to be used and helix-cli could get more generic.

### Ideas
- use npm to download helix-pipeline
- inform user if a newer version is available
- install to `./hlx/build/node_modules` (use `--only-prod`, cache package-lock and use `npm ci` for faster installs)
- also consider dynamically loading htlengine (might need to split out htlengine-runtime ?)

**Comment by rofe** [comment]
I guess we should mention this in https://github.com/adobe/helix-home/blob/master/getting-started.md ...

**Comment by tripodsan** [comment]
> I guess we should mention this in https://github.com/adobe/helix-home/blob/master/getting-started.md ...

what exactly ?

**Comment by rofe** [comment]
> what exactly ?

How one can control the version of `helix-pipeline` being used, no?

**Comment by tripodsan** [comment]
> How one can control the version of `helix-pipeline` being used, no?

just create a `package.json` and add an explicit version of `@adobe/helix-pipeline`

**Comment by rofe** [comment]
This didn't work for me... maybe I need to modify `.hlx/build/package.json` instead?
