### ISSUE TITLE
Tests no longer run with node version < 10

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-cli#1215]
**Description**
Some tests in helix-cli (e.g. `test/testDemoCmd.js`) use `assert.requires` which is available since Node version 10, only.

**To Reproduce**
1. Switch to Node version 8 (`nvm use 8.12`)
2. Run tests: `npm t test/testDemoCmd.js`
3. See error: `TypeError: assert.rejects is not a function`

**Expected behavior**
README.md and package.json should indicate that Node version 10 or higher is required.

**Version:**
5.9.2

**Comment by tripodsan** [comment]
let's wait 1.5 more months, and then ew can drop 8.x support:
https://nodejs.org/en/about/releases/

**Comment by tripodsan** [comment]
switched to node 10.
