### ISSUE TITLE
document --dev-default

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-cli#1223]
## Overview
--dev-default should have some documentation

**Comment by tripodsan** [comment]
@MarquiseRosier is there anything left to do ? otherwise we can close this issue. thanks.

**Comment by MarquiseRosier** [comment]
@tripodsan absolutely nothing! I'll close it :D

**Comment by trieloff** [comment]
@MarquiseRosier use `npm run commit`, this will also ask you which issue a change refers to (and the bot will then close the issue automatically)

**Comment by MarquiseRosier** [comment]
@trieloff  ^^ That's strange I thought I did refer to it; I will be more careful next time!
