### ISSUE TITLE
Export API for integrating cli actions

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1227]
Currently there is no good way to run helix-cli programatically.
Using a better cli/api separation and correctly export the structures would be beneficial.

**Comment by trieloff** [comment]
Where do you want to use the CLI programmatically?

**Comment by tripodsan** [comment]
for example here: https://github.com/adobe/helix-index-pipelines/blob/c215c4ff6e3caf3ef37d61f376c2b0aaa3c3647b/build/deploy.js#L123

**Comment by trieloff** [comment]
Hm. What's the advantage of building your own deploy tool instead of just using the existing CLI in your CircleCI config?

**Comment by tripodsan** [comment]
For that particular case, the deployment was a bit more complicated. we lack some features in `helix-cli` for that special kind of project. especially the linking is tricky. 

even if helix-cli would support all the bits needed for deploying helix-index-pipelines, it still feels more confortable to write a little JS script using the API instead of a complicated bash script.

but at least the `up` command is very useful as API. using `shelljs` would be possible, but doesn't give enough control over the server lifecycle.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
