### ISSUE TITLE
Tests are unstable

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1249]
Since the configurable pipeline has been introduced (https://github.com/adobe/helix-cli/issues/1200), the tests are unstable. See: 
- https://app.circleci.com/jobs/github/adobe/helix-cli/11275
- https://app.circleci.com/jobs/github/adobe/helix-cli/11345

The failure is caused by randomly failing `npm install @adobe/helix-pipeline`. With https://github.com/adobe/helix-cli/pull/1243, we'll introduce a lot more of them (I can count 11) and if we cannot rely on `npm install`, we'll have to find a way to mock it.

cc @tripodsan

**Comment by MarquiseRosier** [comment]
@kptdobe 

i'm interested in taking this. With respect to your question, how would we mock npm install? Perhaps we can ask users to also download pipeline and do some local git operations?

**Comment by tripodsan** [comment]
as far as I can remember, I tried to decouple the npm install of the pipeline from the rest of the tests. it should run before all the tests (w/o timeout) and then  set the module path accordingly, so that the tests use the pre-installed pipeline. if this is not working anymore, then something broke.

**Comment by MarquiseRosier** [comment]
Ok thanks @tripodsan

**Comment by kptdobe** [comment]
Yes, but I think even what you set up is not enough: if you look here https://11275-139854376-gh.circle-artifacts.com/1/home/circleci/repo/junit/test-results.xml (artefact from https://app.circleci.com/jobs/github/adobe/helix-cli/11275), the error `Error: Unable to install @adobe/helix-pipeline: at ModuleHelper.installModule (src/builder/ModuleHelper.js:23:235)` is coming from a failing "pre-install".

Also, #1243, requires multiple extra different installs (we need to test the usage of custom pipeline - i.e. different versions to npm install) which tend to also fail randomly (second example above).

I do not really know how we could do this. Ideally, an `npm install` run during the test should not download anything, just used a locally stored version. We'll have different version to use: 
- the latest one or the one specified by the `HLX_CUSTOM_PIPELINE` env var
- the ones required by the test (v1.0.0 and a git version one)

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
