### ISSUE TITLE
enhance pipeline with external request parameters

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#126]
for solving https://github.com/adobe/petridish/issues/46 also for the pipeline, we need:

- [ ] move the magic parameter handling from ow-log-wrapper to cli https://github.com/adobe/openwhisk-loggly-wrapper/issues/6
- [ ] adjust the `OutputTemplate.js` to implement the logic from ow-log-wrapper
- [x] instruct fastly to generate a `req` request parameter that contains the original request

**Comment by trieloff** [comment]
Careful: every request parameter and Cookie is a potential cache-buster. Adding external request parameters to hypermedia-pipeline is easy, but for our VCL we should have a whitelist approach where parameters not on the list get ignored.

**Comment by tripodsan** [comment]
> but for our VCL we should have a whitelist approach where parameters not on the list get ignored.

- how would the developer control this?
- is it at all possible to create an encoded string that contains the external request?

**Comment by trieloff** [comment]
> how would the developer control this?

Another item in the strain config going into an edge dictionary.

> is it at all possible to create an encoded string that contains the external request?

I think so: 
* https://docs.fastly.com/vcl/functions/querystring-filter-except/ allows us to filter the original query string on a whitelist
* https://docs.fastly.com/vcl/functions/urlencode/ allows us to put it safely into another request parameter

**Comment by kptdobe** [comment]
In VCL, encoding the incoming request in JSON to pass it as a request parameter to invoke this action will be a nightmare to handle...
The JSON should be aligned with the one in Petridish: see https://github.com/adobe/petridish/blob/master/src/RequestContext.js#L98-L105

```
{
      url: req.url,
      resourcePath: var.dir +var.name?,
      path: var.dir?,
      selector: var.selector,
      extension: var.extension,
      method: req.request,
      headers: req.http.header?,
      params: req.params?,
}
```

**Comment by kptdobe** [comment]
@trieloff answered:

It should not be too difficult, if we can accept a bit of transforming/wrapping in the action:

- pass it as parameters: `url`, `path`, `selector`, `extension`, `method`
- passed in __ow_headers: `headers`
- passed with a new, url-encoded params parameter: `params` (see above)

The only remainder is `resourcePath`, which should not be set outside the pipeline, but inside the pipeline (as this is where fetching happens). I'd say petridish is wrong here.

**Comment by trieloff** [comment]
@kptdobe we should not encode things as JSON. It's a non-native construct to VCL, and the one part where we have variable data structures (`params`), we can live with a `urlencode`d value (with a parameter whitelist)

**Comment by kptdobe** [comment]
I definitively prefer the `req` parameter idea which separates clearly the action parameters and the original request.
`_ow_headers`: that's the action incoming headers, no ? or at least they have been tweaked by the VLC on Fastly. Might be fine though...

But on the other hand, when I see the amount of VCL effort to simply dump those parameters into one JSON encoded string...

I found https://github.com/fastly/vcl-json-generate/blob/master/files/json_generate.vcl to inspire from (we would need something similar but not change the req object). But some "JSON utils" would overload the amount of VCL we need.

**Comment by trieloff** [comment]
> `_ow_headers`: that's the action incoming headers, no ? or at least they have been tweaked by the VLC on Fastly. Might be fine though...

Here's the flow: all headers from the original request to Fastly and all headers set or overwritten in VCL (all the `X-Stuff`) get passed into the action and appear there as `__ow_headers`.

This means we can pry a lot of the stuff we need out of the headers, if we want to.

**Comment by kptdobe** [comment]
ok, then on the action side we would a big `if`:
- if `req` parameter is present, parse it.
- otherwise, gather and decode: `url`, `path`, `selector`, `extension`, `method`, `headers`, `params`

Or even simpler, we get rid of the `req` parameter idea, which would simply mean that Petridish must be changed to pass those parameters directly (easy)

**Comment by trieloff** [comment]
I'd keep as much logic as possible out of the action, so:
- always gather and decode: `url`, `path`, `selector`, `extension`, `method`, `__ow_headers`, `params`
- in Petridish: set `__ow_headers` and filter and encode `params`
- in VCL: filter and encode `params`

**Comment by tripodsan** [comment]
I am confused.
we're still doing https://github.com/adobe/hypermedia-pipeline/issues/7#issuecomment-417301894 ?
- so the `payload.request.params` contains the query parameters of the external request
- and the `action.request.params` contains the query parameters of the internal request
- `payload.request.pathInfo` (https://github.com/adobe/hypermedia-pipeline/issues/8) would still contain the url, path, etc of the resources

**Comment by trieloff** [comment]
Then we would have following data flow:

Edge: `https://www.example.com?foo=bar&baz=boo`
Runtime: `https://runtime.adobe.io/api/v1/myaction?path=index.html&extension=html&params=foo%3Dbar%26baz%3Dboo`
Pipeline:
```javascript
const action.request.params = {
  path: 'index.html',
  extension: 'html',
  params: 'foo%3Dbar%26baz%3Dboo'
}

const payload.request.params = {
  foo: 'bar',
  baz: 'boo'
}
```

Correct?
