### ISSUE TITLE
Error during hlx deploy: "Concurrent modification to resource detected."

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1264]
**Description**
sometimes when running `hlx deploy`, the following error occurrs:

```
PUT https://adobeioruntime.net/api/v1/namespaces/***********/packages/helix-services?overwrite=true Returned HTTP 409 (Conflict) --> "Concurrent modification to resource detected."
```

**Version:**
7.0.4

**Comment by trieloff** [comment]
This seems to be a runtime issue. Maybe we should just try again.

**Comment by tripodsan** [comment]
it could also be that we have async jobs that update the package and actions below the package...

**Comment by trieloff** [comment]
Hm. Is that an issue for Runtime? Still looks like a bug to me.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
