### ISSUE TITLE
dev-default should be usable as env variable

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-cli#1266]
**Is your feature request related to a problem? Please describe.**
allow helix devs to use dev-default to set their default params and secrets via env vars

**Comment by tripodsan** [comment]
since the env variable can only be single valued and automatically parsed by yargs, there are only a few options:

```
# as semicolon separated list of key=value pairs (http header style)
HLX_DEV_DEFAULT=key1=value;key2=value

# inline json
HLX_DEV_DEFAULT= {"key1":"value", "key2":"value"}
```

I think the inline json is, although a bit awkward, easy to detect and to parse. it can be implemented in the `coerce` method of yargs.

**Comment by MarquiseRosier** [comment]
I really like the inline json version too; thanks for this critical tip!
