### ISSUE TITLE
verify licenses of dependencies WRT binary distribution

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#128]
subtask of #127

**Comment by stefan-guggisberg** [comment]
[license-checker](https://github.com/kriszyp/json-schema) reports the following licenses being used:

```bash
$ license-checker -summary
├─ MIT: 844
├─ ISC: 84
├─ Apache-2.0: 38
├─ BSD-3-Clause: 23
├─ BSD*: 12
├─ BSD-2-Clause: 12
├─ CC-BY-4.0: 3
├─ MIT*: 3
├─ BSD: 3
├─ MPL-2.0: 2
├─ (BSD-2-Clause OR MIT OR Apache-2.0): 2
├─ Apache License, Version 2.0: 2
├─ (BSD-3-Clause OR GPL-2.0): 1
├─ (MIT OR GPL-3.0): 1
├─ Custom: https://github.com/douglascrockford/JSON-js: 1
├─ (MIT OR Apache-2.0): 1
├─ (MIT AND Zlib): 1
├─ AFLv2.1,BSD: 1
├─ Public Domain: 1
├─ (MIT AND BSD-3-Clause): 1
└─ Unlicense: 1
```

i went through the different licenses. they look good to me with regard to binary distribution (to the best of my knowledge). however,  IANAL and they should be reviewed by an expert on the subject.

**Comment by stevengill** [comment]
@adobe/open-source-office lets review this. 

> Unlicense: 1
The 1 unlicensed one isn't great. Do we know what library that is? Can we manually check if it is licensed?

> Custom: https://github.com/douglascrockford/JSON-js: 1 

This is also not licensed as far as I can tell. How is the CLI using it?

I see we have two licenses that have GPL in them. But according to the results, they are dual licensed. That should be fine. 

The rest of the licenses look fine to me on first pass

**Comment by stefan-guggisberg** [comment]
>> Unlicense: 1

> The 1 unlicensed one isn't great. Do we know what library that is? Can we manually check if it is licensed?

it's not unlicensed, it's licensed under _The Unlicense_: https://github.com/dchest/tweetnacl-js/blob/master/LICENSE

>> Custom: https://github.com/douglascrockford/JSON-js: 1

> This is also not licensed as far as I can tell. How is the CLI using it?

`license-checker`'s summary output is misleading. the module/git repo in question is [cycle](https://github.com/dscape/cycle). according to the [package.json](https://github.com/dscape/cycle/blob/master/package.json#L7) it's `Public-Domain`.

**Comment by stefan-guggisberg** [comment]
we seem to be good license wise, closing issue.
