### ISSUE TITLE
hlx demo fails to create a project

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1285]
Run `hlx demo test`

This shows: 

```
Alexandre Capt
*****@*******
creating test                                    [ok]
On branch master

Initial commit

nothing to commit
Unable to initialize git repository: 
```
This has created an empty `test` folder. 
Expected: a simple Helix project.

Same applies for command `hlx demo --type=full test` which should create a more complex project.

cc @icaraps 

hlx --version: v7.2.5

**Comment by stefan-guggisberg** [comment]
It's a regression of 973d9ce.

**Comment by stefan-guggisberg** [comment]
The `demo` folder was added to `.npmignore` which causes `hlx demo` to fail.

Furthermore, `*.tgz` was removed from `.npmignore`. `*.tgz` files are artefacts of running `npm pack` and should not be included in the npm package.

**Comment by kptdobe** [comment]
Why the tests did not catch the issue ? We have multiple tests in the area...

**Comment by stefan-guggisberg** [comment]
> Why the tests did not catch the issue ? We have multiple tests in the area...

The tests don't use the published module (i.e. installed with `npm i -g @adobe/helix-cli`).
