### ISSUE TITLE
hlx up fails to render a arbitrary project

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1286]
I run: 

```
$ mkdir test
$ cd test
$ vi index.md (add #Hello World in the file)
$ hlx up
```

This shows: `hlx up needs local git repository.`
Then I do: 
```
$ git init
$ hlx up
```

`helix-pages` is installed but index.html fails to render:

```
[hlx] error: Could not find Markdown at http://127.0.0.1:52768/raw/helix/localhost--local--default/master/index.md
[hlx] error: Resource not found: /index.html
```

I would expect this to work and render my `index.md`

cc @icaraps 

hlx --version: v7.2.5

**Comment by tripodsan** [comment]
@stefan-guggisberg might be a problem that the origin is not set?

**Comment by stefan-guggisberg** [comment]
The problem in your example above is that the git repo doesn't have a commit yet. `HEAD` etc don't exist. It's in limbo.

The following works:

```bash
mkdir test && cd test
vi index.md (add #Hello World in the file)
git init
git add .
git commit -m 'initial commit'
hlx up
```

**Comment by tripodsan** [comment]
Maybe we should add a more user friendly error message, like:

```
$ mkdir test
$ cd test
$ vi index.md (add #Hello World in the file)
$ hlx up
error: hlx up needs local git repository.

$ git init
$ hlx up
error: hlx up needs a local git repository with at least 1 commit.
```

**Comment by stefan-guggisberg** [comment]
FWIW: the following works:

```bash
git init && git commit -m 'initial commit' --allow-empty
```

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
