### ISSUE TITLE
Cannot specify Coralogix API key and log level

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1339]
Create a new hlx project with an .env file containing a valid HLX_CORALOGIX_API_KEY and HLX_CORALOGIX_LOG_LEVEL, and all required keys to publish.
Run `hlx build; hlx deploy; hlx publish`

1. Request on Fastly: no logs from the project specific actions appear in Fastly.

2. Run `wsk action get <namespace>/<action id>/html` (html render action): the action does not have the Coralogix specific parameters.

Not sure if this is the right way of providing the Coralogix params but since the project actions are wrapped like any other action, we must be able to configure Coralogix logging.

See also https://github.com/adobe/helix-pages/issues/179

@trieloff @tripodsan any hint ?

**Comment by tripodsan** [comment]
`hlx deploy --default HLX_CORALOGIX_API_KEY ... HLX_CORALOGIX_LOG_LEVEL ...`

**Comment by tripodsan** [comment]
I think https://github.com/adobe/helix-cli/issues/1266 should also be applied to the `default` params.

**Comment by kptdobe** [comment]
The correct solution to my issue is: 

`hlx deploy --default CORALOGIX_API_KEY ... CORALOGIX_LOG_LEVEL ...`

I think the "system" should be smart and take all `HLX_<name>` from the `.env` file and provide them to the action as `<name>` variable.

**Comment by tripodsan** [comment]
> I think the "system" should be smart and take all `HLX_<name>` from the `.env` file and provide them to the action as `<name>` param.

no. the system is already smart, and uses the `HLX_<name>` as yargs arguments :-)

but, similar to the github token, we can ensure that `CORALOGIX_API_KEY` is a deploy argument and automatically added as action params.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
