### ISSUE TITLE
Better default parameter support (env, json, files)

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1352]
**Is your feature request related to a problem? Please describe.**
similar to #1266, the `--default` parameter should also be usable as env variable.

**Comment by tripodsan** [comment]
@MarquiseRosier do you want to take this?

**Comment by tripodsan** [comment]
suggest to add new semantics:

---
## Passing default action parameters during deploy

If the action needs default parameter, they can be specified during `hlx deploy` with the `--default` argument. The argument either takes multiple name/value pairs, json values or references to environment or json files. 

### use as argument values

```console
# arguments with name value pairs
hlx deploy --default SECRET value --default ANOTHER foobar

# multiple name value pairs
hlx deploy --default SECRET value ANOTHER foobar

# json argument
hlx deploy --default '{"SECRET": "value", "ANOTHER": "foobar"}'
```

#### use in environment

All `hlx` command line arguments can also be passed via environment variables, prefixed with `HLX_`. Since the `default` parameters need key and value, this is only possible using the json format:

(note that the `.env` file is automatically loaded by `hlx`)

**.env**
```env
HLX_DEFAULT={"SECRET": "value", "ANOTHER": "foobar"}
```

### use via reference to file

In addition to the above, the parameters can also be specified using a reference to a json or env file:

```console
# reference to env file
hlx deploy --default @secrets.env

# reference to json file
hlx deploy --default @./prod/secrets.json
```

**secrets.env**
```env
SECRET=value
ANOTHER=foobar
```

**prod/secrets.json**
```json
{
  "SECRET": "value",
  "ANOTHER": "foobar"
}
```

#### use in environment

similar to the above, the file reference can also be specified in the environment variables:

**.env**
```
HLX_DEFAULT=@./prod/secrets.json
```

**Comment by tripodsan** [comment]
An alternative to the above is to specify the file references by a separate argument:

```
hlx deploy --defaults-file
```

**Comment by kptdobe** [comment]
Where is the JSON file requirement coming from ?

Contrary to the dev default (mostly for `hlx up` ?), `hlx deploy` is generally used in a CI (in majority). And with the above, I do not have the feeling we make our life more simple, we will end up doing things like https://github.com/adobe/helix-theblog-importer/blob/master/.circleci/config.yml#L36to generate a .env file (or json) with all variables we need.
Why not a pattern like `HLX_DEPLOY_<abc>`: all env var starting with this pattern will be loaded automatically as `<abc>` by deploy ? They can be stored in the `.env` file or in the CI env var. No need for extra files.

**Comment by tripodsan** [comment]
> Where is the JSON file requirement coming from ?

we use yargs. and yargs as a built in mechanism to support environment variables via the `HLX_` prefix. this works for all arguments. but for `--dev-default` and --default` it doesn't because it uses name value pairs. this is especially annoying to `hlx up` where you always need to specify `--dev-default` params. so we added it there to use a json syntax as argument value (usualy in the `.env` file).

For local development and testing, it would be useful to have some default files, that can be used or not. so having a `--default-file` argument is useful. for example:

```
# test a helix-pages deploy
hlx deploy --default-file helix-pages-env.json

# test a tripod deploy
hlx deploy --default-file tripod-env.json
```

---

> Contrary to the dev default (mostly for hlx up ?), hlx deploy is generally used in a CI (in majority).

yes. you can specify it via`.env` or via arguments. also the not-secret params could be provided in the project. eg:

```
hlx deploy --default-file prod.env --default XYZ_TOKEN xxxxxx
```

> we will end up doing things like https://github.com/adobe/helix-theblog-importer/blob/master/.circleci/config.yml#L36to generate a .env file (or json) with all variables we need.

why do you need this? all the env vars defined in the circle ci project are already in the environment.
however, I would write it in multiple lines:

```yaml
- run: echo "LOG_LEVEL=info" > .env
- run: echo "AZURE_BLOB_URI=$AZURE_BLOB_URI" >> .env
- run: echo "AZURE_BLOB_SAS=$AZURE_BLOB_SAS" >> .env
...
```
