### ISSUE TITLE
With pipeline v6.10.0, tests are failing

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1353]
Just run `npm run test` in the current project, they will be failing in multiple places due to multiple issues:
- https://github.com/adobe/helix-pipeline/pull/533 introduced new requests to `helix-markup.yaml`, they need to be recorded otherwise Polly will fail. 
- https://github.com/adobe/helix-pipeline/pull/533 introduced a regtession, see https://github.com/adobe/helix-pipeline/issues/642

All of this did not show up during the integration / smoke tests because of https://github.com/adobe/helix-continuous/issues/80...

**Comment by tripodsan** [comment]
I think this is fixed.
