### ISSUE TITLE
helix-config.yaml file missing in demo project

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#136]
Following the [getting-started.md](https://github.com/adobe/project-helix/blob/master/getting-started.md), there should be a `helix-config.yaml` file present in the demo directory. It isn't :)
I copied it over manually from [here](https://github.com/adobe/helix-cli/blob/master/demos/full/helix-config.yaml).

**Comment by tripodsan** [comment]
this is deliberate. the `demo --simple` just creates the necessary files:

```
$ hlx demo simple-test
...
simple-test/
├── helix_logo.png
├── index.md
└── src/
    ├── html.htl
    ├── html.pre.js
    └── static/
        ├── favicon.ico
        └── style.css
```

the full demo creates a more comprehensive structure:

```
$ hlx demo --type=full full-test
...
full-test/
├── README.md
├── helix-config.yaml
├── helix_logo.png
├── index.md
└── src/
    ├── html.htl
    ├── html.pre.js
    └── static/
        ├── bootstrap.min.css
        └── favicon.ico
```


but I guess, the `getting-started.md`  needs to be adjusted.

**Comment by rofe** [comment]
OK. That's what I thought when I saw full vs simple demo... will open an issue for `getting-started.md`.
