### ISSUE TITLE
send publish service wsk params

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-cli#1378]
**Is your feature request related to a problem? Please describe.**
In order to support package health checks with: 
https://github.com/adobe/helix-publish/pull/394
publish must send wsk credentials to publish service! 

**Describe the solution you'd like**
the PR adjusts the request body for the publish service request, and includes needed parameters

**Describe alternatives you've considered**
No alternatives

**Comment by tripodsan** [comment]
thinking on this again, I don't think that you need to pass long the openwhisk credentials, because we already invoke the `helix-services/publish` in the customers namespace.

I make a small test action:

```js
const openwhisk = require('openwhisk');
async function main(params) {
  const ow = openwhisk();
  try {
    await ow.packages.get({
      name: params.pkgName,
    });
    return {
      body: {
        status: 'package exists',
      }
    }
  } catch (e) {
    return {
      body: {
        status: 'package does not exist',
      }
    }
  }
}
module.exports.main = main;
```

and then test:

```console
$ wsk namespace list
namespaces
tripod
$ wsk action invoke helix-services/tripod-pkg-test -r -p pkgName a950f6025bad13e2cc3f659136694b5a8499111b
{
    "body": {
        "status": "package exists"
    }
}
$ wsk action invoke helix-services/tripod-pkg-test -r -p pkgName a950f6025bad13e2cc3f659136694b5a8499111b_foo
{
    "body": {
        "status": "package does not exist"
    }
}
```

**Comment by MarquiseRosier** [comment]
Ahhhh that's really cool, thanks! :)
