### ISSUE TITLE
Use release branches

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1387]
## Overview
Using semantic-release in CI has the problem, that with protected branches, it cannot commit the updated `package.json` and `CHANGELOG.md` to master.

## Details
`helix-cli` (and other crucial repos) have protected `master` branches enabled and require reviewed and approved pull requests in order to push to master. This is a problem for the `semantic-release` step, which updates the master after the release.

## Proposed Actions
possible workflow:

1. create PR in issue branch
2. approve and merge to master
3. ci runs semantic-release -> detects release
4. semantic release creates new branch for release
5. package.json and changelog is updated in release branch
6. PR is created.
7. PR is auto-approved by github action
8. PR gets merged back to master
9. CI detects release commit and actually releases artifacts.

**Comment by tripodsan** [comment]
I created a github action that implements (7) and (8)
https://github.com/adobe-rnd/github-automerge-action/tree/master/

**Comment by trieloff** [comment]
I think this is only a problem if we don't allow Admins to override the branch protection rules, which is something I could live with.

**Comment by tripodsan** [comment]
ok
