### ISSUE TITLE
Client-side sources not reloaded when switching git branch

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#1389]
**Description**
While developing locally, any source changes trigger a rebuild automatically. But when changing source files by switching git branches, this doesn't happen and the developer is stuck with the sources from the previous branch.

**To Reproduce**
1. Go to Helix (Pages) project
1. `git checkout <some-branch>`
2. `hlx up`
3. Make a change to a CSS or JS file
4. Reload browser to see changes
5. Commit & push
5. `git checkout <other-branch>`
6. Reload browser to original state
7. JS/CSS source changes not reflected

**Expected behavior**
Switching between branches should refresh client-side source files in the same way manual changes do.

**Workaround**
- Restart `hlx up`

**Version:**
7.5.2

**Comment by tripodsan** [comment]
it works for me. are you sure you committed the file that you modified before switching the branch?

![image](https://user-images.githubusercontent.com/917628/80555805-5051cc00-8a0c-11ea-8ac0-84e0bcbca994.png)

**Comment by rofe** [comment]
Weird... I'll try to reproduce it next time.

**Comment by rofe** [comment]
I realized that when I said sources, I actually meant the _client-side_ sources, i.e. content 😬  - so style.css, scripts.js etc. It would be great if one could seamlessly switch between different branches without having to restart in between.

**Comment by rofe** [comment]
I tried to clarify the problem in the description above.

**Comment by tripodsan** [comment]
it seems that the git-server doesn't detect the change to the `.git` files.
@stefan-guggisberg I guess, it would be the simplest to just restart the gitserver or should be implement something in git-server that it detects if the branch is switched?

**Comment by rofe** [comment]
Not exactly sure if this is related, but more recently I noticed when switching branches on a Helix Pages repo, the dev server does attempt to restart after detecting a change in helix-query.yaml (note there's no actual change in that file required to reproduce it). I assume this would fix the issue of loading the content from the correct branch, but then it fails to come back up:
```
helix-query.yaml modified. Restarting dev server...
[hlx] info: Local Helix Dev server stopped.
[git] info: http: server stopped.
[ERROR] encountered unhandled promise rejection at process level: [object Promise], reason: Error: Invalid configuration:
A list of strains and a strain with the name "default" is required.
    at ConfigValidator.assetValid (/usr/local/lib/node_modules/@adobe/helix-cli/node_modules/@adobe/helix-shared/src/ConfigValidator.js:89:13)
    at HelixConfig.validate (/usr/local/lib/node_modules/@adobe/helix-cli/node_modules/@adobe/helix-shared/src/HelixConfig.js:83:27)
    at HelixConfig.init (/usr/local/lib/node_modules/@adobe/helix-cli/node_modules/@adobe/helix-shared/src/HelixConfig.js:88:16)
```
