### ISSUE TITLE
local memory cache for hlx up

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1390]
when working with large external content (eg word2md, gdocs2md), reloading the page to fetch the markdown again is very slow. for local development, modifying the (external) content is rare, but modifying the scripts is common. so it would be cool to have the option to enable some memory cache for the external files.

### suggestion

```
hlx up --cache=external
```

causes all the simulator to cache all content of external sources.

### Workaround:

- create a local structure of the content you are debugging / developping
- download the respective markdown via the word2md action and store it at the correct place
- disable the mountpoint in `fstab.yaml` or just rename `fstab.yaml` to `no_fstab.yaml`

/cc @davidnuescheler @trieloff

**Comment by trieloff** [comment]
Agree in principle, but flip the default.

**Comment by davidnuescheler** [comment]
agreed with @trieloff 

having said that, i think that we possibly should consider implementing this in a more general fashion... 
especially thinking about the data embed and their relationship to a `.json` made me consider that we should more generally support requests to the `.md`.

what i mean is that we could simulate what the world looks like if this was all in a github repo instead of google docs/sheets etc. this would mean that if i can a `/test` gdoc, the same way how i could get to the `/test.html` i should be able to directly request `/test.md`

and the same should true for google sheets where i would end up requesting `/sheet.json` from a sheet.

the reason why i think this is relevant for this conversation, is that i think we might want to consider having the pipeline always fetch the corresponding `.md` or `.json` as its source from the same domain as the incoming request, which would in turn allow us to cache things in the inner (or outer CDN) as well as caching things locally in the same abstraction.

this would also be great for debugging of `.docx` and google docs to md issues...

**Comment by tripodsan** [comment]
I kind of like this, but this would mean quite some change in the entire architecture

- https://example.com/test.html would request the html-pipeline (via dispatch),
- which would request https://example.com/test.md ?
- which would request the md-pipeline (via dispatch again? or direct),
- which would request the gdocs2md

I think the overhead of resolving `/test.md` twice in the dispatch is what makes it a bit expensive. but it would be a nice shift from the complex pipeline to a second action.

we could also shift the _resource loader_ logic from the pipeline to dispatch:

- dispatch checks if the resource is available statically
- dispatch knows the fstab.yaml and can invoke gdocs/word2md
- dispatch can invoke the data embed stuff for .json resources

**Comment by trieloff** [comment]
Maybe we should introduce a new action (and request type) `helix-content-proxy` (name TDB), which

- turns `owner`, `repo`, `branch` into `owner`, `repo`, `ref` using `helix-resolve-git-ref` and a short-lived cache
- fetches `helix-fstab.yaml` and keeps it cached for a while
- depending on the resolved backend and requested content type, fetches the correct resource

|              | `.json`                          | `.md`                       | `.*`                          |
|--------------|----------------------------------|-----------------------------|-------------------------------|
| GitHub       | get *.csv via `helix-data-embed` | `raw.githubusercontent.com` | `raw.githubusercontent.com`   |
| Google Drive | Sheets via `helix-data-embed`    | `gdocs2md`                  | Download file from Google     |
| Sharepoint   | Excel via `helix-data-embed`     | `word2md`                   | Download file from Sharepoint |

* serves the results with 
  * effectively immutable `Surrogate-Control` headers 
  * `ETag` based on resolved `ref`
  * `Surrogate-Key` based on actual content source URL

This keeps `helix-dispatch` as small as it is right now (with the option to shrink away one `resolve-git-ref` step – and it wouldn't hinder porting dispatch to Compute@Edge.
---

The next question would be how to serve the `helix-content-proxy` from the web. I fear that using straight `https://www.example.com/README.(md|json)` would lead to conflicts if customers want to overlay (for good reason) the `md` or `json` extensions.

We have then two options:

1. use a special path like `https://www.example.com/README.hlx_content.(md|json)`
2. use an additional header, i.e. `Accept=application/helix-content`

(1) leads to uglier URLs that are conflict free and easy to invalidate. (2) gives us nice URLs, but we will have to `Vary` on `Accept` (or some derivative) and invalidation gets a bit harder.

---

Speaking of invalidation: push-invalidation of the Fastly-content cache requires knowledge of the hostname or service ID (and token) of the serving domain. @tripodsan do you think that is practical?

Alternatively, we could drop the idea of using the customer's domain name and instead create a shared cache at `content.project-helix.io`, which would be easier to invalidate and would avoid URL conflicts.

**Comment by tripodsan** [comment]
> * depending on the resolved backend and requested content type, fetches the correct resource

it should have the same logic as dispatch today.
1. try the most special location (eg word2md)
2. try the resource on the content github repo (eg. the blog)
3. try the resource on the 2nd content github repo (eg. helix-pages)
4. try the resource on the 2nd static github repo (eg. helix-pages/htdocs)

also note, that the word2md / gdocs2md currently handle the native requests, eg (/welcome.docx or /welcome) and then fallback trying to fetch the markdown, eg (/welcome.md). this functionality can be moved to `helix-content-proxy`, if we want to implement the google-drive, one-drive logic again. otherwise I would keep this in the md converters.

> The next question would be how to serve the helix-content-proxy from the web. I fear that using straight https://www.example.com/README.(md|json) 

I think having an inner and outer CDN for all customers is preferred. e.g. serve the `.md` always from the inner CDN and cache it there.

**Comment by tripodsan** [comment]
> Speaking of invalidation: push-invalidation of the Fastly-content cache requires knowledge of the hostname or service ID (and token) of the serving domain. @tripodsan do you think that is practical?

as long as the repository where the change happens is controlled by helix-bot, this is possible, at least for the inner CDN. I'm not sure how this works if we don't control the outer CDN. maybe with an extra observation listener.

**Comment by tripodsan** [comment]
> This keeps `helix-dispatch` as small as it is right now (with the option to shrink away one `resolve-git-ref` step – and it wouldn't hinder porting dispatch to Compute@Edge.

what about hlx-static? what would use it?

**Comment by trieloff** [comment]
I'd leave the outer CDN out of the picture. You could have a Cloudflare or Akamai as outer CDN.

**Comment by trieloff** [comment]
`hlx-dispatch` would still call `helix-static`, which would still go to GitHub directly. We don't use fstab for static resources, afaik.

**Comment by trieloff** [comment]
> I think having an inner and outer CDN for all customers is preferred.

I think the outer CDN is a crutch and I'd very much prefer if we had custom domains on the inner CDN.

**Comment by tripodsan** [comment]
> `hlx-dispatch` would still call `helix-static`, which would still go to GitHub directly. We don't use fstab for static resources, afaik.

ok. so this would _only_ be for true (transformed) content....

**Comment by trieloff** [comment]
Re https://github.com/adobe/helix-cli/issues/1390#issuecomment-625749290

I'd try to make as little changes as possible, so don't move fallback logic from `dispatch` or `*2md` into `content-proxy`. Ideally, the only other part affected by introducing the content proxy would be the pipeline.

**Comment by trieloff** [comment]
One more thing to consider: we will get a 1 MB limit for Markdown that we didn't have before.

**Comment by tripodsan** [comment]
> One more thing to consider: we will get a 1 MB limit for Markdown that we didn't have before.

yes...we already do for word2md

**Comment by trieloff** [comment]
Good idea. With Fastly in front of the proxy, the redirect trick becomes viable again.

**Comment by davidnuescheler** [comment]
> I fear that using straight https://www.example.com/README.(md|json) would lead to conflicts if customers want to overlay (for good reason) the md or json extensions.

i would be interested in understanding any of those "good" reasons. i think that pre-emptively trying to avoid a hypothetical collision has lead us in the past to a lot of pain and complexity, like the jcr namespaces.

**Comment by trieloff** [comment]
Good reason to overlay JSON: you are building an SPA on Helix and want to serve JSON (but in a format that is not quite like the OOTB format we offer) – you do care that URLs are simple and find something like https://example.com/myapp/content.spa.json to be distasteful.

**Comment by davidnuescheler** [comment]
from the table: github / json in https://github.com/adobe/helix-cli/issues/1390#issuecomment-625691704

> get *.csv via helix-data-embed

@trieloff i think for this to be intuitive and consistent it should be just raw.githubusercontent.com as well. i think there is a lot of value and being able to `serialize` things into a github repo, the way the pipeline picks it up.

also, i really haven't run into a usecase where i was working on github repo and a `.csv` was significantly easier to find than a `.json`. i think csv is kind of an odd ball in github land.

**Comment by davidnuescheler** [comment]
> Good reason to overlay JSON: you are building an SPA on Helix and want to serve JSON (but in a format that is not quite like the OOTB format we offer) – you do care that URLs are simple and find something like https://example.com/myapp/content.spa.json to be distasteful.

well, if we are talking about "taste", and you are mentioning a SPA, i think that's whole different can of worms. :) 

jokes aside... i'd rather inconvenience the SPA developer who most likely feels more at home in the `cgi-bin` directory anyway, than to build in another indirection for our own standard case...

**Comment by tripodsan** [comment]
> Good reason to overlay JSON: you are building an SPA on Helix and want to serve JSON

but I doubt, that you use semi-static json originating from data-embed or github. you either have your own action that generates the json, a json pipeline or a cgi-bin... in anyways, it would probably be addressed differently anyways.

**Comment by trieloff** [comment]
Ok, I'm convinced.

Next question: are our customers going to see it as problematic that their "raw content" is available on the web. I know AEM customers do go considerable lengths to disable the Sling JSON features on publish instances.

**Comment by tripodsan** [comment]
> Next question: are our customers going to see it as problematic that their "raw content" is available on the web.

that's where the outer CDN can block those... :-)

**Comment by trieloff** [comment]
If there is any chance that this will end up on a go-live checklist (for reasons of security, paranoia, etc) then I'd rather have a bundled solution that makes the go-live effort smaller.

**Comment by davidnuescheler** [comment]
hmm... i think there is a difference between the sling JSON service (which gives you access to all sorts of "internal" information thanks to its general purpose exposure of JCR) while the `.md` and `.json` representations of pages that are published anyway as html (and/or JSON) seems to be disclosing a lot less information. 

...or let me put it this way, if you choose to publish the data of a spreadsheet (and we even limit that to the first or a named sheet to get started) i think the expectation would be that your (filtered) data will be read as JSON.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
