### ISSUE TITLE
generate manifest.json with information of the static files

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#144]
since the list of static files is know during deploy time, it can be included into the bundled distributor.

**Comment by trieloff** [comment]
I'd suggest we remove the bundled distributor entirely, given that we have a good way of using GitHub as the distributor.

**Comment by tripodsan** [comment]
this is only a pre-step before we can merge the static-serving logic. As I mentioned somewhere else (can't remember where :-) Having the static delivery redirector (disty) bundled together with the html.js action saves us 1 action. so we still can have a disty per strain, but the config in the VLC is much easier, as we only need to handle 1 case.

**Comment by tripodsan** [comment]
Ok, let's just generate the `manifest.json` for now. I think it could serve as a good source of information for any _static deployment_ mechanism. I will also include the content-hash of the files. eg:

```json
{
  "styles.css": {
      size: 1234,
      hash: "..."
  },
  "favicon.ico": {
  ...
  }
}
```
