### ISSUE TITLE
local lighthouse score testing mode

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-cli#1467]
In current web development the lighthouse score is a great overall user experience measurement.

There are a range of factors that we either cannot control directly or there is simply too big of a variance to make an assessment of a specific isolated change and the relative impact on the light house score.

Therefore it would be great to be able to remove all the moving pieces and benchmark against a fully cached local copy of a page and quickly iterate css and js code to see what the impact is in a reliable fashion.

I think a good example is the question if the server sided addition via markup.yaml really has a measurable impact on the lighthouse score see https://github.com/adobe/theblog/issues/241

**Comment by tripodsan** [comment]
won't fix for now.
