### ISSUE TITLE
[hlx strain] non-default strain doesn't work

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#148]
Following the [Getting Started: Strain](https://github.com/adobe/project-helix/blob/master/getting-started.md#strain) walk through: 

When changing the name in the generated `.hlx/strains.yaml` from `default` to something else (e.g. `demo`), `hlx strain` runs successfully. However, requests sent to the domain (e.g. `demo.project-helix.info` return `401`.

changing the name to `default` and running `hlx strain` again solves the problem.

**Comment by trieloff** [comment]
A first "fix" could be some validation that checks for the existence of a `default` strain and makes `hlx strain` fail if not found.
