### ISSUE TITLE
New command? hlx log

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#1518]
This would be just the log portion of `hlx publish` to be used for outer CDNs with https://github.com/adobe/helix-logging/releases/tag/v1.5.0

**Comment by tripodsan** [comment]
- access control could be checked via github push rights on the github repository
- the format could be access.log

**Comment by trieloff** [comment]
Clarification: I intended the command to automate the creation of a logging config on a Fastly service, not as a way to retrieve logs.

**Comment by rofe** [comment]
Maybe it should be called `hlx logging` then?

**Comment by tripodsan** [comment]
or `hlx publish-logging`

**Comment by tripodsan** [comment]
> That's almost as long as the curl command this should replace :)

just, but you also only need it once, when you add a new outer cdn....

so why not:

```
hlx publish --logging=<fastlySvcID0> --logging=<fastlySvcID1>
```

**Comment by trieloff** [comment]
`hlx cdn --logging=<fastlySvcID0> --logging=<fastlySvcID1> --fastlyToken=… --coralogixToken=…0`?

**Comment by tripodsan** [comment]
not needed anymore. server log is irrelevant for developer.
