### ISSUE TITLE
OOTB cli experience 

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-cli#1535]
currently a `hlx-up` with a helix pages project (and probably also straight up) creates a lot of logging output, warnings and errors even though everything works 100% as expected.

i think it would be great to consider what the log-levels really should be especially as we have a lot of `404`s that are completely expected. i don't think this is as simple as just raising the default error level from `INFO` but instead it probably requires that we log differently.

**Comment by tripodsan** [comment]
won't fix for helix 2. fixed for helix 3.
