### ISSUE TITLE
[hlx demo] references to static files are wrong

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#159]
Run 
```
hlx demo test
cd test
hlx up
```
`style.css` is not delivered.

@trieloff @tripodsan

**Comment by trieloff** [comment]
See adobe/petridish#51

**Comment by tripodsan** [comment]
This is a problem of the demo code, not petridish.

**Comment by tripodsan** [comment]
(well, and petridish)

**Comment by tripodsan** [comment]
also a problem in --full
