### ISSUE TITLE
[hlx up] support intuitive debugging of project code 

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#162]
in keeping with our manifesto ([Local Development](https://github.com/adobe/project-helix/blob/master/manifesto.md#local-development-t)), local debugging of project code (e.g. `html.pre.js`, `html.htl`) should be intuitive, smooth and painless, i.e. not requiring complex setups.

**scenario**: a developer new to `project-helix` and not familiar with `node.js` starts developing a helix project following this walk-through:

* download and install the binary `hlx` command-line tool:
  ```bash
  curl -OL https://github.com/adobe/helix-cli/releases/download/v0.3.2/hlx_install.sh
  chmod 755 hlx_install.sh
  ./hlx_install.sh
  ```
* create a new project `hello_helix` and run it locally:
  ```bash
  hlx demo hello_helix
  cd hello_helix
  hlx up
  ```
  a browser opens, rendering the project's `index.html`.
* start [VSCode](https://code.visualstudio.com/) and open the `hello_helix` folder. 
* open `src/html.pre.js` and place a breakpoint on a line of code.
* switch to the Debug view, select `Attach to hlx` from the dropdown and start debugging.
* after refreshing the browser the debugger halts at the breakpoint in `src/html.pre.js`.

**Comment by stefan-guggisberg** [comment]
what's currently already possible:

* run `hlx up` and determine process id (`ps -ef | grep hlx` or see console output `[git] info: [<process id>] HTTP: listening on port ...`)
* start VSCode and open the project folder
* switch to Debug view and add/edit a launch configuration `Attach by Process ID`
* replace `processId` attribute value with process id from 1st step
* start debugging
* go to `Loaded Scripts` pane and open `~/...../.hlx/build/html.js`
* set a breakpoint e.g. in `pre` function (->`html.pre.js`) or the `run` function (-> `html.htl`)
* after refreshing the browser the debugger halts at the breakpoint

**Comment by tripodsan** [comment]
I would also investigate how other frameworks do it. AFAIK, you can easily tell chrome where your scripts are and together with the source maps, you can set the breakpoint directly in the browser.

ideally, the debug support is independent of the IDE. i.e. the diversity in IDE is greater than the diversity in Browsers.

**Comment by stefan-guggisberg** [comment]
what's working as of `hlx` v0.7.5:

* create a new project hello_helix:
  ```
  hlx demo hello_helix
  cd hello_helix
  ```
* open project in IDE (VSCode):
  ```
  code .
  ```
* set breakpoint in `src/html.pre.js`, switch to the Debug view, select `Attach` from the dropdown and start debugging.
* go back to the terminal and start helix environment:
  ```
  hlx up
  ```
  a browser opens, rendering the project's `index.html`
* after refreshing the browser the debugger halts at the breakpoint

**Comment by stefan-guggisberg** [comment]
_intuitive debugging_ as described in this issue is working, closing this issue.

debugging support in `.htl` templates is tracked in a separate issue: https://github.com/adobe/htlengine/issues/22
