### ISSUE TITLE
improve autodeployment selection logic

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#166]
I think it is more common during development to use manual deployment often, so using `--no-auto` is a bit tedious. 

maybe the existence of the `.cicleci/config.yaml` should select the default behaviour. i.e. if there is a circleci config, run autodeployment, unless `--no-auto` is specified.

**Comment by trieloff** [comment]
We could do this: `--auto` has three values `yes`, `no`, and `auto`. `--auto=yes` forces the CircleCI setup, `--auto-no` does a local deployment. `--auto=auto` tries to find the right setting:

- in CircleCI `CI=true`: `no`
- if `.circleci/config.yaml` does not exist or `--circleci-auth` isn't set: `no`
- else: `yes`

**Comment by rofe** [comment]
Is this issue still relevant?

**Comment by tripodsan** [comment]
I would like to remove the autodeployment logic from the CLI, until we really want to use it.

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
