### ISSUE TITLE
hlx build does not re-generate the compiled js files

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#176]
To fix a bug in the generated htl to js code, I updated hlx-cli to the latest version. 

I ran an explicit `hlx build` assuming it would update all my code to the latest and greatest. But I did not, my generated `html.js` still contained the (broken) old code. Only solution was to `rm -fr .hlx` folder.

Several options here: 
* running `hlx build` does always regenerate everything (no cache)
* add a `--force` or `--no-cache` options to build
* add a `hlx clean` command that would guaranty the user a clean state

**Comment by trieloff** [comment]
Why don't we change the default to no-cache until `build` gets too slow?

**Comment by tripodsan** [comment]
@kptdobe can you still reproduce this?

I tried:

```
$ hlx demo cleantest
$ cd cleantest
$ hlx build
$ cp .hlx/build/html.js ori.js
$ vi src/html.htl
$ hlx build
$ diff -u ori.js .hlx/build/html.js
--- ori.js	2018-10-02 14:02:45.000000000 +0900
+++ .hlx/build/html.js	2018-10-02 14:03:04.000000000 +0900
@@ -205,7 +205,7 @@
     out("\n\n<hr></hr>\n<em>");
     const var_5 = "generated at " + content["time"];
     out(var_5);
-    out("</em>\n\n</body>\n</html>\n");
+    out("</em>\ntest\n</body>\n</html>\n");
   });
 }
```

and also with the pre.js

```
$ vi src/html.pre.js
$ hlx build
$ diff -u ori.js .hlx/build/html.js
--- ori.js	2018-10-02 14:02:45.000000000 +0900
+++ .hlx/build/html.js	2018-10-02 14:05:25.000000000 +0900
@@ -129,6 +129,7 @@
  * @param payload.content The content
  */
 function pre(payload) {
+  // new test
   payload.content.time = `${new Date()}`;
 }

@@ -205,7 +206,7 @@
     out("\n\n<hr></hr>\n<em>");
     const var_5 = "generated at " + content["time"];
     out(var_5);
-    out("</em>\n\n</body>\n</html>\n");
+    out("</em>\ntest\n</body>\n</html>\n");
   });
 }
```

But I think the problem arises when removing files:

```
$ rm src/html.pre.js
$ hlx build
🚨  /Users/tripod/codez/helix/sandbox/cleantest/src/html.pre.js: ENOENT: no such file or directory, open '/Users/tripod/codez/helix/sandbox/cleantest/src/html.pre.js'
Error: ENOENT: no such file or directory, open '/Users/tripod/codez/helix/sandbox/cleantest/src/html.pre.js'
ENOENT: no such file or directory, open '/Users/tripod/codez/helix/sandbox/cleantest/src/html.pre.js'
$ rm -rf .hlx/cache/
$ hlx build
✨  Built in 522ms.

.hlx/build/html.js                 9.2 KB    471ms
.hlx/build/favicon.26242483.ico     921 B     22ms
.hlx/build/style.e308ff8e.css       711 B     28ms

✨  Moving static files in place:
dist/favicon.26242483.ico
dist/style.e308ff8e.css
```

and probably also when adding files.

**Comment by kptdobe** [comment]
This specific case was when you upgrade the helix-cli: 
- make a change in the htlengine for example to expect a different html.js output.
- then run `hlx build`

I assume the reason is that the project files (html.pre.js, html.htl) have not been modified... but the output should be different. Probably an edge case but still, the only solution is to remove the folder or "touch" the project files.

Adding a new renderer (like selector_html.pre.js) while running `hlx up` does not trigger a re-build but that's a different issue.

**Comment by tripodsan** [comment]
> Adding a new renderer (like selector_html.pre.js) while running hlx up does not trigger a re-build but that's a different issue.

this will be fixed  with https://github.com/adobe/helix-cli/pull/221
