### ISSUE TITLE
Support self-test with hlx test

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#18]
When developing templates, you want to be able to quickly validate if you are getting the required output.

## Three places to run the test
1. `--local` loads your local `.hlx/build` scripts or petridish, runs them and validates the output
2. `--runtime` does the same, against the function deployed in OpenWhisk
3. `--live` makes an HTTP request to the deployed function through the CDN

## How to specify input:

In `tests/` create a file `[<selector>_]?<extension>.[0-9]+.spec.json`, `[<selector>_]?<extension>.[0-9]+.spec.md`, or `[<selector>_]?<extension>.[0-9]+.spec.har` that matches your `selector_extension` pair. For the default, you would have a `html.0.spec.json`. For the selector `example`, you'd have `example_html.0.spec.json`

The number before `.spec` allows the creation of multiple test files.

### JSON Input

JSON can only be used for `--local` and `--runtime`. The entire JSON object will be used as the pipeline input.

JSON can be used in combination with Markdown.

### Markdown Input

Markdown can only be used for `--local` and `--runtime`. It can be used in combination with JSON.

The content of the JSON document will be put into `resource.body` of the pipeline payload, so that the HTTP fetch step can be skipped, enabling offline testing.

### HAR Input

If you create a `.har` (this is the HTTP Archive you can capture in your browser's dev tools), it will be used to make requests against the `--live` instance or against petridish.

## How to specify output:

In `tests/` create a file `[<selector>_]?<extension>.[0-9]+.out.<extension>`, e.g:
- `html.0.out.html` for default HTML
- `json.0.out.json` for default JSON
- `example_html.0.out.html` for HTML with the `example` selector

**Comment by trieloff** [comment]
Note: `request` has support for HAR: https://github.com/request/request/blob/master/README.md#support-for-har-12

**Comment by filmaj** [comment]
I'm not sure I would create a JSON file of expected output. That seems like high maintenance. It would be awesome if helix could compare against the actual markdown so that these are pretty much "free" tests that helix devs get without having to implement anything.

**Comment by trieloff** [comment]
The JSON expected output is for using the JSON pipeline, i.e. when you want to create JSON

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
