### ISSUE TITLE
support helix pages with src/ directory

### ISSUE THREAD

**Issue by maxakuru** [adobe/helix-cli#1829]
**Is your feature request related to a problem? Please describe.**
Using `src/` is a common pattern, right now using the flag `--pages-url` with a repo that contains a src directory silently ignores it, skips the reverse proxy, and uses Helix instead of Helix pages.

**Describe the solution you'd like**
Any one of..
1. use something else to identify a regular helix repo
2. default to pages when `--pages-url` flag is set
3. add a flag to override and explicitly specify pages

ref: https://github.com/adobe/helix-cli/blob/80501249efdcce1c217ec30aa46bea47df8bc8c6/src/helix-pages.js#L75

**Describe alternatives you've considered**
Considered removing the src directory, but it's nice to keep everything in one place and when using certain frameworks they depend on a src directory (if using a directory at all)

**Comment by trieloff** [comment]
This would be a breaking change, but I don't think it would be an issue, at least with hlx3, as the legacy hlx1 use case will be all gone by then.

**Comment by maxakuru** [comment]
makes sense.. would that mean waiting for archiving hlx1 projects or is cutting a major with this alright? 

I started adding a simple change where if `--pages-url` flag is set, HelixPages is used.. 
agreeable? any preference? @trieloff @tripodsan

**Comment by tripodsan** [comment]
IMO, we can throw away all hlx1 related stuff and only keep the hlx pages proxy.
as long as we release it as a new major version.

**Comment by trieloff** [comment]
Agree. Should the hlx1 stuff become relevant again or be needed for bug fixes (both unlikely), we can create a release branch for the old version.

**Comment by tripodsan** [comment]
fixed with #1857
