### ISSUE TITLE
Breaking: Remove helix 2 support

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1848]
In order to keep the helix-cli light, we can remove all helix2 related code:

### cli
- `hlx up`: only support _helix pages_ mode by default and proxy to the `*.hlx3.page` domain
- `hlx build`: remove
- `hlx package`: remove
- `hlx deploy`: remove
- `hlx publish`: remove
- `hlx clean`: remove
- `hlx` should default to `hlx up`

### internal
- if helix config files are invalid, only report warning
- integrate `helix-simulator` proxy directly into `helix-cli`

**Comment by rofe** [comment]
- `hlx demo`: remove
