### ISSUE TITLE
helix cli follows 302/301 transparently

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-cli#1863]
instead of serving a `301` or `302` with the respective location header to the browser through `localhost:3000` helix-cli seems to resolve the `301/302` and serve up `200`

**Comment by tripodsan** [comment]
for relative redirects, this should be the case. but not for absolute ones.
it might be that absolute ones to the `pagesUrl` host are not properly handled.

@davidnuescheler can you give an example?

**Comment by davidnuescheler** [comment]
first of all I don't think there should be any difference in behavior between absolute and relative redirects, and every 301/302 that is served from hlx3.page should bubble up as a 301/302 on localhost identically as it is served from the pagesUrl. Also, the redirects spreadsheet should (just like the rest of helix) work with absolute URLs as input from the user and if needed magically make them relative where appropriate.

As an example feel free to run https://redirect-manager--spark-website--adobe.hlx3.page/tools/redirects/manager.html locally and see the difference.

**Comment by tripodsan** [comment]
ah... you mean it should redirect you away, but the current behaviour is wrong, as the proxy internally follows the redirect.
