### ISSUE TITLE
support local head.html development

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1867]
since the `head.html` in included in the helix pipeline, local changes during development are not reflected and need to be pushed to github frequently.

**suggestion:**
the proxy should replace the `head.html` section with the local version if it was modified.

**Comment by kptdobe** [comment]
Why do you need to detect the position while you could subtract the current one and add the local one ?

**Comment by tripodsan** [comment]
> Why do you need to detect the position while you could subtract the current one and add the local one ?

because then I need to read the current one :-) but good idea.

**Comment by tripodsan** [comment]
@kptdobe it's not so easy... I finished implementing it, but it never works in real life. because the pipeline-service is adding the head.html via dom, so the html might not be 100% the same.

so we also need to parse the HTML and replace the head HTML in the dom....
