### ISSUE TITLE
CORS header support for sidekick project config

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#1896]
In order to be able to test sidekick module and project configs locally in the sidekick extension, we need to add `Access-Control-Allow-Origin: *` to `/tools/sidekick/config.js` and `/src/sidekick/module.js` in the proxy.

See also
- https://github.com/adobe/project-helix/issues/613
- https://github.com/adobe/helix-sidekick/issues/146

**Comment by rofe** [comment]
The current solution from #1897 unfortunately doesn't help, because `helix-sidekick` isn't actually a Helix 3 project, so `hlx up` will always serve local files only, not proxied ones. `http://localhost:3000/src/sidekick/module.js` does not have CORS headers.

**Comment by tripodsan** [comment]
ok
