### ISSUE TITLE
concise download url for binary distribution 

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#194]
a concise url for downloading the latest version of the binary `hlx` installer would be nice.

e.g. `https://adobe.ly/helix-cli` or `https://helix.io/install.sh`

the url should automatically redirect to the latest release on GH (e.g. `https://github.com/adobe/helix-cli/releases/download/v0.7.1/hlx_install.sh`)

**Comment by stefan-guggisberg** [comment]
related to #127

**Comment by tripodsan** [comment]
I think this can be closed.

url is: https://www.project-helix.io/cli.sh
