### ISSUE TITLE
Move all owrequest adapter to pipeline

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#196]
The `OutputTemplate.js` contains a lot of internal logic that converts the ow-request to `(payload, action)`. 

It would be nicer to have this in _hypermedia-pipeline/adaptOWRequest_

**Comment by trieloff** [comment]
I came across the code in the pipeline again today. One challenge here is that pipeline considers action to be immutable, so we need to figure out what to do here. One way could be to have a helper function in pipeline that gets called by OutputTemplate.

**Comment by tripodsan** [comment]
good point. why not add it to the `Pipeline` ? https://github.com/adobe/hypermedia-pipeline/blob/master/src/pipeline.js#L57
