### ISSUE TITLE
Get rid of Helix pages specific code

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1990]
Remove https://github.com/adobe/helix-cli/blob/main/src/helix-pages.js from the code base but also:

Also the cli says:

![image](https://user-images.githubusercontent.com/474200/164009745-fbbd13d2-d686-4156-b329-b1574c1baf10.png)

![image](https://user-images.githubusercontent.com/474200/164009817-1cf7fb2b-7354-48b2-92c0-1085d60ed07c.png)

We need a new ASCII art :)

**Comment by tripodsan** [comment]
well, it's still helix-pages - or just `helix` ?

**Comment by tripodsan** [comment]
done.
