### ISSUE TITLE
Enable bash completion in hlx cli

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#202]
See http://yargs.js.org/docs/#api-completioncmd-description-fn

**Comment by tripodsan** [comment]
the link above does not show any docs...

**Comment by trieloff** [comment]
Hm. Link works for me. The gist of it: add `yargs.completion()` and then running `hlx completion` will print a script that can be appended to `~/.bash_completion`

**Comment by trieloff** [comment]
@stefan-guggisberg can we install the bash completion script using the installer?

**Comment by stefan-guggisberg** [comment]
@trieloff i've added it to the install script: d825aa0
