### ISSUE TITLE
hlx strain fails with Fastly

### ISSUE THREAD

**Issue by cwoeltge** [adobe/helix-cli#205]
This new block is giving a syntax exception:

  # Gets the white-listed params for the current strain
    sub hlx_params {
      set req.http.X-Params = "";
      set req.http.X-Encoded-Params = "";
      # first load the params from the strain
      set req.http.X-Params = table.lookup(strain_params, req.http.X-Strain);
      if (!req.http.X-Params) {
        set req.http.X-Params = table.lookup(strain_params, "default");
      }
      if (req.http.X-Params) {
        set req.http.X-Old-Url = req.url;
        set req.url = querystring.regfilter(req.url, req.http.X-Params);
        set req.http.X-Encoded-Params = urlencode(req.url.qs);
      }
    }

Exception:

```
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body:
      { msg: 'Bad request',
        detail: 'Syntax error: Expected `STRING` expression\nat: (input Line 1010 Pos 50)\n    set req.url = querystring.regfilter(req.url, req.http.X-Params);\n-------------------------------------------------#################--' } } }
Error setting one or more edge dictionary values
Error: Unable to activate new configuration
    at request.then.catch (/__enclose_io_memfs__/src/strain.cmd.js:382:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error setting one or more edge dictionary values
```

**Comment by trieloff** [comment]
See #206 – it looks like the parameter whitelist won't work with edge dictionary values.
