### ISSUE TITLE
rename binary from `hlx` to `aem`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#2064]
- rename the binary name to `frk` (or `fra` or `frn` or `fr` or `f`)
- is it possible to stay backward compatible? if yes, display a _deprecated_ message when using `hlx`

**Comment by trieloff** [comment]
I've started to register a couple of `fkln.*` domains, so we could keep this in line.

To keep it backwards compatible, this could work:

https://github.com/adobe/helix-cli/blob/b3fa8640dbfebcd40b4254f0656ab203fd6e3a9e/package.json#L7-L9

to

```json
  "bin": {
    "hlx": "./index.js",
    "fkln": "./index.js"
  },
```

**Comment by kptdobe** [comment]
@tripodsan why you do not agree with Lars's solution ?

**Comment by tripodsan** [comment]
> @tripodsan why you do not agree with Lars's solution ?

because it associates with `F**kling`

**Comment by tripodsan** [comment]
I think `fr` would be the better option :-)

**Comment by trieloff** [comment]
I got you, @kptdobe:

<img width="1103" alt="Screenshot 2022-10-27 at 15 08 17" src="https://user-images.githubusercontent.com/39613/198398502-a4e34f65-81e1-47ed-86d2-12a5c5e62cc4.png">

**Comment by trieloff** [comment]
Without kidding, I prefer `fr` over `frk`.

Maybe `fri` would work, too. Sounds good, too.

**Comment by tripodsan** [comment]
or `aem`

**Comment by amol-anand** [comment]
Agree with calling it `aem`! please review PR

**Comment by tripodsan** [comment]
> Agree with calling it `aem`! please review PR

your PR is still a draft... I can't review it.

**Comment by amol-anand** [comment]
Ready for review now
