### ISSUE TITLE
CI build of hlx is broken

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#208]
the `hlx` binary doesn't include `nodegit`:

```
$ hlx up
  Cannot find module 'nodegit'
```

that's probably due to the fact that the `nodegit` dependency is now resolved via GH url instead of npm.

**Comment by trieloff** [comment]
Maybe we should add a quick validating script to the end of the build process.

**Comment by stefan-guggisberg** [comment]
@trieloff yes. but i'd be more interested in finding the cause of the broken builds.

**Comment by stefan-guggisberg** [comment]
as of 387aa6b193cb8e0cb9479944b0ffba9b9ade58a7 CI build of `hlx` installer is working again. successfully tested with `hlx v0.7.10-pre.0`.
