### ISSUE TITLE
hlx import should print the version of the importer-ui

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#2093]
**Is your feature request related to a problem? Please describe.**
it would help to debug issues a customer might have, if the version of the importer-ui would be visible either in the CLI or in the UI itself.

**Describe the solution you'd like**
print the importer-ui version to the cli output, eg:

before:
```
Fetching latest version of the Franklin Import UI.
Franklin Importer UI is now up-to-date.
```

suggested:
```
Fetching latest version of the Franklin Import UI.
Franklin Importer UI is now up-to-date (version 2.0.1).
```

/cc @kptdobe

**Comment by amol-anand** [comment]
This already happens currently. see screenshot below:
![Screenshot 2023-09-15 at 3 46 19 PM](https://github.com/adobe/helix-cli/assets/7074782/c946a9f6-db0b-4bca-ac67-4ff7b1cbef74)
