### ISSUE TITLE
can not load files with spaces in filename

### ISSUE THREAD

**Issue by synox** [adobe/helix-cli#2145]
**Description**
Added a file `MacOS Maximize.svg` to `/icons/dealer-locator`. Then opened in the browser: http://localhost:3000/icons/dealer-locator/MacOS%20Maximize.svg - returns 404.

**To Reproduce**
1. add a file `MacOS Maximize.svg` to `/icons/dealer-locator`. 
2. open: http://localhost:3000/icons/dealer-locator/MacOS%20Maximize.svg 
3. see 404.

**Expected behavior**
Should load files with spaces.

**Screenshots**
```
warn: Proxy GET request to https://main--vg-volvotrucks-us--hlxsites.hlx.page/icons/dealer-locator/MacOS%20Maximize.svg: 404 (text/html; charset=utf-8)
```

**Version:**
14.21.4

**Additional context**

**Comment by tripodsan** [comment]
filenames should be all lowercase, and only use alphanumeric ascii and `_-`.

**Comment by synox** [comment]
I think we should support spaces. Are spaces supported on the CDN?
