### ISSUE TITLE
Use fastly-native-promise

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#219]
See if https://www.npmjs.com/package/fastly-promises is useful for us, otherwise contribute missing features or create our own.

**Comment by trieloff** [comment]
The project seems not to be actively maintained, see philippschulte/fastly-promises#5

**Comment by tripodsan** [comment]
yes... I saw it as well afterwards... but we can ask him to help ? I think it's a good approach. or just fork it.

**Comment by trieloff** [comment]
I've reached out to Philipp. 

One thing I'm not sure about: Fastly-Promises uses Axios, which does the same as request-promise we are using everywhere else.

**Comment by tripodsan** [comment]
> Fastly-Promises uses Axios

yes, we might just replace it. I think it has some nice features like default headers. but maybe he just used it because it is supports browsers

**Comment by tripodsan** [comment]
also see additional API calls we need elsewhere: https://github.com/adobe/helix-bot/blob/hlxctl/actions/hlxctl/src/Fastly.js.

I suggest to create a new package altogether: `node-fastly` ?

**Comment by tripodsan** [comment]
closing due to https://github.com/adobe/fastly-native-promises

**Comment by tripodsan** [comment]
updated comment to clarify that we want to use  https://github.com/adobe/fastly-native-promises

**Comment by trieloff** [comment]
I'd close this issue, as we are using it in the place where I want to use it #468 and I'd remove the existing publish functionality as soon as possible, so don't spend time to refactor it.
