### ISSUE TITLE
Improve snapshot deployment

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#22]
- tag snapshots as `next`, not `latest`
- create git tags for snapshot releases
- document versioning in contributing.md

**Comment by trieloff** [comment]
To make git tagging work in CircleCI, go to https://circleci.com/gh/adobe/helix-cli/edit#checkout and add a user-specific deploy key

**Comment by trieloff** [comment]
And here's our first auto-tagged tag: https://github.com/adobe/helix-cli/tree/0.1.0-SNAPSHOT.47

**Comment by trieloff** [comment]
@tripodsan let me know what you think of this approach, we can replicate it for the other projects, too

**Comment by tripodsan** [comment]
that's ok. but I think we should only use `latest` for releases, i.e. not for `SNAPSHOT` versions.

**Comment by trieloff** [comment]
Yes, that's what's happening. Manual releases use `--tag latest`, automatic SNAPSHOTs use `--tag next`
