### ISSUE TITLE
Unable to up the server on localhost

### ISSUE THREAD

**Issue by vasiurrahmangh** [adobe/helix-cli#2238]
**Description**

$ hlx up

Warning: Your '.env' file is currently not ignored by git.
This is typically not good because it might contain secrets
which should never be stored in the git repository.

    ____              __    ___   v14.24.17
   / __/______ ____  / /__ / (_)__  
  / _// __/ _ `/ _ \/  '_// / / _ \ 
 /_/ /_/  \_,_/_//_/_/\_\/_/_/_//_/ 

warn: Unable to verify main branch via https://main--helix-cli--adobe.hlx.page/fstab.yaml (404). 
Maybe not pushed yet?
info: Starting Franklin dev server v14.24.17
info: Local Franklin dev server up and running: https://localhost:3000/
info: Enabled reverse proxy to https://main--helix-cli--adobe.hlx.page
error: error while loading local head.html from C:\S-Drive-A\helix\helix-cli\head.html: ENOENT   
error: error while loading head.html from https://main--helix-cli--adobe.hlx.page/head.html: 404
opening default browser: https://localhost:3000/

**Version:**
v14.24.17

**Additional context**

**Comment by tripodsan** [comment]
- are you running `hlx up` in a checkout of your helix project? (i.e. not helix-cli directory)
- what is the problem? the output looks good to me.
- are you sure it reports `https://localhost:3000/` (not http?)
