### ISSUE TITLE
fix: validate urls before opening them [AEM-04]

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#2257]
**Description**
Follow up to #2149 from remediation: 

We noted that such URL‐encoding was not applied for the `hlx up` or `hlx import` command. It is therefore still possible to inject OS commands. The following commands will run `calc.exe` on the host machine:
```
1 $ aem up --open 'https://$(calc.exe)'
2 ...
3
4 info: Starting AEM dev server v15.0.1
5 info: Local AEM dev server up and running: http://localhost:3000/
6 info: Enabled reverse proxy to https://main--retest-website1--username.hlx.page
7 opening default browser: https://$(calc.exe)/
8 $ aem import --open 'https://$(calc.exe)'
9 ...
10
11 AEM Importer UI needs to be installed.
12 Cloning https://github.com/adobe/helix-importer-ui in /tmp/retest-website1/tools/importer.
13 AEM Importer UI is ready. v1.46.1
14 info: Starting AEM dev server v15.0.1
15 info: Local AEM dev server up and running: http://localhost:3001/
16 opening default browser: https://$(calc.exe)/
```

**Expected behavior**
OS command injection prevented

**Comment by tripodsan** [comment]
I can reproduce it on windows:

<img width="841" alt="image" src="https://github.com/adobe/helix-cli/assets/917628/aff11a76-4ef0-4235-b33c-05a128118ebe">

but not on macos:

<img width="1328" alt="image" src="https://github.com/adobe/helix-cli/assets/917628/631b8c6f-4c2a-4abe-8ca5-a96027c050ef">

I guess we just validate the hostname

**Comment by tripodsan** [comment]
related: https://github.com/sindresorhus/open/issues/323
