### ISSUE TITLE
Really hard to deploy: from [hlx demo] to [hlx publish], review and document

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#229]
Here is the process to publish a site starting from scratch and all the pain points and undocumented / missing / broken pieces:

```
hlx demo test
cd test
hlx build
```

Then commit all the required stuff (after adding the .gitignore, see https://github.com/adobe/helix-cli/issues/228).

Load you favorites env variables (HLX_FASTLY_AUTH, HLX_FASTLY_NAMESPACE, HLX_WSK_NAMESPACE, HLX_WSK_AUTH, HLX_CIRCLECI_AUTH).

- [ ] Document env variables and how to load them easily

```
hlx deploy
Automating deployment with https://circleci.com/api/v1.1/project/github///follow
404 - "<!DOCTYPE html>\n<html><head><title>Continuous Integration and Deployment</title><meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type....
```

- [ ] Fix weird output that looks like an error

```
hlx deploy --no-auto
```

- [ ] Either fix the `auto` or just set --no-auto by default

**Comment by tripodsan** [comment]
>  Either fix the auto or just set --no-auto by default

+1, I think `--no-auto` should be default.

**Comment by trieloff** [comment]
```
hlx deploy
Automating deployment with https://circleci.com/api/v1.1/project/github///follow
404 - "<!DOCTYPE html>\n<html><head><title>Continuous Integration and Deployment</title><meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type....
```

It looks like the reason why this fails is that the project does not have a remote.

**Comment by trieloff** [comment]
@kptdobe  [9:55 AM]
> I just published a new version of https://www.project-helix.io
> Just to mention that it was really smooth and worked perfectly on the first shot!

Ok to close this issue for now?
