### ISSUE TITLE
Consider 2 different pages:

### ISSUE THREAD

**Issue by morrisonjk** [adobe/helix-cli#2290]
Consider 2 different pages:
1. https://main--helix-perf-playground--adobe-rnd.hlx.page/test-cases/baseline: `baseline` gdoc page in gdrive
2. https://main--helix-perf-playground--adobe-rnd.hlx.page/test-cases/baseline.html: `index.html` static html file in github

When I run aem up and do the same locally:
1. http://localhost:3000/test-cases/baseline
2. http://localhost:3000/test-cases/baseline.html

both map to my local `/test-cases/baseline.html`

_Originally posted by @kptdobe in https://github.com/adobe/helix-cli/issues/2285_

**Comment by tripodsan** [comment]
duplicate of https://github.com/adobe/helix-cli/issues/2285
