### ISSUE TITLE
Possible to proxy certain paths to different backend?

### ISSUE THREAD

**Issue by kevin-mitchell** [adobe/helix-cli#2299]
## Overview
It would be useful to be able to proxy certain paths to a different "backend", e.g. `localhost:3000/different-app` might be setup to proxy to `http://localhost:8080/different-app`. There are of course many ways this could be done, but it would be convenient for local development if this could be configured through this CLI tool, vs having to bring something else in.

## Details
I took a brief look at [HelixServer.js](https://github.com/adobe/helix-cli/blob/2bab030a6f6c9a087e454a078f1439c0e0761665/src/server/HelixServer.js#L20) and [utils.js](https://github.com/adobe/helix-cli/blob/2bab030a6f6c9a087e454a078f1439c0e0761665/src/server/utils.js) and it seems like this would at least be technically feasible. I'm posting here wondering if I'm perhaps missing something and this is actually already possible (possibly through creative configuration values?), or if there are any thoughts on this.

Thanks for reading!

**Comment by trieloff** [comment]
You can add a proxy around your `*.hlx.page` which does the proxying for certain paths. Then you can use `aem up --pages-url https://main--branch--site.myaemproxyexample.com` to get content from there.

**Comment by kevin-mitchell** [comment]
This would require the proxy logic be implemented outside of the cli though, correct? Given the express server and all it seems like it'd be convenient to do it within this cli right? Maybe being able to provide something in fstab for example, or a different configuration file?

**Comment by trieloff** [comment]
Yes, that would be an external implementation, but it would have the advantage that localhost does not deviate from your preview and production URLs.

**Comment by tripodsan** [comment]
> It would be useful to be able to proxy certain paths to a different "backend",

why would it be useful? even if you proxy it locally, the authors will only see the normal .hlx.page / hlx.live content.

**Comment by kevin-mitchell** [comment]
This is a great point, it wouldn't be useful for authors. In my mind the use would be limited to the developer experience, and a specific use case I have in mind is proxying certain paths for third party integrations, e.g. to avoid cors issues. 

Thank you both for the info/thoughts/time - it sounds like for now I'll look for an external solution for my use case.

**Comment by tripodsan** [comment]
@kevin-mitchell I can see your use-case, where the developer indeed needs to develop an integration to a 3rd party system that will eventually be proxied via the production host (e.g. www.example.com/payment). and this integration doesn't need to be accessed via .hlx.page or hlx.live, as it is not authored. and during local development, you want to avoid cors problems as they will not be a problem in the deployed environment.

as this is a very specific usecase, i don't know if we can add this to the cli

a workaround to the CORS problem is that you disable web security when starting chrome with the `--disable-web-security` command line option. Just be careful that you don't use this browser instance for your regular browsing afterwards, as it comes with security risks.

**Comment by kevin-mitchell** [comment]
@tripodsan yes exactly this:

> ...proxied via the production host (e.g. [www.example.com/payment](http://www.example.com/payment)). and this integration doesn't need to be accessed via .hlx.page or hlx.live, as it is not authored...

I'll add that it's not necessarily just CORS but also things like potential shared `localStorage` / `sessionStorage` for example.

Anyway it is very reasonable _not_ to support this use case in the cli as it's probably a bit specific and there are likely better ways to handle this (ideally using the same systems as production), I just figured I'd make sure it wasn't possible.

Thanks again!
