### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by touseefkhanstewart** [adobe/helix-cli#2306]
**Description**
While trying to run aem up command getting 'Unable to verify the first certificate' error

**To Reproduce**

1. Go to the helix project directory
2. Run npm install -g @adobe/aem-cli with sudo access and this works
3. Run aem up
4. Then it throws an error - Unable to verify the first certificate

**Expected behavior**
Would have expected aem server to be up on localhost:3000 as mentioned.

**Screenshots**
![image](https://github.com/adobe/helix-cli/assets/145148000/4dea444c-5f8a-4373-a700-b5ac6b3a7c8a)

**Version:**
run: $ hlx --version

**Additional context**
Setting up the local AEM franklin

**Comment by tripodsan** [comment]
- what node version are you using?
- can you run with `aem --log-level=silly up`

**Comment by touseefkhanstewart** [comment]
Hi @tripodsan I am using node v20.11.0 and my OS is Windows 10.

**Comment by touseefkhanstewart** [comment]
I ran this command and getting same error
![image](https://github.com/adobe/helix-cli/assets/145148000/b8333384-7a8d-43c0-86f5-07ed45daac8d)

**Comment by trieloff** [comment]
Hi, you are likely dealing with a corporate firewall that is performing deep package inspection. The way this usually works is that all HTTPS requests get redirected to a proxy server, which will serve its own certificates for the site you are trying to access. Though corporate device management, the correct CA is typically installed in your browser, but not for developer tools.

Most IT orgs are a bit sensitive about this, so I won't ask you to share a screenshot here in public, but if you have access to our support Slack, then we can help you there.
