### ISSUE TITLE
Change default of auto deploy to `no-auto`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#232]
see #229.

### Suggest:
- change default of `--auto` to `false`

**Comment by trieloff** [comment]
Changing the default is just masking the underlying issues outlined in #229: -1

**Comment by tripodsan** [comment]
The problem is, that for initial development, no one wants auto. it's just another hurdle to get across. 

I think the natural evolution of a project is:
1. completely local (`hlx up`)
2. manual deploy (`hlx deploy --no-auto`)
3. fastly integration (`hlx publish`)
4. CI integration (`hlx deploy`)

I think that is more a problem is, that `hlx deploy --auto` does 2 things:
- it creates the actions
- and sets up circle ci

maybe we should separate this; either by using the helix-bot, which sets up the circleci automatically, or with a separate command `hlx enable-autodeploy`. also the strains config should probably define, which branches/strains are managed by the CI.

ps: For the completely managed case, you don't even need `hlx deploy`; you just commit the code and the helix-bot does the rest.

**Comment by trieloff** [comment]
Ok. Let's change it.

**Comment by tripodsan** [comment]
@rofe do you want to take a stab on this?

**Comment by rofe** [comment]
Ack. I can look into this right after the [go-live](https://github.com/adobe/Adobe-Developer-Site).
