### ISSUE TITLE
`AEM_NO_OPEN` not working

### ISSUE THREAD

**Issue by felix-staud** [adobe/helix-cli#2323]
**Description**
When using a `.env` file and adding the variable `AEM_NO_OPEN` it doesn't seem to be recognized.
I tried:

```dot-env
AEM_NO_OPEN=TRUE
```

```dot-env
AEM_NO_OPEN=true
```

```dot-env
AEM_NO_OPEN='TRUE'
```

```dot-env
AEM_NO_OPEN='true'
```

```dot-env
AEM_NO_OPEN="TRUE"
```

```dot-env
AEM_NO_OPEN="true"
```

**To Reproduce**
1. Have an EDS project ready
2. Have the cli ready
3. Create a `.env` file in the root of your repo
4. Add `AEM_NO_OPEN=true` to your `.env` file
5. run `aem up` in your terminal

**Expected behavior**
The browser doesn't open a page automatically

**Version:**
`16.1.5`

**Comment by tripodsan** [comment]
indeed....strange ;-) thanks for reporting.

**Comment by felix-staud** [comment]
@tripodsan I found [this](https://github.com/adobe/helix-cli/blob/d0f0bca2dcdc1228b840de07a54d2cdc9a512319/test/fixtures/all.env#L21)

```
AEM_OPEN=false
```

and this works like a charm.

So either the documentation is off or something else

**Comment by felix-staud** [comment]
@tripodsan thanks for the quick fix 🚀 
Just tested it and works like a charm.

One small detail: There seem to be some `console.log`. Are the still supposed to be there?
<img width="521" alt="image" src="https://github.com/adobe/helix-cli/assets/50131232/0fb046db-41ce-4b62-be92-47eab07ae2ca">

**Comment by tripodsan** [comment]
> One small detail: There seem to be some `console.log` in [src/up.js L 105+](https://github.com/adobe/helix-cli/blob/434760591071b3df17e0962f0eae5c2b82dbe932/src/up.js#L105). Are they supposed to be there?

oops... thanks you for catching !
