### ISSUE TITLE
console log output after commit console output with `aem up` in background

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-cli#2328]
i am usually starting dev `aem up` and attach it to background with `ctrl-z` & `bg` or start with `aem up &`... then i am using the `git` cli to `commit` changes and `push`.

after a `commit` there is some log output on the console... looks something like this, that is somewhat messing up my typing as it is usually a little bit delayed...

```
uncled@Davids-MacBook-Pro-4 thinktanked % git commit -m "chore: better checkbox handling"
[rum-slicer 6e88cd7] chore: better checkbox handling
 1 file changed, 1 insertion(+), 1 deletion(-)
uncled@Davids-MacBook-Pro-4 thinktanked % git HEAD or remotes changed, reconfiguring server...
git puUpdated proxy to https://rum-slicer--thinktanked--davidnuescheler.hlx.page
sh origin
```

as you can see i already started to type `git push origin` and that got mixed in the `git HEAD or remotes changed ...` message.

i appreciate that this can happen with the above setup, it is just normally not super intrusive, but in this case it kind of gets me every time...

the simple solution would be to lower the log level on that specific message, but i am not sure if that's desired and i should just change how do things...

**Comment by davidnuescheler** [comment]
i actually think that the message is not needed altogether... i think if you checkout a new branch the proxy origin has to change but, i don't think this needs to happen with a commit. so maybe we can suppress this message if the origin actually hasn't changed.

**Comment by tripodsan** [comment]
...or you just press `⌘K` to reset your terminal an continue with the current line  :-)
