### ISSUE TITLE
[import] news.adobe.com (Cloudflare) 403 due to http 1.1 fetch

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#2332]
To produce the issue:

- Run `aem import`
- in Chrome, open http://localhost:3001/news/news-details/2022/Adobe-Reports-Record-Revenue-in-Q1-Fiscal-2022/default.aspx?host=https%3A%2F%2Fnews.adobe.com

This leads to a 403 response from Cloudflare.

Workaround: 
- in Chrome, change the `User-Agent` header to `Thunder Client (https://www.thunderclient.com)` (use for example a Chrome extension https://chromewebstore.google.com/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj?pli=1)
- requesting the page now works.

Cloudflare seems to associate the Chrome user agent to h2, other user agents are fine with http 1.1. 
@catalan-adobe managed to prove that use an h2 fetch in the importer proxy fixes the issue (https://github.com/adobe/helix-cli/blob/main/src/server/HelixImportServer.js#L104).

@tripodsan: the question now is why do we use `keepAlive` (see https://github.com/adobe/helix-cli/blob/main/src/fetch-utils.js#L52-L56) which forces http 1.1 (see https://github.com/adobe/fetch?tab=readme-ov-file#http11-keep-alive) ? Any specific reason ? I cannot remember but assuming the proxy is supposed to work with potentially "old" infrastructure, it might be a better choice. Just bad luck with Cloudflare validation in this specific case.

**Comment by catalan-adobe** [comment]
I could also confirm that `noCache` (instead of `keepAlive`) also works!

**Comment by tripodsan** [comment]
I can't imagine that clourflare would reject http1.1 based on the user-agent. that would be a major breaking change.
@stefan-guggisberg WDYT?

**Comment by kptdobe** [comment]
```
curl -v -o /dev/null \
  -A 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'accept-encoding: gzip, deflate, br, zstd' \
  https://news.adobe.com/news/news-details/2022/Adobe-Reports-Record-Revenue-in-Q1-Fiscal-2022/default.aspx
```
gives a 200. Default use h2...

```
curl -v -o /dev/null \
  -A 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'accept-encoding: gzip, deflate, br, zstd' \
  --http1.1 \
  https://news.adobe.com/news/news-details/2022/Adobe-Reports-Record-Revenue-in-Q1-Fiscal-2022/default.aspx
```
gives a 403!

**Comment by kptdobe** [comment]
ok, might be another header combo because 
```
curl --http1.1 -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" -v https://news.adobe.com/news/news-details/2022/Adobe-Reports-Record-Revenue-in-Q1-Fiscal-2022/default.aspx
```
gives a 200... so weird.

**Comment by stefan-guggisberg** [comment]
Who setup https://news.adobe.com/? It's not Franklin related, right? We should ask them why they block these HTTP/1.1 requests. I could imagine that they have enabled a WAF.

**Comment by kptdobe** [comment]
Correct, it is not Franklin related yet. We are trying to import the site from this host and convert it. It is the importer code which fails, we are just trying to understand why. Not a big deal, we have a workaround, just questioning why we are not able to fetch with h2.

**Comment by tripodsan** [comment]
> Not a big deal, we have a workaround,

Suggest to allow the user to specify the user-agent

**Comment by kptdobe** [comment]
> Suggest to allow the user to specify the user-agent

That's in the issue description. Using a Chrome extension to change the user-agent header (like https://chromewebstore.google.com/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj?pli=1) is the proposed workaround for now... If this is the only site we try to import with this problem, no need for an extra config.

Getting rid of Chrome user agent feels really silly, I still wanted to understand the why we do not use an h2 fetch. But again, no worries, we can even close this issue.

**Comment by kptdobe** [comment]
Closing for now as there is a workaround. Will re-open (and address) if importing from Cloudflare becomes a more regular issue.
