### ISSUE TITLE
Support 301/302 redirects 

### ISSUE THREAD

**Issue by freshjones** [adobe/helix-cli#2336]
See this video https://www.loom.com/share/331518c274464444b9c15864cc52a147

would be great if cli supported 301/302 redirects

utils.js

```js
if (ret.status === 301 || ret.status === 302) {
      const location = new URL(ret.headers.get('location'));
      location.hostname = 'localhost';
      location.port = ctx.config.server.port;
      location.protocol = req.protocol;
      respHeaders['location'] = location.toString();
      res
        .status(ret.status)
        .set(respHeaders);
    }
```

**Comment by tripodsan** [comment]
thanks @freshjones for the report. from the video, it is not obvious what the value of the `location` header is. of course, we should only rewrite redirects if the `location` points to the same origin.

alternatively, the system that generates the redirects for your icons (either the cloudflare worker or the redirects.xlsx) should use relative paths. then local dev should work ootb.

**Comment by freshjones** [comment]
@tripodsan  ah good shout! lemm see if I can adjust the location on the worker to root relative and see if that works. thanks!
