### ISSUE TITLE
Could add a Options named '--allowUnauthorized ' in command?

### ISSUE THREAD

**Issue by zhangqx1994** [adobe/helix-cli#2351]
I used net environment   in company and i found a problem like this:
![image](https://github.com/adobe/helix-cli/assets/18023108/866f1b79-6b3f-4e66-9cef-f0ce29fd652a)

From the log-level silly , i couldn't to solve this issue with the simple log. XD (Obviously, its about http auth)
And i try to find the reason with the **hlx-cli** source code.
Finally , i found this function named _getFetch()_
![image](https://github.com/adobe/helix-cli/assets/18023108/5077aac4-9676-4d07-820a-c7a381d17158)

In my environment   , i need to make the 'allowUnauthorized' parameters  not null.
But I didn't find other way to achieve it besides modify the source code and run it in local .

So i think shall we add a option to control this param easily?

**Comment by helms-charity** [comment]
I want to upvote this -- My customer is blocked with the same problem.

**Comment by dominique-pfister** [comment]
There is now an option `--allow-insecure` to achieve this.

**Comment by helms-charity** [comment]
actually it seems to be --allowInsecure
