### ISSUE TITLE
Reverse proxy has the branch hardcoded to main

### ISSUE THREAD

**Issue by clementepereyra** [adobe/helix-cli#2362]
**Description**
The client always uses the main branch for the reverse proxy. Even though locally we are working on a separate branch, there's a hardcoded value to use main always. I've seen this has been added [here](https://github.com/adobe/helix-cli/pull/2333/files#diff-35760cd786da2cd387bcec424a0c4ff61fec53d1cadcd75945cd58da8d8c1840R135) as part of a fix. But I think that's preventing working with any other branch but main while working on local development.

**To Reproduce**
1. Install the client.
2. Clone a repository based on the AEM boilerplate template.
3. Create a new branch, push it and check it out.
4. Run `aem up`.
5. See that even though you are on a different branch, the client still works with main branch

**Expected behavior**
The client should create the reverse proxy based on the git branch currently in use.

**Screenshots**
<img width="444" alt="image" src="https://github.com/adobe/helix-cli/assets/31851655/4541cbc0-db17-402d-b0c1-0701fcd376e5">

<img width="715" alt="image" src="https://github.com/adobe/helix-cli/assets/31851655/7429e45b-6c81-4130-8945-0069dcdbe008">

**Version:**
16.3.16

**Comment by tripodsan** [comment]
yes. this was changed in https://github.com/adobe/helix-cli/pull/2333

if you want to open a specific branch, use the `--url` argument or the `AEM_URL`  env var.

**Comment by clementepereyra** [comment]
Thanks for the response @tripodsan. That's exactly right, it was introduced in there. So, are you saying this was intentional and the idea is to limit the client to only pull from _main_? Meaning, this is not a defect but a desired feature?
