### ISSUE TITLE
`aem up` should support variables in `.env` file

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#2411]
The customer would like to use a generic `.env` file which makes sure that `aem up` always proxies their custom preview origin, but without having to specify a dedicated value for `HLX_URL` in every repository they have.

e.g.
```
AEM_URL=https://main--${site}--${org}.aem.page
```
where `org` and `site` are automatically replaced.

**Comment by tripodsan** [comment]
`site` and `org` are not really the correct variables when dealing with code repos. I think we should only support `owner` and `repo` (and `ref`)

**Comment by rofe** [comment]
I think it should be `AEM_*` in the `aem` CLI...

**Comment by rofe** [comment]
`${...}` seems like a bad idea, because it might get auto-replaced with an empty or unexpected variable at the shell level. Something like `{{...}}` might be safer.

**Comment by rofe** [comment]
@tripodsan on second thought, I don't think we should support `ref` as a variable to be replaced with the branch from the local checkout. I think the ref doesn't matter for local development because the code in the proxy will be coming from the disk anyway, and using the local branch could lead to unexpected 404s on `aem up` if it doesn't exist on github.com yet.
