### ISSUE TITLE
[hlx deploy] should not modify strains.yaml

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#242]
**Is your feature request related to a problem? Please describe.**
Add `.hlx/strains.yaml` to git and commit it.
Make a change in your code and commit it.
Run `hlx deploy`. (changes your `.hlx/strains.yaml`)
Run `hlx deploy`:-> `hlx will not deploy a working copy that has uncommitted changes. Re-run with flag --dirty to force.``

3 options:
1. Run `hlx deploy --dirty` which forces you to change all your strain configs first (assuming you want all of them to you the latest code) to "dirty" code action  -> not desired
2. Revert the changes made by the first `hlx deploy` to the `strains.yaml` -> annoying 
3. Commit the changes made by the first `hlx deploy` to the `strains.yaml` -> unnecessary polluting extra strain

**Describe the solution you'd like**
`hlx deploy` should only add a strain if there is none in the file.

**Comment by tripodsan** [comment]
option 4.: let's finally move the strains into the `helix-config.yaml` again. (and of course not modify it during publish)

**Comment by tripodsan** [comment]
fixed with #271
