### ISSUE TITLE
[hlx up] Requesting / fires an error

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#245]
**Description**
Request to `/` (root) does not redirect to /index.html

**To Reproduce**
1. `hlx up`
2. Open http://localhost:3000/
3. See error: 

```
[hlx] error: Error while delivering resource / - Error: resource at https://raw.github.com/adobe/project-helix.io/master/ does not exist. got 400 from server
    at Object.fetch (../project-helix/modules/petridish/src/utils.js:59:13)
    at <anonymous>
```

**Expected behavior**
~~Requests to / should be redirected to /index.html then to /README.html if no index.~~
The behavior should be the same than in production: URL must stay http://localhost:3000/ but render index.html (or README.html if no index).

**Version:**
run: `$ hlx --version`
0.7.13-pre.8

**Comment by tripodsan** [comment]
I would keep this issue, and add respective support for directory index handing in petridish,

**Comment by tripodsan** [comment]
no longer an issue
