### ISSUE TITLE
Add a "X-Version" header that exposes the Fastly configuration version

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#247]
**Is your feature request related to a problem? Please describe.**
After a `hlx strain`, the cache is purged and the first hit is sometimes really slow but sometimes it is surprisingly fast: this gives a lot of doubts and uncertainty knowing if the request was made before the purge fully happened and if the content has really been updated. The fact is that I often do not know if my change has been taken into account thus I need to `hlx strain` again.

**Describe the solution you'd like**
My proposal is to add a X-Version header that contains the Fastly version number. It could be "injected" somehow during the `hlx strain` process. Like this, I am sure which version generated the html delivered.

cc @trieloff @tripodsan

**Comment by kptdobe** [comment]
I takes sometimes multiple `build / deploy / strain` to get the latest change (htl in my current case) on the "publish" website. There is nothing wrong somewhere and hopefully, being able to determine which VCL version + action "version" would be necessary.

**Comment by kptdobe** [comment]
Arff.. the pb in the current case is that I want to check before committing, thus I added `--dirty` which changes the action name thus I should have updated my strains... something else to improve...

**Comment by kptdobe** [comment]
The main issue: this cannot live only in Fastly because activating a new version is independent from purging the cache. You can cache A.html with v12, activate v13, do not purge the cache, the current active version is not the one that "created" A.html.

**Comment by trieloff** [comment]
`hlx publish` runs a complete purge at the end, so you are unlikely to experience the issue you've outlined.

**Comment by kptdobe** [comment]
Implemented with https://github.com/adobe/helix-cli/commit/00e01d2f9f514b04aa7d659be7e4077718a19222

**Comment by tripodsan** [comment]
I disagree:
- using the VCL version retrieved during hlx publish, is not accurate, if someone modifies the VLC afterwards via API or UI. if we only set it in hlx publish, we might provide a wrong number, which will be even more confusing. if it doesn't match the one that is active on fastly.

please reconsider to set the VLC version using the `req.vcl` variable, as proposed by fastly support.

/cc @trieloff

**Comment by kptdobe** [comment]
You cannot modify the VCL of an active version, you need to clone it which will create a new version number, in which case, the version will be wrong, I agree. 
Actually, we could have both, this will tell us immediately if someone did not use `hlx publish` to generate the config! Even better.

**Comment by tripodsan** [comment]
we should better use http header semantics instead of `|`. see my comment in the PR: https://github.com/adobe/helix-cli/pull/265/files#r225015280
