### ISSUE TITLE
Implement `--log-level`

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#248]
When running `hlx up`, the pipeline and my `pre.js` can output plenty of `debug` logs. How do I set the log level to `debug` ? (default to `info`)

cc @trieloff @tripodsan

**Comment by trieloff** [comment]
We don't have a parameter like `--log-level` yet.

**Comment by tripodsan** [comment]
fixed with #281

**Comment by tripodsan** [comment]
not completely...
