### ISSUE TITLE
Reconsider adding X-Version as a debugging feature

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#264]
With https://github.com/adobe/helix-cli/issues/247, we introduced a `X-Version` header which has been made available for all the requests. While this is useful for debugging, it exposes some "internal" info like the hlx cli version being used to publish and the last code commit sha.

Goal of this issue is to track the fact we might need the header in the early stage of the first productive sites but we'll must hide the header and make it a `X-Debug` feature at one point.

**Comment by tripodsan** [comment]
I think that all headers visible with `X-Debug` reveal information better not disclosed:

```
< x-openwhisk-activation-id: db66aa98b72a43a6a6aa98b72a83a60d
< x-request-id: u3lhwlA2m5kvlkpsXoq3hmztDJE6ooeu
< x-backend-name: 3t7g8apsfQlFyvuHIQn9e8--F_AdobeRuntime
< x-cdn-request-id: a3f506c3-0015-45d6-be98-a561a7204388
< x-backend-url: /api/v1/web/acapt/default/https---github-com-adobe-project-helix-io-git--master--html?owner=adobe&repo=project-helix.io&ref=master&path=/index.md&selector=&extension=&branch=master&strain=default&GITHUB_KEY=(null)
< x-branch: master
< x-strain: default
< x-github-static-ref: @(null)
< x-index: default
< x-action-root: /acapt/default/https---github-com-adobe-project-helix-io-git--master--
< x-url: /
< x-root-path:
< x-version: 74
```

### Suggest

- provide a way to publish in _production mode_ which will disable the `X-Debug` completely in the VCL.

**Comment by trieloff** [comment]
My idea was to have a secret debug key, so that you have to set the `X-Debug` header to a random value that is generated during deployment time.

**Comment by tripodsan** [comment]
> have a secret debug key,
but should be visible in the VLC, not in an edge directory. so that you can look it up.
or we could store it in a well known dictionary and then fetch it via https://docs.fastly.com/api/config#dictionary_item_a48de28cd7e76c1ea58523f39bb7204b.
this could be added to hlx as:
```
hlx publish --debug-key
-H "X-Debug: fasdsadfasd4345234543"
```

**Comment by trieloff** [comment]
> but should be visible in the VLC, not in an edge directory. so that you can look it up.

Agree. Storing it in a dictionary is just an extra step that we don't need to take.

I'd always print the debug key, but allow setting it with `--debug-key=hunter2`
