### ISSUE TITLE
Discuss: Consider monorepo for helix-cli and petridish

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#268]
**Is your feature request related to a problem? Please describe.**
helix-cli depends on petridish; petridish is not usable w/o helix-cli. having them in separate repos is cumbersome, as many issues are cross package. 

adding new common dependencies is also cumbersome, as we would need to setup yet another repo. thus hindering good modularization. 

**Describe the solution you'd like**
Suggest to turn `helix-cli` into a monorepo, with the following packages:
- helix-cli
- helix-server (formerly known as petridish)
- (helix-config)
- ...

I think that using [lerna](https://github.com/lerna/lerna) will help us with managing the packages effectively (@kptdobe , you'll like: [lerna link](https://github.com/lerna/lerna/tree/master/commands/link#readme))

**Stretch goal**
Eventually, we might then also rename the `helix-cli` repository to `helix`

**Describe alternatives you've considered**
The alternative is to keep using separate repositories.

**Comment by trieloff** [comment]
+1 to moving it into a single repository.

I'm indifferent to having separate packages in the same repository, given that it is unlikely to ever import `helix-server` without `helix-cli`.

**Comment by kptdobe** [comment]
+1

**Comment by tripodsan** [comment]
@stefan-guggisberg @dominique-pfister any objections?

**Comment by dominique-pfister** [comment]
Nope, here’s my +1

**Comment by stefan-guggisberg** [comment]
+1

**Comment by tripodsan** [comment]
update. after playing around with a real project, like helix-cli, I think (2) is mandatory for better test isolation and coverage.
