### ISSUE TITLE
ESI on / are not executed on production

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#269]
**Description**
An ESI include in the `index.html` will not be executed and `esi:include` tag will be rendered.

**To Reproduce**
See https://github.com/adobe/project-helix.io/issues/19
Basically: 
- add an ESI include to your htl template for index.html
- request /index.html -> ESI include executed, HTML rendered
- request / -> ESI include NOT executed, ESI tag rendered

**Version:**
run: `$ hlx --version`
0.8.1-pre.8

**Comment by trieloff** [comment]
this is the offending code:

```vcl
  # making sure to get an uncompressed object for ESI
  if ( req.url.ext == "html" ) {
   unset bereq.http.Accept-Encoding;
  }
```

ESI only works for non-gzipped responses. 

A simple solution would be to unset it when the extension is `"html"` or `""`, but I wonder if it wouldn't be better to fix this in the pipeline, e.g. when the response body contains `<esi` to set the `Accept-Encoding` to `null`.
