### ISSUE TITLE
add build artefacts to .gitignore

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#274]
**Description**
`hlx up` and `hlx build` create a `dist` folder which should be added to the `.gitignore` file

**To Reproduce**
1. `hlx demo demo`
2. `cd demo`
3. `hlx build`
4. `git st` reports `dist/` as `Untracked files`

**Expected behavior**
All artefacts generated by `hlx up` and `hlx build` should be covered by the patterns in `.gitignore`

**Version:**
`0.8.0`

**Comment by stefan-guggisberg** [comment]
fixed in 6149009f81b650078d425c125488de6d5207a7e5

**Comment by trieloff** [comment]
@tripodsan don't we expect the `dist` folder to get checked in?

**Comment by stefan-guggisberg** [comment]
oops, didn’t know. i’ll revert if that’s the case.

**Comment by tripodsan** [comment]
yes. the `dist` folder is meant to be comitted to the repository. it is used for delivering the static files.
