### ISSUE TITLE
Conditionally enable ESI

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#275]
As discussed in #269, the ESI logic at the moment is a bit brute-force/dumb:

- if the request is served through the standard (non-static) pipeline, try to ESI (at least since #270)

This comes with a number of unwanted side-effects:

- we have to disable Gzip for all dynamic requests, as ESI is incompatible with Gzip
- Fastly has to scan every response for `<esi` tags, which adds a small performance overhead on every request

I suggest we get smarter about ESI by enabling ESI/disabling Gzip only when the origin tells us in a `beresp.http.X-ESI` header that there is something to include. We adjust pipeline to do that when there is an `<esi` tag in the response body.

**Comment by ejthurgo** [comment]
It seems like a pretty sensible way to avoid the extra overhead when you don't need ESI.
