### ISSUE TITLE
Unable to initialize project if git commit hooks blocks commit

### ISSUE THREAD

**Issue by gknobloch** [adobe/helix-cli#280]
**Description**
If your git configuration has a pre-commit hook rejecting the commit message, the client won't be able to initialize the repository.

**To Reproduce**
1. Download helix installer
2. Run `hlx demo test`
3. See error

```
$ hlx demo test3
creating test                                    [ok]
creating test/index.md                           [ok]
creating test/_gitignore                         [ok]
creating test/helix_logo.png                     [ok]
creating test/.vscode/settings.json              [ok]
creating test/.circleci/config.yml               [ok]
creating test/src/favicon.ico                    [ok]
creating test/.vscode/launch.json                [ok]
creating test/src/html.htl                       [ok]
creating test/src/html.pre.js                    [ok]
creating test/src/style.css                      [ok]
Repository Violation: Commit message does not contain a valid issue number.
Unable to initialize git repository: Repository Violation: Commit message does not contain a valid issue number.
```

**Expected behavior**
Project initializes and server can be started.
Works if I disable my Git commit hook validating format of my commit message.
Maybe the commits should be done ignoring commit hooks using `git commit --no-verify`.
- https://github.com/adobe/helix-cli/blob/v0.8.0/src/demo.cmd.js#L78

**Version:**
`0.8.1-pre.10`

**Comment by stefan-guggisberg** [comment]
fixed in 4049f5b

**Comment by tripodsan** [comment]
Thanks for the fix, @stefan-guggisberg.
please also add tests.

**Comment by stefan-guggisberg** [comment]
added test in eb20083d673ac9b765c04f06c219b7a450d7191f

**Comment by tripodsan** [comment]
sänks!
