### ISSUE TITLE
CI or not CI ?

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#285]
When running `hlx demo myproject`, you get a `.circleci/config.yml` that is ready to be used on CircleCI and runs various things for you. It mainly:

* checks out your project code
* install the last helix-cli
* runs `hlx build`
* runs `hlx deploy`
* runs `hlx publish` which will push your lastest commit to Fastly, whatever it is
* runs `hlx perf`

This is great to automate: if a commit comes into your master branch, code will be automatically pushed to Fastly and you code will be live with no effort..

As @trieloff described somewhere else, if the CI runs on a branch commit, `hlx deploy`  will create a new strain for that branch. The subsequent `hlx publish` will publish that new strain, but keep the old strains (pointing to the old code definitely, and the old content depending on configuration) in place.

While this is true there are several critical issues appearing here:

1. `hlx publish` will increment the Fastly config (including the VCL files) using the last helix-cli. If we release a new heli-cli in between 2 commits from a branch, the CI will push a potentially new and non-backward compatible Fastly setup.
2. `hlx publish` runs a full cache purge on Fastly, which means that all the "live websites" will lose their cache and each page will take a loooooong time to reconstruct.

While I think we are aware of 2., I do not think we ever considered 1. Or maybe this is what the bot is supposed to address but in that case, what is the point of having this CI ?

cc @tripodsan @trieloff

**Comment by tripodsan** [comment]
frankly, I don't think that helix-cli should manage the CI. either everything is automated by the bot for managed projects, or the developer knows what he is doing and can setup the CI himself.

> As @trieloff described somewhere else, if the CI runs on a branch commit, hlx deploy will create a new strain for that branch. The subsequent hlx publish will publish that new strain, but keep the old strains (pointing to the old code definitely, and the old content depending on configuration) in place.

I don't understand how this would work? I think that: new branch -> new strain -> new domain -> new service -> new vlc.

**Comment by kptdobe** [comment]
Another issue I just found: 

3. with you branch checked out, run `hlx deploy`

This tells you:

```
Automating deployment with https://circleci.com/api/v1.1/project/github/adobe/project-helix.io/follow

Auto-deployment already set up. Triggering a new build.
Go to https://circleci.com/gh/adobe/project-helix.io/42 for build status.
```

which is great. But the deployment is executed on... master!

**Comment by trieloff** [comment]
> `hlx publish` runs a full cache purge on Fastly, which means that all the "live websites" will lose their cache and each page will take a loooooong time to reconstruct.

Yep, aware of it. And `hlx perf` is in a way a means to re-warm the cache after a publish.

**Comment by trieloff** [comment]
> `hlx publish` will increment the Fastly config (including the VCL files) using the last helix-cli. If we release a new heli-cli in between 2 commits from a branch, the CI will push a potentially new and non-backward compatible Fastly setup.

We might be able to prevent this by staying with the helix-cli minor version that is pinned in the `package.json`.

**Comment by trieloff** [comment]
> As @trieloff described somewhere else, if the CI runs on a branch commit, hlx deploy will create a new strain for that branch. The subsequent hlx publish will publish that new strain, but keep the old strains (pointing to the old code definitely, and the old content depending on configuration) in place.
> I don't understand how this would work? I think that: new branch -> new strain -> new domain -> new service -> new vlc.

`hlx deploy` creates a new strain (with a hashed name) and no conditions attached, so that you can test it (by using the `X-Strain` header or cookie), but it won't ever see live traffic unless you attach a condition to it.

So: new branch -> new strain: yes
new strain -> new domain: no – in fact no changes to the URL at all
new domain -> new service: unrelated, but also no: a given service can have any number of domains., it's just that a given domain can be attached to only one service
new service -> new VCL: yes.

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
