### ISSUE TITLE
hlx deploy triggers CI build on wrong branch

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#286]
3. with you branch checked out, run `hlx deploy`

This tells you:

```
Automating deployment with https://circleci.com/api/v1.1/project/github/adobe/project-helix.io/follow

Auto-deployment already set up. Triggering a new build.
Go to https://circleci.com/gh/adobe/project-helix.io/42 for build status.
```

which is great. But the deployment is executed on... master!

_Originally posted by @kptdobe in https://github.com/adobe/helix-cli/issues/285#issuecomment-431307616_

**Comment by trieloff** [comment]
Obvious bug, with an obvious fix.

**Comment by kptdobe** [comment]
Needs to be verified. Might be fixed.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
