### ISSUE TITLE
[Smoke Tests] Create CI to run tests against master code of all dependencies

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#289]
In order to start tracking breaking changes, we need to introduce a CI config that runs the helix-cli tests against the master code of all dependencies (hypermedia-pipeline, git-server...). Ideally the CI runs each time there is a commit in the master branch of one of our repo. 
This will help identifying early if we introduce a breaking change:
- either an uncovered issue that would appear in a later release
- or a valid breaking change that needs to somehow be applied somewhere else (like in `hlx demo` generated code or at the project level)

**Comment by tripodsan** [comment]
in circleci, can we somehow link a downstream projects workflow to a helix-cli workflow? and then pass a parameter to which dependency to replace?

**Comment by kptdobe** [comment]
> in circleci, can we somehow link a downstream projects workflow to a helix-cli workflow? and then pass a parameter to which dependency to replace?

That's what I would do too. We need to investigate if this is possible.

**Comment by trieloff** [comment]
Triggering a build from the API is possible: https://circleci.com/docs/2.0/api-job-trigger/#conditionally-running-jobs-with-the-api

Passing a parameter (especially, which PR to use) seems to be harder.

**Comment by trieloff** [comment]
Nevermind: https://circleci.com/docs/api/#trigger-a-new-job

> `build_parameters`: Additional environment variables to inject into the build environment. A map of names to values.

**Comment by kptdobe** [comment]
I created our first smoke test here: https://github.com/adobe/project-helix.io/blob/master/test/smoke/test.hlx.up.js
Probably not the most brilliant test but it took me a while to make sure it does the minimum (and passes...)
Now I need to make sure it is executed each time you create a PR in any of our repo and test the PR together with latest code from everything.

**Comment by trieloff** [comment]
See also https://github.com/adobe/helix-cli/issues/311

**Comment by kptdobe** [comment]
Well... Orbs will help on making things reusable and easier to read but will not do the actual job of testing!

**Comment by kptdobe** [comment]
Branch `alex-test` in `adobe/petridish` has now the CI configured to call the smoke tests: https://github.com/adobe/helix-simulator/blob/alex-test/.circleci/config.yml#L53-L60

Last step required:
- "wait" for the smoke tests to complete and display results in the "calling" PR
- productise and document the whole setup (there are pieces everywhere)

**Comment by kptdobe** [comment]
Waiting seems to be doable with a script: see https://github.com/circleci/frontend/blob/master/script/wait-for-deploy.sh

**Comment by kptdobe** [comment]
The smoke tests are almost ready.

You can see an execution exemple here: https://circleci.com/gh/adobe/helix-simulator/493

This was triggered by a PR (https://github.com/adobe/helix-simulator/pull/91), executed the helix-simulator build which now contains a smoke_tests command (https://github.com/adobe/helix-simulator/blob/alex-test/.circleci/config.yml#L30-L95). 
In this specific case, the job running the smoke tests fails but this is due to a bug in CircleCI: the API call does not trigger a job properly if the job is in v2.1. I opened a ticket for that on the CircleCI (url to share when I know where it is...)
Here is an example (before v2.1 migration and output cleanup) of failing smoke tests (for valid reason) - error message is fetched and displayed in the PR related job: https://circleci.com/gh/adobe/helix-simulator/477

Remaining todo:
- cleanup
- document overall architecture / create video recording with explanation
- document and write tests for GDM
- wait for CircleCI to fix bug (otherwise we'll have to go back to v2.0 in helix-cli)

**Comment by kptdobe** [comment]
Debating with CircleCI on why this is a regression and not a potential new feature they might need to build. They finally pointed me to: https://circleci.com/ideas/?idea=CCI-I-690 and cannot provide an ETA when / even.. if this is done.

I am trying now using v2.1 new build trigger (full workflows) instead of job trigger

**Comment by kptdobe** [comment]
To workaround the migration issue and as @tripodsan suggested, I am going to create a new repo that will host everything ci/cd related. At the beginning, it will just contain a config for the smoke tests (which will be v2.0 thus no issue - upgrade when CircleCI will have fixed the issue) and the CI scripts needed. Quickly after, it may contain the first helix orb...

Repo name proposal: `helix-continuous` (`helix-ci` is too close to `helix-cli`).

@trieloff @tripodsan @rofe @stefan-guggisberg WDYT ?

**Comment by trieloff** [comment]
`helix-build`?

**Comment by tripodsan** [comment]
`helix-smoke-and-mirrors` ?

**Comment by kptdobe** [comment]
`helix-build` is misleading, I would expect to build Helix from here while helix-cli should still be the entry point. This repo would more be the "puppet-master".
`helix-smoke-and-mirrors` is maybe to honest and gives too many hints 😂

**Comment by kptdobe** [comment]
ok, smoke tests are running in the new repo (failing if all master). See https://circleci.com/gh/adobe/helix-continuous/6

Next (hopefully final) step: create an orb to be used in all our projects to trigger the smoke tests on commit.

**Comment by kptdobe** [comment]
The smoke tests are now ready to be integrated:
- https://github.com/adobe/helix-continuous contains the smoke tests, the CircleCI orb and everything needed to run the tests.
- per project PR to integrate the smoke tests:
  - https://github.com/adobe/helix-cli/pull/307
  - https://github.com/adobe/helix-simulator/pull/91
  - https://github.com/adobe/hypermedia-pipeline/pull/119

I suggest to start with those 3 repos for now, see how it works and then propagate to other repos

**Comment by kptdobe** [comment]
Created https://github.com/adobe/project-helix/issues/347 to follow up on the configs and integration of the tests in the other repos.
