### ISSUE TITLE
[hlx init] Add CSS file 

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#29]
`hlx init` should also add a css file and maybe a `fav.ico` so that users see how static files are delivered.

### suggest

```
dist/fav.ico
dist/main.css
```

**Comment by kptdobe** [comment]
+1
This will require https://github.com/adobe/petridish/issues/19 for testing

**Comment by trieloff** [comment]
I'm not sure about `dist`. It seems the standard is to use `dist` as an output directory and we will relatively soon have some packaging built in. So this is something that might change in the future.

**Comment by kptdobe** [comment]
I agree for the `dist` folder. This is all related to https://github.com/adobe/project-helix/issues/101

**Comment by tripodsan** [comment]
what about:

- `./src/static/*`

in general:

```
./src/mycomponent/
   html.htl
   static/
      main.css
```

**Comment by trieloff** [comment]
I like `static`.

We have to see what introducing subfolders for components will do for compiled file names and resulting action names, though.

**Comment by tripodsan** [comment]
see #49
