### ISSUE TITLE
Remove embedded resource processing (again)

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#295]
as discussed with @davidnuescheler the static file processing by parcel has several flaws:
- referencing the source files from within the htl is counter intuitiv (although referencing them via absolute path, will cause the IDE to complain)
- parcel doesn't support all possible meta tags/refs and we don't want to be responsible to support them
- parcel modifies the HTML, e.g. closes tags etc.

### Suggestion by @davidnuescheler
- remove resource processing from the parcel plugin again
- user needs to copy copy the static files manually to the webroot

**Comment by tripodsan** [comment]
@trieloff  @kptdobe WDYT? the goal is to remove some magic again.

**Comment by trieloff** [comment]
Is this about pre-processing the HTL?

**Comment by tripodsan** [comment]
> I would never do that. I would put them directly in the webroot!

that's what I mean :-) 

> Is this about pre-processing the HTL?

yes. both @davidnuescheler  and @kptdobe struggle very much with the treatment of parcel, which often modify the html, don't process all files, etc. I think that we should strive to a what-you-see-is-what-you-get and no-surprises approach ;-)
