### ISSUE TITLE
Helix Guide

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#30]
I read about cheat.sh on the break today and thought we could build something similar.

‘hlx guide’ should show a step by step tutorial that helps you to get up and running. If you haven’t run ‘hlx init’ yet, it will be the default command.

**Comment by kptdobe** [comment]
Or have each command telling you what would be the next logical step. The `hlx --help` would simply tell you to start with `hlx init`.

**Comment by trieloff** [comment]
I don't want to break expectations for `--help` to much. What most people expect when calling `--help` is a terse synopsis of the available command line arguments. With `guide` I've been thinking more about a guided tutorial.
