### ISSUE TITLE
Automatically create new release w/ binary hlx installer attached on new version tag

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#306]
**Is your feature request related to a problem? Please describe.**
The binary `hlx` installer script (`hlx_install.sh`) currently needs to be manually built and added to every new release. 

**Describe the solution you'd like**
On a new version tag (e.g. `v0.1.2`) a new release should be automatically created with the corresponding binary `hlx_install.sh` attached.

**Comment by trieloff** [comment]
We might also want to try https://www.npmjs.com/package/semantic-release to automatically generate change logs from our commit messages.

**Comment by stefan-guggisberg** [comment]
implemented in 7beb67cb41aab295a1a844eaaf57a048d35f70e0

creating a version tag of format `v9.9.9` will trigger creation of a new release with `hlx_install.sh` attached.
