### ISSUE TITLE
Explore CircleCI Orbs

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#311]
## Overview

CircleCI has introduced a new feature, Orbs (https://circleci.com/orbs/) that allows the creation of re-usable commands, executors and jobs that might allow us to simplify the default CI configuration and achieve greater standardization.

We might also use this for things like #307, so that we can preview in simulator and pipeline, if a merged PR would break the downstream build.

**Comment by kptdobe** [comment]
Big +1. 
Whatever can be done to simplify the circleci config and reuse stuff (instead of copy/pasting everywhere) must be explored...

**Comment by tripodsan** [comment]
also see https://github.com/adobe-rnd/new-nodejs-repository-template/blob/master/.circleci/config.yml

where I already use commands and executors. would be nice to turn them into orbs.
we might maintain the orbs in https://github.com/adobe/helix-shared ?

**Comment by kptdobe** [comment]
I created a first orb that could serve as an example - see here: https://github.com/adobe/helix-continuous/tree/master/.circleci/orbs

As @tripodsan, we can use an orb for the commands and executors we already have. This is tracked now here (cross multiple project): https://github.com/adobe/project-helix/issues/347
