### ISSUE TITLE
Debugging broken in v0.9.0

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#313]
**Description**
As of v0.9.0 setting breakpoints in `html.htl` and `html.pre.js` is not possible anymore. 

**To Reproduce**
Follow instructions [here](https://github.com/adobe/project-helix/blob/master/start-developing-your-first-helix-project-in-60-seconds.md). Steps 7 and 8 don't work anymore.

**Expected behavior**
Above instructions should work.

**Version:**
0.9.0

**Additional context**
Seems like source mapping of generated `html.js` to the projects `html.htl` and `html.pre.js` is broken.

**Comment by tripodsan** [comment]
I'll have a look.
