### ISSUE TITLE
[Regression][hlx up]  title, intro, image properties of the payload are either undefined or wrong

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#319]
**To Reproduce**
1. `hlx test`
2. `cd test`
3. `hlx up`

Inspect the payload:

```
  title: 'helix-logo',
  intro: 'helix-logo',
  image: undefined,
```

Based on the md, I expect it to be:

```
  title: 'Helix - test',
  intro: 'It works! test is up and running.',
  image: './helix_logo.png',
```

4. Remove the `![helix-logo](./helix_logo.png)` line from `index.md`
5. Reload the page

Inspect the payload:

```
  title: undefined,
  intro: undefined,
  image: undefined,
```

I expect it to be:

```
  title: 'Helix - test',
  intro: 'It works! test is up and running.',
  image: undefined,
```

**Version:**
run: `$ hlx --version`
v0.9.0

cc @trieloff

**Comment by trieloff** [comment]
@kptdobe looks like it is partly a pipeline issue (which has been fixed in 27c5711) and partially a definition issue:

`helix-logo` is the `alt` text of the image, which makes up the first paragraph. We could ignore images, or decide that their alt text is part of the intro. WDYT @kptdobe?

Don't have a test for the second scenario yet.

**Comment by trieloff** [comment]
https://github.com/adobe/hypermedia-pipeline/commit/52ea9d98189a0d306bc636aec7477f34824162b7 adds a test for the second scenario, but it yields your expected result.

**Comment by kptdobe** [comment]
I did not realise the definition issue. I do not think it makes sense to use the alt text of the image... We should just ignore the image.

Actually, the "real" issue is in project-helix.io (https://github.com/adobe/project-helix.io/blob/master/index.md) where the 3 properties are undefined... that's the important thing to fix.

**Comment by trieloff** [comment]
I've added the test for project-helix.io here, and it works https://github.com/adobe/hypermedia-pipeline/commit/693132c8bc2f94f63141e23d6a33d58442512680

**Comment by tripodsan** [comment]
works for me:

![image](https://user-images.githubusercontent.com/917628/51655454-18c1cc00-1fe0-11e9-8fc8-ffbe5fc9d9b4.png)
