### ISSUE TITLE
Rendering triggers an error with `hlx up`

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#32]
To reproduce:

1. Build and link hlx-cli latest master.
2. Run:
 ```
hlx init testproject
cd testproject
hlx up
```
3. Open http://localhost:3000/index.html

-> Error: 

```
[hlx] error: Error while delivering resource: Error: Cannot find module '@adobe/htlengine/src/runtime/Runtime'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at newRequire (/Users/alex/work/dev/playground/newhelixproject/alexproject/.hlx/build/html.js:36:18)
    at localRequire (/Users/alex/work/dev/playground/newhelixproject/alexproject/.hlx/build/html.js:54:14)
    at Object.parcelRequire.html.htl../html.pre.js (/Users/alex/work/dev/playground/newhelixproject/alexproject/.hlx/build/html.js:153:17)
    at newRequire (/Users/alex/work/dev/playground/newhelixproject/alexproject/.hlx/build/html.js:48:24)
    at /Users/alex/work/dev/playground/newhelixproject/alexproject/.hlx/build/html.js:80:5
    at Object.<anonymous> (/Users/alex/work/dev/playground/newhelixproject/alexproject/.hlx/build/html.js:106:3)

```

**Comment by kptdobe** [comment]
When using `npm install -g @adobe/helix-cli` to install the client I get another error...:

```
[hlx] error: Error while delivering resource: TypeError: mod.main is not a function
    at executeTemplate (/Users/alex/.nvm/versions/node/v9.11.2/lib/node_modules/@adobe/helix-cli/node_modules/@adobe/petridish/src/HelixServer.js:36:30)
    at <anonymous>
```

**Comment by kptdobe** [comment]
2nd issue: no html.js is generated, adding `@adobe/parcel-plugin-htl` to the dev dep of testproject fixes the issue. But @tripodsan mentioned this could be removed... not sure if this really works without.

**Comment by trieloff** [comment]
@davidnuescheler mentioned something similar yesterday. Haven't been able to look into it, yet.

**Comment by tripodsan** [comment]
should work...let me check

**Comment by tripodsan** [comment]
> ...centrally update the core pipeline.

which is probably a nightmare.... helix-cli-v1.X together with customer pre.js-v2.Y runs with openwhisk-helix-container-v3.27.Z which contains pipeline-v4 etc....

**Comment by trieloff** [comment]
Or: you always get the latest default pipeline upon invocation. If you want to fix a certain pipeline, you override it.

I would not want to give customers choice over the container they are running, but I also don't want customer code to go stale.

Given that we will have access to customer code (including `hlx test`) we can make sure pipeline upgrades are non-breaking.

**Comment by tripodsan** [comment]
1. parcel can't include dependencies if they are not declared in the projects package.json. I guess this is obvious, since they come indirectly via the plugin
2. parcel trips over:
```
[hlx] info:     buildDir: /Users/tripod/helix/examples/soupdemo/.hlx/build
🚨  /Users/tripod/helix/examples/soupdemo/node_modules/@adobe/openwhisk-loggly-wrapper/transport.js:19:40: Unexpected token (19:40)
  17 |   constructor(options) {
  18 |     super(options);
> 19 |     this.loggly = loggly.createClient({ ...options, bufferOptions: { size: 1 } });
     |                                         ^
  20 |   }
  21 |
  22 |   log(info, callback) {
```

so we probably want to add the `@adobe/hypermedia-pipeline` to the package.json of the project. it might make sense, since we mimick the production enviroment. so option 4)

**Comment by trieloff** [comment]
I've fixed the adobe/openwhisk-loggly-wrapper#3 issue that you've been experiencing in (2)

Adding the dependencies to the project makes sense to me.

**Comment by trieloff** [comment]
As @devongovett suggested, we might want to file an issue against Parcel to enable ES2018 object spread syntax by default for `--target node`, as node.js is supporting it.

**Comment by tripodsan** [comment]
I found a solution to inject the module path. see adobe/petridish#29. I will use this solution for now.
