### ISSUE TITLE
Discuss: Switch to Node 10.x

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#321]
the LTS support for Node8 will stop end of 2019
https://github.com/nodejs/Release#release-schedule

So we should anticipate a longer lifetime of project-helix and switch to Node 10.x.

other reasons are:
- runtime currently only has a nodejs:10-fat container (see #308 )
- more features and faster: https://www.angularminds.com/blog/article/whats-new-in-node-js-version-10-features-and-improvements.html

**Comment by tripodsan** [comment]
problems seen so far:
- https://github.com/assaf/node-replay/issues/155

**Comment by trieloff** [comment]
I think we should:
- switch to Node 10 in production
- try to maintain compatibility with node 8 for dev tooling until LTS expires in 2019
- have CI test node 8, node 10, and node 11 in parallel.

**Comment by tripodsan** [comment]
> try to maintain compatibility with node 8 for dev tooling until LTS expires in 2019

why? is there a compelling reason to stick to node8 ? does anyone really care?

**Comment by stefan-guggisberg** [comment]
+1 for node10

**Comment by trieloff** [comment]
I'd maintain node 8 compatibility for developer tooling so that Helix works with the node installation people have on their machine, which might be provided by brew or other package managers. I want to make it as easy as possible, and support the installation that people might reasonably have.

**Comment by stefan-guggisberg** [comment]
correct, the binary `hlx` distribution doesn't require node. node 8 is embedded. 

however, there is a caveat: the version of the embedded node is fixed. changing the version of the embedded node is doable but would require some porting effort.

**Comment by trieloff** [comment]
The installer is great for MacOS, I'm thinking about Linux and Windows users here. Linux users might have a node version that comes with their distribution and Windows users – who knows where they get their node.

**Comment by tripodsan** [comment]
ok :-) 

so:
- developer tooling (helix-cli) compatible with 8.x and 10.x 
- deployed actions in runtime only 10.x
- use 10.x for all CI tests
- add additional 8.x tests for helix-cli

**Comment by tripodsan** [comment]
let's reopen this end of 2019...
