### ISSUE TITLE
resource not found error message in vanilla demo project

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#322]
**Description**
The full demo throws the following error when requesting the homepage:
`[hlx] error: Resource not found: /bootstrap.min.css.map`

**To Reproduce**
1. `hlx demo --type=full myproject`
2. `cd myproject`
3. `hlx up`
4. Open Chrome Developer Tools & refresh
5. Observe console output

**Expected behavior**
No error should be thrown out of the box

**Version:**
0.9.1

**Comment by tripodsan** [comment]
solution: add proper `bootstrap.min.css.map`

**Comment by rofe** [comment]
Issue no longer present
