### ISSUE TITLE
migrate simple and full demo to the new static file handling

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#323]
## Overview
The full demo now supports `staticRoot` and by default comes with a `webroot` folder for statics.

## Details
The simple demo still sports the old `dist` folder, which may confuse users

## Proposed Actions
Consolidate on a single approach using `webroot` and remove `dist`

**Comment by tripodsan** [comment]
it does:
```
$ hlx demo foo
...
$ tree foo
foo
├── dist/
│   ├── favicon.ico
│   └── style.css
├── helix_logo.png
├── index.md
└── src/
    ├── html.htl
    └── html.pre.js
```

with the static files already in `/dist`. together with the default webroot `/`( see [helix-config](https://github.com/adobe/helix-shared/blob/v0.0.5/src/HelixConfig.js#L40) and the statics referenced via absolute URL: `<link rel="stylesheet" href="/dist/style.css"/>`

**Comment by rofe** [comment]
Maybe in the simple demo case, `favicon.ico` and `style.css` should just be in `/` then?

**Comment by tripodsan** [comment]
maybe :-) but it is important to distinguish between statics and the content based imagees, like the helix_logo.png. this is why I like /dist better.

**Comment by rofe** [comment]
right... but why use a different static folder name between simple and full demo?

**Comment by tripodsan** [comment]
so people don't confuse it....  in the fulldemo, the `webroot` is actually set in the config.


ok ok... move everything to '/' :-)

**Comment by rofe** [comment]
@tripodsan @stefan-guggisberg I assume we should still go for `/` in the simple demo, regardless of the decision made in #435? After all we still want to avoid having a `helix-config.yaml` here, right?

**Comment by tripodsan** [comment]
from what I recall from the discussion of the _docroot_, we said that the default will be `htdocs`, even if no `helix-config.yaml` is present.

**Comment by stefan-guggisberg** [comment]
i agree with @tripodsan
