### ISSUE TITLE
Adjust defaults to include *.js in build

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#328]
@rofe observed that `src/**/*.js` is not included in the default sources for `hlx up` and `hlx build`, this should get adjusted to support pure-JS actions.

**Comment by tripodsan** [comment]
please provide example. what are pure-js actions?

**Comment by tripodsan** [comment]
I think this is a bit tricky, since it must not match the `...pre.js`.

**Comment by tripodsan** [comment]
i'll cover this with #23

**Comment by rofe** [comment]
> please provide example. what are pure-js actions?

I tried with a `bla_html.js`

**Comment by trieloff** [comment]
A Pure-JS action is an action that has a JS file at the heart (`once`) of its pipeline. Instead of having the JS compiled from HTL, JST, JSX, or any other templating language, a developer has written their own `html.js`, `xml.js`, or `json.js` to emit something that is more structured than the typical HTML output.

**Comment by tripodsan** [comment]
ok, so basically a `pre.js` without the `pre` :-)

currently, we don't to any pipeline wrapping to `.js` functions in parcel. I created a new issue: #334
