### ISSUE TITLE
Copied files don't have source maps

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#329]
When running `hlx up src/*.js`, the JS files from `src` are copied into build, but breakpoints cannot be set because they are simply copied without adding the correct source map. There might be an underlying Parcel issue here.

/foundby @rofe

**Comment by tripodsan** [comment]
server or client side JS files?

we only support server side JS files and they need to be referenced via `require()` and then they are embeded into the `html.js` and should be covered with the source map.

clientside JS should not touched by parcel. so better to put them into `dist`.

**Comment by tripodsan** [comment]
I'm currently rewriting the src generation for #23. this will cover this problem.

**Comment by tripodsan** [comment]
@trieloff do you think, pure action-js should really be pure action? or rather just the `once` function?
it should be possible to do both, I think. like in the XML pipeline, you probably only want to implement the XML serialization. otherwise the dev needs to know too much about openwhisk.

**Comment by trieloff** [comment]
I mean scripts that have a `once` function that is written in JS, not in a template language.

"Real pure" actions are a less common case that should be handled separately.
