### ISSUE TITLE
Default CircleCI does not work for projects without package.json

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#330]
Observed by @hirenoble
In a project like https://github.com/hirenoble/helix-2 the CircleCI build fails:

- `restore_cache` won't work because no `package.json` exists
- `npm install` creates some output, leaving a `--dirty` working directory
- `hlx deploy --no-auto` complains that the working directory is dirty

**Comment by trieloff** [comment]
I'm not sure what we can do about the cache-restoration. 

`npm install` can probably be guarded with an `if [ -e "package.json" ]`

**Comment by tripodsan** [comment]
> I'm not sure what we can do about the cache-restoration.

we can skip the entire npm install and cache restoration if the project doesn't have a package.json. because then there is nothing to install or restore. :-)

**Comment by trieloff** [comment]
What I meant was: skipping `npm install` can be done through shell conditions, but skipping `cache_restore`, etc. is implemented as native CircleCI functionality, so we would need either CircleCI conditions (and I haven't found a condition that's dependent on the existence of a file) or we find out what command CircleCI is calling behind the scenes and guard **that** command with an `if`.

**Comment by tripodsan** [comment]
but in the conf, the cache restore is relying on:
```
            - v1-dependencies-{{ checksum "package.json" }}
```

we could change it to:

```
            - v1-dependencies-{{ checksum "package-lock.json" }}
```

and create an empty `package-lock.json` if it doesn't exist before the cache restore.

**Comment by trieloff** [comment]
That's a dirty trick. I like it!
