### ISSUE TITLE
Improve test code coverage

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#333]
the code coverage is currently at ~~77~~83%. I think testing `deploy.cmd.js` properly would increase the coverage a lot, since many uncovered sources are used during deploy.

**Comment by rofe** [comment]
I don't think +0.17% is enough :) 

Reopening...

**Comment by rofe** [comment]
Test code coverage has improved to 92% since Feb. Everything except `auth`, `clean`, `demo` and `perf` is above 80%. I think that's good enough for now.
