### ISSUE TITLE
Pure-JS actions are not wrapped 

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#334]
**Is your feature request related to a problem? Please describe.**
as discussed in #328, _pure-js_ actions (eg: `html.js` or `html_dump.js` are currently not transformed/wrapped by parcel, and end up as-is in the openwhisk action. this means the developer needs to write (and understand) the openwhisk web action invocation semantics.

**Describe the solution you'd like**
Ideally, such _pure-js_ actions are automatically wrapped with parcel so that the developer can write them the same way as the `...pre.js` actions.

**Describe alternatives you've considered**
the only alternative is to write a `pre.js` and have an empty `.htl`

**Comment by trieloff** [comment]
@rofe you've been experiencing this.

**Comment by trieloff** [comment]
@tripodsan did the merge of #325 fix this?

**Comment by tripodsan** [comment]
with this fixed, pure action can be written with a simple `main` pipeline function. for example:

**src/xml.js**
```js
module.exports.main = async function main() {
  return {
    body: `<?xml version="1.0" encoding="UTF-8"?>
<note>
  <to>Peach</to>
  <from>Mario</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>`,
  };
};
```

**Comment by rofe** [comment]
Not sure yet if this is a `helix-cli` or `helix-pipeline` (specifically [#106?](https://github.com/adobe/hypermedia-pipeline/issues/106)) problem, but my example of a pure js action fails in the `validate` action due to an interestingly looking `response` object during step 6 after the `main` function (where I simply return `payload`) got executed:

main function in test_xml.js:
```
async function main(payload, action) {
    return payload;
}
````

payload dump:
```
{
    "content": {
        ...
    },
    "request": {
        ...
    },
    "response": {
        "request": {
            ...
	},
	"content": {
	    ...
        }
    }
}
```
Looks like at some point `response` got confused with `payload` and `request` and `content` objects got duplicated inside...

**Comment by rofe** [comment]
The `response` seems to be merged into `payload` right after the 'main' function. The error message is ```Error: Invalid Context at step 6
data.response should NOT have additional properties, data.response should NOT have additional properties```

**Comment by trieloff** [comment]
@rofe try changing two things:

1. in pipeline: `content.xml` to `response.xml` (also in the schema)
2. in your `main`: `return {xml: payload};

**Comment by tripodsan** [comment]
the pure-js action, should act like a pipeline function, so @rofe's example above should work, IMO.
the problem is, that the generated `htl` script does not comply with the pipeline function, so the wrapper is wrong.

**Comment by rofe** [comment]
Thanks @tripodsan it works now. One just needs to be careful to add a `response` object in the `main` function (at the latest).
@trieloff not sure I follow your proposal... let's maybe continue this change request in a separate issue in `helix-pipeline`
