### ISSUE TITLE
Progress bar for `hlx deploy` is jumpy and skippy

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#341]
Running `hlx deploy` creates a progress bar that jumps back and forth (from nearly 100% to 80%) and that creates line breaks, resulting in output like this:

```bash
$ hlx deploy --no-auto
[==================================================] analyzing static.js 0.0s
[================================------------------] packaging node_modules/request-promise-native/package.json 0.2
[==================================================] packaging node_modules/lodash/package.json 0.0s
[==================================================]  0.0s

✅  deployment completed
```

**Comment by tripodsan** [comment]
hmm... it should only create 3 progress bars. 1 for analyze, one for packageing and 1 for deployment.

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
