### ISSUE TITLE
Runtime deploy issue in circleci on first deploy

### ISSUE THREAD

**Issue by stevengill** [adobe/helix-cli#345]
**Description**

Even though my `hlx deploy` command is correct, sometimes circleci build fails at the runtime deploy step. I fix it by manually running the build again in circleci. It seems to happen on the very first deploy. 

The issue I see in circleCi is 

```
Missing required arguments: wsk-namespace, wsk-auth
OpenWhisk Namespace is required
Authentication is required. You can pass the key via the HLX_WSK_AUTH environment variable, too
Exited with code 1
```

these variables are passed in and setup properly in circleci. Like I said, running the build manually makes it work. Not sure if this is an issue with circleci or runtime. Probably circleci not setting up the env var quick enough. 

**To Reproduce**
1. Go through the quickstart in the readme on https://github.com/adobe/helix-cli
2. Run `hlx deploy command` (with all of the flags filled in)
3. Log into circleci, see that the build fails
4. rerun the job manually, it will pass.

**Expected behavior**
It should pass on first build

**Version:**
0.9.1

**Comment by trieloff** [comment]
Can you share the links to your CircleCI builds?

When you run `hlx deploy` again, it will trigger a new build – can you try this? I'd like to make sure that this really is a race condition that can be solved with a bit of sleep, not an issue with the way the build is started.
