### ISSUE TITLE
Enable Snyk Runtime

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#351]
We are part of the Snyk Runtime beta: https://snyk.io/blog/introducing-open-source-security-runtime-monitoring

**Comment by tripodsan** [comment]
I don't really understand what this does. but it currently fails one of the builds:
https://circleci.com/gh/adobe/helix-cli/6175?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

where as the normal build works.
