### ISSUE TITLE
Integrate LGTM in new projects

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#360]
Thanks to the help of @sjvs and @xiemaisi we now have a LGTM query that can detect leakage of `secrets` into the log files: https://lgtm.com/query/2480616262882982836/

We should include a `lgtm.yaml` file in the new project template that flags these offenses (and others we may add over time).

If possible, we should also enable LGTM monitoring for projects as part of `hlx deploy`.

**Comment by trieloff** [comment]
Here is one way to add custom queries to a project: https://lgtm.com/help/lgtm/about-queries#how-do-i-add-custom-queries-to-LGTM – ideally we would like to share queries across all Helix projects.

**Comment by trieloff** [comment]
Here is the query for project-helix.io https://lgtm.com/query/1474841491343831399/

**Comment by trieloff** [comment]
And here is a query to detect access to `payload.content.children`, which we can use as a deprecation tracker: https://lgtm.com/query/3720393903689988445/

**Comment by xiemaisi** [comment]
I think you don't even need a taint-tracking configuration for this one (though I may have misunderstood the intent of the query): https://lgtm.com/query/1736810846736096811/

**Comment by trieloff** [comment]
@xiemaisi nice, that's so much shorter.

**Comment by sjvs** [comment]
Hi @trieloff. It looks like the `.ql` files in the `project-helix.io` repository don't have a query id. Here's the log file: https://lgtm.com/projects/g/adobe/project-helix.io/querypacks

For more info, please see "Add the query metadata" section on this page: https://lgtm.com/help/lgtm/writing-custom-queries

Here's an overview of all query metadata: https://lgtm.com/help/ql/writing-queries/query-metadata

**Comment by trieloff** [comment]
Thanks for the heads-up @sjvs – let's see if I got it right with the last two commits.

**Comment by sjvs** [comment]
That's all looking great now, @trieloff: https://lgtm.com/projects/g/adobe/project-helix.io/querypacks. And the first results are in: https://lgtm.com/projects/g/adobe/project-helix.io/alerts/?mode=tree&tag=&ruleFocus=1506752697150

**Comment by trieloff** [comment]
Oooh, this is soo cool. Thanks for all the help, @sjvs and @xiemaisi!

**Comment by kptdobe** [comment]
This should be fixed.
