### ISSUE TITLE
hlx deploy does not report the action name anymore

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#365]
While troubleshooting for @hirenoble (https://circleci.com/gh/hirenoble/helix-5/4) I noticed that the deploy URL is not reported anymore, which makes ad-hoc editing of config files a bit hard.

We should re-add it.

**Comment by tripodsan** [comment]
someone streamlined the nice verbose logging with a progress bar :-)

**Comment by tripodsan** [comment]
this was fixed with #437
