### ISSUE TITLE
hlx deploy does not pick up ref from helix-config.yaml

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#366]
Working with following config file: https://github.com/hirenoble/helix-5/blob/master/helix-config.yaml

`hlx deploy` command does not pick up the correct `ref` (should be `"master"`) by keeps it empty.

https://circleci.com/gh/hirenoble/helix-5/12 (expand the "Deploying to Adobe I/O Runtime" step)

generated `.hlx/strains.json`
```json
{
  "default": {
    "name": "default",
    "code": "/io-solutions/default/git-github-com-hirenoble-helix-5-git--master--",
    "content": {
      "protocol": "ssh",
      "host": "github.com",
      "port": "",
      "hostname": "github.com",
      "owner": "hirenoble",
      "repo": "helix-5",
      "ref": "",
      "path": ""
    },
    "static": {
      "protocol": "https",
      "host": "github.com",
      "port": "",
      "hostname": "github.com",
      "owner": "hirenoble",
      "repo": "helix-5",
      "ref": "master",
      "path": "",
      "magic": false,
      "allow": [],
      "deny": []
    },
    "condition": "",
    "directoryIndex": "index.html",
    "perf": {
      "device": "",
      "location": "",
      "connection": ""
    }
  }
}
```

/cc @hirenoble

**Comment by tripodsan** [comment]
how does the helix-config.yaml look like?
if there is no `...#ref` in the git url, then there is no `ref` in the json, because the github determines the default branch.

we could ignore this and always default to `master` or use the github API to detect the default branch.

**Comment by kptdobe** [comment]
While debugging #369, we found the explanation for this issue: not implemented!

There is one confusing in the description: the `ref` which is missing in the `.hlx/strains.json` is not the code one (i.e. `master`) but the content one (i.e. `e150fab47ca1df49ab0a4a0d289663b04775f577`).

The `deploy` method falls back to the git-url origin to determine the content git url if it does not find a `content` (well currently `contentRepo` url, see #369) in the yaml. It is not implemented to check for the default strain.

@hirenoble: until all of those are fixed, using `contentRepo: https://github.com/hirenoble/helix-5.git#e150fab47ca1df49ab0a4a0d289663b04775f577` to your helix-config.yaml file should do the trick for now

**Comment by tripodsan** [comment]
no longer relevant with the lates config changes.
