### ISSUE TITLE
Separate hlx package step from hlx deploy

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#368]
`hlx --help` says that `hlx build` is building and packaging. In reality, packaging happens during `hlx deploy`, no matter if code has changed or not. 

I suggest we separate the `hlx package` step out of `hlx deploy`, but run it from `hlx deploy` unless disabled (`--no-package`) when the packages are outdated.

**Comment by trieloff** [comment]
I would say with the new deployment mechanism, where we create OpenWhisk packages (i.e. folders for actions) for each deployment, based on the sha, we can keep the action name simple and transparent, e.g. `html.htl` compiles to `html.js` packages to `html.zip` deploys as `/$SHA/html`.

**Comment by tripodsan** [comment]
changes to be affected with #437:

## new package command:
the package command uses the `*.info.json` files produced by the `build` step to analyze the required modules and then creates an openwhisk action including all the required node modules and source files. after creation of the zips it writes back the `*.info.json` files with detailed information about the action. this information ca be used by the `deploy` command.

the package command also emits 2 events: `package-created` and `package-ignored`.
those are only really used for testing.

```
$ hlx package --help
hlx package

Create Adobe I/O runtime packages

Package options
  --force       Forces creation of packages even if the sources are not
                modified.                             [boolean] [default: false]
  --target, -o  Target directory for packaged actions
                                                [string] [default: ".hlx/build"]

Options:
  --version    Show version number                                     [boolean]
  --log-file   Log file (use "-" for stdout)              [array] [default: "-"]
  --log-level  Log level
        [string] [choices: "silly", "debug", "verbose", "info", "warn", "error"]
                                                               [default: "info"]
  --help       Show help                                               [boolean]
```

## changes to deploy command

the `deploy` command invokes the `package` command for non-auto deployments, if the `--package` argument is not set to `ignore`.
setting the `--package` argument to `always` will force recreation of the packages. default is `auto`.

the `deploy` command uses the information provided in the `*.info.json` files updated in the `package` command.

```
$ hlx deploy --help
hlx deploy

Deploy packaged functions to Adobe I/O runtime
.
.
.
Package options
  --package     Automatically create or update outdated action packages.
                [string] [choices: "auto", "ignore", "always"] [default: "auto"]
  --target, -o  Target directory for compiled JS[string] [default: ".hlx/build"]
.
.
.
```
