### ISSUE TITLE
Github rate limit reached for local development

### ISSUE THREAD

**Issue by stevengill** [adobe/helix-cli#380]
Unauthenticated github api requests are rate limited at 60 requests per hour. If we were authenticated, we could do 5000 per hour. [Source](https://developer.github.com/v3/#rate-limiting)

I ran into this limit while doing local development.

Suggestion: Let's allow users to set an environment variable with a github personal access token. `hlx up` would grab the variable and pass it along to the pipeline which could use it to make the github api requests.

**Comment by trieloff** [comment]
I'd hope that we could do even more than that and go through the OAuth flow with GitHub.

**Comment by filmaj** [comment]
@trieloff how would you envision this flow working for a developer using hlx from the command line?

**Comment by trieloff** [comment]
I'd love to have a development flow with a `hlx auth` step that launches a small web app which validates all credentials that are needed (GitHub, Adobe, Fastly, etc) and then passes the relevant tokens back to the command line application for local safekeeping.

I think @purplecabbage mentioned a command line tool that did some OAuth trickery at the Hackathon. If I remember correctly, this app would create a temporary URL for the authentication session and then keep pinging that URL until the authentication flow has been completed.

**Comment by tripodsan** [comment]
I'd like to elaborate this further. for now I created a simple prototype how we could create a token on the fly. https://github.com/adobe/helix-cli/pull/547. subsequently, the token should be made available to `hlx up` and the `helix-simulator` via `HLX_GITHUB_TOKEN`

**Comment by purplecabbage** [comment]
The previously mentioned runtime function to serve as a login redirect page can be found in adobe private git:
io-dev-tools/aio-cli-login-function

The cli code that calls it is here: 
io-dev-tools/aio-cli-plugin-oauth2

Note this is generically named oauth2 although the runtime function code is very specific to our own adobe-id authentication and uses an integration created in adobe.io/console; scopes and redirect_url are all specific to the integration.

@tripodsan your solution looks good, in our case we were trying to avoid typing username and passwords for third parties into our tooling.  This may or may not be an issue in your case.

**Comment by tripodsan** [comment]
The _personal access token_ is quite invasive as it grants repository access to all repositories the user has. Same is true for creating an OAuth app. It  would be better to use a github app and create an access token so that the requests can act on the apps behalf, if this is possible.

something like:

1. the user installs the bot on the content repository
2. the user logs in (either via cli or browser)
3. the bot creates an access token that acts in behalf of the bot
4. we store the token in the action that access the content (or in the edge directory of fastly)

**Comment by trieloff** [comment]
Is there an easy way for us to refresh an installation token once it has expired?

**Comment by tripodsan** [comment]
> Is there an easy way for us to refresh an installation token once it has expired?

I wouldn't go the route with the installation token anymore, but with the [gitapp access token](https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/). afaics, those never expire.

**Comment by rofe** [comment]
Is this still an issue since `hlx auth`?

**Comment by tripodsan** [comment]
`hlx auth` has nothing to do with this... this is probably no longer a problem anyways, since we now use the github raw api...
