### ISSUE TITLE
Rolling deployments

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#383]
You are most likely to break something when deploying new code, so we should establish rolling deployments, which means for every branch (including dirty) we keep three deployments: previous, current, and next. 

`hlx deploy` would then use OpenWhisk's copy to copy current to previous, next to current and deploy next fresh from source.

We also implement a deployment pointer in VCL (edge dict) that by default points to current.

In case of a mistake, you can then run `hlx oops --rollback` or `hlx oops --rollforward` to change the deployment pointer without touching anything else in the VCL.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kptdobe** [comment]
Not sure we need this if the deployment is super clear and transparent: the code is tagged via git, if you want to rollback, you can just deploy from a previous git commit.
I would rather say: we should eliminate the `deploy` phase. If the strain contains content / code / static git urls, then `hlx publish strain_x` should know exactly what to update and the developer gets a clear picture of what he just deployed. If there is a mistake, he can change the branch / tag in the code url, and publish again.

**Comment by trieloff** [comment]
See also #81

**Comment by trieloff** [comment]
We don't need this to implement #81
