### ISSUE TITLE
Require without file extension

### ISSUE THREAD

**Issue by Corwynt** [adobe/helix-cli#397]
**Description**
In one of the latest releases, using `require` on a local file does not work anymore if the file extension is omitted. I need this functionality to allow the inclusion of **jsx** files. These files have the **jsx** extension in the source directory, but are renamed to **js** files inside the `.hlx/build` directory and can therefore not be required anymore.

**To Reproduce**
1. Create a new demo project `hlx demo test`
2. add a new js file `src/test.js` with content `module.exports = "Test";`
3. add `const test = require("./test");` at the beginning of `src/html.pre.js`
4. run helix with `hlx up`

**Expected behavior**
Helix should build the project without complains.

**Version:**
0.10.10

**Comment by tripodsan** [comment]
how are you using the `jsx` files? i.e. do you have a parcel plugin that transforms them into pipeline function? if they are clientside files, don't put them im `src` but _build/copy_ them into `/dist` (or whatever your webroot is).

but I agree, that it should work w/o extension.

**Comment by tripodsan** [comment]
this now works with `hlx up`, but not with `hlx package`
