### ISSUE TITLE
Remote Publish/Remote Perf

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#401]
I'd like to move most of the work that `hlx publish` does into a separate `helix-publish` OpenWhisk action/microservice. Same for `hlx perf` and `helix-perf`.

With this, we can massively reduce the complexity of the client-side applications (they only need to make one request to the micro service) and get a number of advantages:

- force feeding updates to VCL and other config files
- easier sharing of access tokens (e.g. for Calibre or Logging endpoints)

**Comment by trieloff** [comment]
See adobe/helix-logging#5 and adobe/helix-cli#372

**Comment by tripodsan** [comment]
why the extra indirection? would you create one for each customer (installed during `hlx-deploy`) or have a global one? how do you retrieve the fastly access tokens (the bot will be able to)?

in any case, we should keep the `publish` logic available as cli (and API). if not in `hlx` then `hlxctl`.

**Comment by trieloff** [comment]
> why the extra indirection? 

For `publish`:

1. so that we can force-update the VCL and are not dependent on CLI updates
2. because we have significant parts happing remotely in `helix-logging` anyway (and can't move them away)

For `perf`:

- so that we can use a shared performance monitoring account and users don't need to bring their own Calibre credentials anymore

> would you create one for each customer (installed during hlx-deploy) or have a global one?

One global. See above.
