### ISSUE TITLE
Example urls are dead

### ISSUE THREAD

**Issue by koraa** [adobe/helix-cli#422]
The following urls return 404s; they are mentioned in the integration test readme: 

https://launch.primordialsoup.life/administration/adapters.html
https://launch.primordialsoup.life/README.html

**Comment by PreethiJC** [comment]
Found a few more dead URLs mentioned in the integration test readme:

https://preview.primordialsoup.life/README.html 
https://lars.primordialsoup.life/hello.html
https://lars.primordialsoup.life/moscow/moscow.html
https://xdm.primordialsoup.life/README.html
