### ISSUE TITLE
Reconsider strains.yaml location

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#43]
`strains.yaml` ends up in the `.hlx` folder. It is generated by hlx, but I would not expect to edit files in `.hlx` folder. We never edit files in the `.git` folder…

**Comment by kptdobe** [comment]
@trieloff says:

I’ve modeled it after CircleCI’s `.circleci/config.yml` but we can change it.
One way of doing it would be to have `helix-dev.yaml` (i.e. `helix-config.yaml`) and `helix-prod.yaml` (i.e.`.hlx/strains.yaml`)

**Comment by tripodsan** [comment]
see https://github.com/adobe/petridish/issues/75
