### ISSUE TITLE
intermittent failing logger test on circleci

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#433]
**Description**
happens only on circle ci...sometimes:

```
  1) Testing standard logger configuration
       File logger can be created:
     Uncaught Error: ENOENT: no such file or directory, open '/home/circleci/repo/test/tmp/testlog.log'
      at Object.fs.openSync (fs.js:646:18)
      at Object.fs.readFileSync (fs.js:551:33)
      at Timeout.setTimeout [as _onTimeout] (test/testLogCommon.js:57:22)
```

**Expected behavior**
no errors.

**Comment by DrewML** [comment]
Likely related: https://github.com/winstonjs/winston/issues/1504. Winston 2/3 historically has a _ton_ of problems with answering the question "have all logs been flushed?"

Relevant: https://github.com/winstonjs/winston#awaiting-logs-to-be-written-in-winston

**Comment by tripodsan** [comment]
well, there are other cases, where we want to test the log output. so maybe a string based transport for winston would help here.

**Comment by DrewML** [comment]
Seems like that would make more sense imho. I assume you'd want an upstream change in `@adobe/helix-shared` to add the option for some form of string based transport? It seems like the usage of `winston` is just an implementation detail of `helix-shared` so I wouldn't want to reach in and muck with transports.

**Comment by tripodsan** [comment]
I added a string based test logger here: https://github.com/adobe/helix-cli/commit/ce67700d2e2f7c49f499d3693a7e25077b7ee6c2

I would disable the common log tests here and wait until winstonjs/winston#1504 is fixed.
another issue might arise, if the winston versions used in shared and cli are not the same. this happens to me a lot when npm linking the helix-shared during development. then the `winston.loggers.clear()` doesn't work and the tests fail. 

> It seems like the usage of winston is just an implementation detail of helix-shared so I wouldn't want to reach in and muck with transports.

exactly. I suggest that we remove the winston dependency from helix-cli and only rely on helix-shared. so maybe create a string transport when passing `/dev/text` or something :-)
