### ISSUE TITLE
provide cgi like actions

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#436]
as discussed during the 4/2018 hackathon, we should produce an ability to create cgi-like actions.

- they will be served from in `htdocs/cgi-bin`
- they contain a main function that has the same signature as a pipeline function
- they are similar to the pure actions (#334) but are not bound to a resource but have a url.

for example:

`htdocs/cgi-bin/login.js`

would be invoked with:

`https://demo.project-helix.io/cgi-bin/login.js`

/cc @davidnuescheler

**Comment by trieloff** [comment]
https://cq-dev.slack.com/archives/C9KD0TT6G/p1557392651377800

iven that the action and package name for `src/html.htl` is `trieloff/2c5fbf40237634b75ba3ed821172dfc53b27a091/html`, what should be action and package name for `cgi-bin/html.js`?

I'm seeing following options:

1. `trieloff/2c5fbf40237634b75ba3ed821172dfc53b27a091/html` (i.e. allow conflicts)
2. `trieloff/2c5fbf40237634b75ba3ed821172dfc53b27a091/cgi-bin-html` (inject prefix and hope to avoid conflicts)
3. `trieloff/2c5fbf40237634b75ba3ed821172dfc53b27a091-cgi-bin/html` (create a new package to really avoid conflicts)

**Comment by stefan-guggisberg** [comment]
2. or 3., with a soft pref for 2.

**Comment by rofe** [comment]
2

**Comment by trieloff** [comment]
Too late, **2** is already implemented.

**Comment by trieloff** [comment]
Use case: https://team.project-helix.io has a form that is currently an embedded google sheets iframe. With cgi-bin actions we can replace it with a proper contact form.

**Comment by tripodsan** [comment]
things to consider:

- [ ] `cgi-bin` needs special treatment in fastly, to allow POSTs (also see https://github.com/adobe/helix-pipeline/issues/251)
- [ ] if normal pipeline handles it, there will be a problem with POSTs as well.
- [ ] since the cgi-bin is not bound to a resource, it is quetionable if it should be handled by helix-pipeline... maybe for starters, we just treat them as raw openwhisk actions instead?

**Comment by tripodsan** [comment]
> Too late, **2** is already implemented.

where?

**Comment by trieloff** [comment]
The build/deploy part of the implementation is in #851 

> `cgi-bin` needs special treatment in fastly, to allow POSTs (also see adobe/helix-pipeline#251)

Yes, there should be a new `X-Request-Type = "CGI"` to handle this.

>  if normal pipeline handles it, there will be a problem with POSTs as well.

No. The normal pipeline should remain GET only.

>  since the cgi-bin is not bound to a resource, it is quetionable if it should be handled by helix-pipeline... maybe for starters, we just treat them as raw openwhisk actions instead?

Yes, that was my plan. The helix-pipeline as it stands would only get in the way, so these are raw OW actions.

**Comment by rofe** [comment]
@trieloff can you add documentation and/or a quick code sample?

**Comment by trieloff** [comment]
Yes, as this becomes more practical to use. Right now, you can build and deploy the `cgi-bin`, but you cannot invoke it anywhere.
