### ISSUE TITLE
improve eslint settings to deal with 2018 and 2019 in copyright headers

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#438]
the [eslint-plugin-header](https://github.com/Stuk/eslint-plugin-header) doesn't seem to support patterns in multiline block comments (it just concatenates the lines for matching.)

the following options:
1. fix the plugin
2. use a very long pattern
3. try to find another plugin that does the same

**Comment by tripodsan** [comment]
I think we should fix the plugin.

**Comment by trieloff** [comment]
I'd go with the alternative plugin you've found.

**Comment by tripodsan** [comment]
> I'd go with the alternative plugin you've found.

I haven't tried and I think it isn't better....

**Comment by tripodsan** [comment]
provided PR for header plugin. https://github.com/Stuk/eslint-plugin-header/pull/21

**Comment by tripodsan** [comment]
fixed.
