### ISSUE TITLE
[hlx build] gets slower and slower when HTL grows

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#463]
**Description**
With a normal size HTL file (like 2000 lines), the build process quickly takes more than 7s. It goes up to 18s when the file reaches 6500 lines. In both cases, there is no HTL instruction, only HTML. This should take less than a second to process.

**To Reproduce**
1. `hlx demo`
2. `cd demo`
3. `hlx build'
4. -> `Built in 700ms`
5. Edit `src/html.htl` and replace the content by the output view-source:https://www.adobe.com/ (just random HTML ~2000 lines)
6. `hlx build'
7. ->  `Built in 6.59s`
8. Edit `src/html.htl` and replace the content by the output view-source:https://www.tesla.com/model3 (just random HTML ~6500 lines)
6. `hlx build'
7. ->  `Built in 18s`

**Expected behavior**
Even if performance degradation is ok, the build process should stay under 1s, especially if there is no "special" treatment to happen like processing the HTL specific tags.

**Version:**
run: `$ hlx --version`
0.10.16

**Comment by kptdobe** [comment]
I traced it to the HTMLParser#update method: https://github.com/adobe/htlengine/blob/master/src/parser/html/HTMLParser.js#L71-L365
A monster which will be hard to improve...

**Comment by kptdobe** [comment]
The function has no tests! 
It is iterating through all the characters of the HTML input (400k characters in the case of the 6500 lines HTML) which is why it takes so long.
@tripodsan Any thoughts ?

**Comment by tripodsan** [comment]
it has a test: `html_parser_test.js`

well, it's a parser and needs to read all the characters :-) I tried to combine the HTML parsing with the HTL expression parser, but it was too difficult with the context switching. the HTML parser is copied from the one in AEM, but maybe it can be optimized for javascript. and we can certainly test other parsers. 

also note, that the parser sends event while parsing and uses a 2nd ANTLR4 based parser for the HTL expressions. so the time you are measuring is the combined time of the HTML parsing and the HTL parsing.

**Comment by tripodsan** [comment]
btw, I tested the parser + processor:

```
  HTML Parsing
    ✓ parses simple.htm
    ✓ parses and processes simple.htm (170ms)
    ✓ parses 200kb.htm (58ms)
    ✓ parses and processes 200kb.htm (7474ms)
```

it seems that the parser is reasonably fast, but the processing (i.e. converting the HTML DOM into the HTL command stream is slow.

**Comment by tripodsan** [comment]
I think having huge junks of HTML is a problem anyways. as it all ends up in a huge `out("")` statement in the JS. we should consider using `<sly data-include="large.html"/> some something, bundle it with the action and then load it from disk instead. or use an ESI include and move it to `htdocs` :-)

**Comment by kptdobe** [comment]
Awesome! My project went from 10.87s to... 575ms. Nice build time improvement!!

Thanks @tripodsan!

Every time you do not have an HTL command, you get an HTML block. I assume this will not happen too often they get so huge. Except when like me you start by dumping the HTML you want to "HTLify" and progressively replace some blocks by payload properties.
If those blocks get too big, it might be for special cases like including a font, some styles, inline images... and here it makes total sense to extract and put somewhere else. It is just hard to express when you need to consider exploding your HTL (build time too slow?). 
I'll continue observing performances anyway, a slow build time is really annoying when you develop because it rebuilds on each save which happens really often!
