### ISSUE TITLE
Setting up new project Windows 10 x64

### ISSUE THREAD

**Issue by Temilol** [adobe/helix-cli#479]
**Description**
Running `hlx up` to start up the development of a new project produce error:

```Unknown signal: SIGUSR1```

**System Information**
OS: `Windows 10 x64 arch`
Processor Type: `Intel(R) Xeon(R) E5507`
RAM: `16 GB`

**Comment by stefan-guggisberg** [comment]
On Linux or Mac `helix up` automatically launches the node debugger by sending the `SIGUSR1` signal to the current process. This is not supported on Windows.

In PowerShell, you can enter the following to enable debugging of your local helix project:
```
$env:NODE_OPTIONS="--inspect"
hlx up
```

**Comment by stefan-guggisberg** [comment]
disabled sending `SIGUSR1` on windows in 812d320

**Comment by trieloff** [comment]
@Temilol thanks for the bug report!
