### ISSUE TITLE
[hlx package] does not package "linked" dependencies

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#487]
**Description**
While developing, I `npm link` the helix-pipeline to the helix-cli. When I run `hlx deploy` on my project, the helix-pipeline is not deployed at all. The wsk action cannot be executed.

**To Reproduce**
1. In helix-pipeline: `npm install`, then `npm link`
1. In helix-cli: `npm install`, then `npm link`, then `npm link @adobe/helix-pipeline`
1. In a project, run `hlx build` and then `hlx package`

Open the `.hlx/build/html.info.json` and check the `externals` libraries: `@adobe/helix-pipeline` is not in the list.

**Expected behavior**
`@adobe/helix-pipeline` should be part of the `externals` libraries

**Version:**
run: `$ hlx --version`
0.12.1-pre.0

cc @tripodsan

**Comment by kptdobe** [comment]
I identified the issue: https://github.com/adobe/helix-cli/blob/master/src/parcel/ExternalsCollector.js#L71

When linked, the module resource / path is not `node_modules/@adobe/helix-pipeline` but the path of the linked folder. The regex does not consider that case.

**Comment by tripodsan** [comment]
a workaorund is to `npm pack` the dependency and the reference it via `file://`

eg:

```
$ cd helix-pipeline
$ npm pack
$ cd ../helix-cli
$ npm add ../helix-pipeline/helix-pipeline@0.1.2.tgz
...
```
