### ISSUE TITLE
Improve full demo

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#491]
**Description**
We should improve the example with more realistic use case:

1. in `pre.js` go over all sections and calculate an `id` based on `section.title`
2. in `pre.js`, inject an anchor (`<a href="#${id}" />`) to the `section.dom` 
3. in `htl`, output the section with id:
```
<sly data-sly-list="${content.sections}">
    <section id="${item.meta.title}">
        ${item.dom.innerHtml}
    </section>
</sly>
```
**Additional context**
- missing feature: `section.dom`

**Comment by rofe** [comment]
I wonder if this is still relevant now that we simply output `content.document.body.innerHTML` instead of looping anything...

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
