### ISSUE TITLE
[usability] harmonize options to save default config in hlx up and deploy

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#494]
**Description**
When creating a simple `hlx demo` and running `hlx up`, the console outputs the following:
```
The project does not have a helix-config.yaml which is necessary to 
access remote content and to deploy helix. Consider running 
hlx up --save-config to generate a default config.
```
I think this is good from a usability POV. However, when running `hlx deploy` on the same project without `helix-config.yaml`, the following output appears:
```
No helix-config.yaml. Please add one before deployment.
You can auto generate a default config with
$ hlx deploy --add=default
```
While I think it's great that the CLI is now providing guidance when the config is missing, I find it a bit confusing that the options are so different

**Expected behavior**
I think both `hlx up` and `deploy` should have a "ad config" option which is equally named, either `add` or `save-config`. The explanations could also be harmonized.

**Version:**
0.13.3-pre-1

**Comment by tripodsan** [comment]
the difference is: `--add` adds a missing strain, where ass `--save-config` generates the entire config. I agree that `--save-config` is not optimal. I would rather like to have an individual command or have a _config wizard_.

**Comment by rofe** [comment]
> the difference is: `--add` adds a missing strain

Well, it would also have to add an entire config file if none is present (which was the case in my test above)...

**Comment by rofe** [comment]
@tripodsan I would propose to remove the `--save-config` option from `hlx up` again as having a config file isn't relevant until you attempt to `hlx deploy`. How about changing the current behavior as follows:
1. Remove `--save-config` (and related console output) from `hlx up`.
2. Have `hlx deploy` auto-generate a config file if none is present (like `hlx up --save-config` is currently doing), then abort deployment, asking the developer to first review/adjust it before retrying.
3. Maybe rename `--add` to `--add-strain` to be more self-explanatory?

cc @trieloff @kptdobe

**Comment by tripodsan** [comment]
> having a config file isn't relevant until you attempt to `hlx deploy`.

Hmm, A dev would want to create a multi-strain site with proxies etc, so he would be glad to have a default config. but, if he is so advanced, he could probably use `hlx deploy --add-strains --dry-run`.

so ok, for your proposal.

**Comment by rofe** [comment]
Bear in mind this is only for the simple demo case - the full demo has a default config file.

**Comment by rofe** [comment]
Let's revisit this as part of the developer experience discussion at the next hackathon. Linking to #711 and unassigning myself.

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
