### ISSUE TITLE
Detect and fix missing parcel-plugin-htl dependency

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#5]
If you do not add a dev dependency to `adobe/parcel-plugin-htl` in the "code" project, `hlx build` and `hlx up` does not compile the htl and pre.js files.

I think the hlx-cli should to bring whatever it needs and do not require the "code" project to have certain dev dependencies constraints.

----

+1 yes. dev deps only for testing

----

-1 I think it's better to make the dependencies explicit, so that you can add support for other templating languages simply by adding them as a dependency of your project instead of having us to adjust helix-cli for every new language.

----

adobe/project-helix#243 should take care of bootstrapping the project so that you don't forget about the dependency.

----

> ...so that you can add support for other templating languages simply by adding them as a dependency of your project instead of having us to adjust helix-cli for every new language.
true. but then, hlx up should probably complain if no parcel plugin is defined with a appropriate error message.

----

I agree.

Or even suggest to add it itself.

**Comment by tripodsan** [comment]
this is no longer needed.
