### ISSUE TITLE
deploy may use the wrong git remote when adding a missing strain

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#514]
**Description**
When running `npm test` on a git clone using `https://github.com/adobe/helix-cli.git`, the following error occurs:
```
1) hlx deploy (Integration)
       deploy reports affected strains with default proxy:

      AssertionError [ERR_ASSERTION]: '#\n# helix configuration for local development\n#\nversion: 1\n\ndefinitions:\n  defaults:\n    - &localRepo "http://localhost/ == '#\n# helix configuration for local development\n#\nversion: 1\n\ndefinitions:\n  defaults:\n    - &localRepo "http://localhost/
      + expected - actual

             address: 127.0.0.1

         new-strain:
           code: ssh://git@github.com/adobe/dummy.git#master
      -    content: https://github.com/adobe/helix-cli.git
      -    static: https://github.com/adobe/helix-cli.git/htdocs
      +    content: ssh://git@github.com/adobe/helix-cli.git
      +    static: ssh://git@github.com/adobe/helix-cli.git/htdocs
           package: 7b4d608e9eb05c0d0ca9222530b5cce408547c78

      at Context.it (test/testDeployCmd.js:273:12)
      at <anonymous>
```
The workaround is to create a fresh clone using the ssh URL `git@github.com:adobe/helix-cli.git`

**To Reproduce**
1. `git clone https://github.com/adobe/helix-cli.git`
2. `cd helix-cli`
3. `npm install && npm test`

**Expected behavior**
Tests shouldn't depend on which git clone method was used

**Version:**
0.13.3

**Comment by rofe** [comment]
@tripodsan based on your comment in #516, do you think the result in `actual` is wrong, and thus this issue should not be fixed in the test but the code?

**Comment by tripodsan** [comment]
yes. I think all 3 properties should point to `ssh://git@github.com/adobe/dummy.git#master`

**Comment by rofe** [comment]
I see... the default config is not created based on the current working dir (in this case, `testRoot`), hence the wrong git remote is being used. Working on a fix.

**Comment by rofe** [comment]
OK, just to be sure, here's what I understood the expected behavior to be like when `hlx deploy` is adding a missing strain:
1. if the working directory is a git checkout, `hlx deploy` is expected to use its `git remote`, rather than the one from wherever the parent process may have been started (in the test, it's `testRoot`).
2. so if the `git remote` in `testRoot` is `git@github.com:adobe/dummy.git`(as in the test), then the expected output in the `helix-config.yaml` is:
```
new-strain:
    code: ssh://git@github.com/adobe/dummy.git#master
    content: ssh://git@github.com/adobe/dummy.git
    static: ssh://git@github.com/adobe/dummy.git/htdocs
```
If this is correct, then the latest changes in #516 should have the fix. I also adjusted the issue title to better reflect what's wrong.
