### ISSUE TITLE
hlx deploy should not set package property for _local_ strains

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#518]
**Description**
strains that have a localhost url, are considered to be used only for local development, and therefor should not get a `package` property during deploy. this also avoids creating conditions and strains configs during publish.

**Version:**
```
$ hlx --version
0.13.4-pre.1
```

**Additional context**
also see #510

**Comment by tripodsan** [comment]
in order to mark a strain for local development, set the `code` repo to `"http://localhost/local/default.git"`. having the `url` as indicator is wrong and gets even more complicated with proper conditions.

**Comment by filmaj** [comment]
Just to double-check: I should set the `code` as above and also drop the `url`, correct?

Currently in our config [we have a default of `&defaultRepo: http://localhost/local/default.git`](https://github.com/adobe/developer.adobe.com/blob/master/helix-config.yaml#L18) and [our `basestrain` sets `code`, `content` and `static` as `defaultRepo`](https://github.com/adobe/developer.adobe.com/blob/master/helix-config.yaml#L19-L24). Finally, all of our strains inherit from `basestrain` - but the "local" strains override `url` and set it to `http://localhost:3000` (sometimes with an additional path in the URL).

Just want to be sure I'm doing the right thing 😄

**Comment by filmaj** [comment]
Actually, thinking about this some more, we need to use `url` for the local strains as some strains are mounted on specific URL paths. If I drop `url` from the local strain configs then we lose that mounting ability locally.

**Comment by tripodsan** [comment]
yes, that is correct. but the `code` property influences on what is deployed. having it point to the `http://localhost/local/default.git` prevents the strain from being touched by the deployment.

you can still use the `url` to select the strain during local development

**Comment by filmaj** [comment]
> having [`code`] point to the `http://localhost/local/default.git` prevents the strain from being touched by the deployment.

Got it!

So the strains that we have set up for local deployment won't be published anymore, perfect.

The change we need to make on the site, then, is to set up the helix-demo.xyz strains not to use `http://localhost/local/default.git` code, content or static properties, but instead point to the remote repo. I think that was the issue I was having.

Thank you for talking this through with me!
