### ISSUE TITLE
hlx build and up failing on windows environment

### ISSUE THREAD

**Issue by srajagop** [adobe/helix-cli#520]
**Description**
hlx build and up commands are not working properly in windows environment

**To Reproduce**
1. Set up a demo project by running hlx demo hlx-sample
2. cd into hlx-sample
2. run hlx up
3. You will notice an error .html.pre.js no such file or directory

**Expected behavior**
Build successfully without throwing any errors

**Screenshots**
![helix](https://user-images.githubusercontent.com/11360377/52615810-7e58f800-2ebc-11e9-87fe-c4063301d98f.PNG)

**Version:**
0.13.2

**Comment by rofe** [comment]
It looks like you are trying to run `hlx build` in your home dir. Is `sample` the project name you provided to `hlx demo` (guessing from your step 1 above)? If yes, you need to `cd sample` (or whatever name you chose) before running `hlx build`.

**Comment by srajagop** [comment]
@rofe  I updated my steps. the demo project name was myaccount.

**Comment by tripodsan** [comment]
most probably a problem due to path separator `/` vs `\`. I can take a look at it.

**Comment by tripodsan** [comment]
yup; generated code is wrong:

```js
  const { OpenWhiskAction } = require('@adobe/helix-pipeline');
  const { pipe } = require('@adobe/helix-pipeline/src/defaults/html.pipe.js');
  const { pre } = require('.\html.pre.js');
```
