### ISSUE TITLE
Implement `hlx auth --github`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#579]
**Description**
there should be a simple way to retrieve the credentials that are required for depoyment from the various backends (see https://github.com/adobe/helix-cli/issues/380#issuecomment-448728876)

this issue is about adding `hlx auth --github` which will initiate the authentication process with github for the user to generate a token as `helix bot`. see https://github.com/adobe/helix-bot/issues/33 for details.

**Comment by tripodsan** [comment]
### example output:

```
$ hlx auth --github

Thank you for choosing the automatic Helix Bot Authentication process.
We will shortly open a browser with the following url. In case the browser doesn't
open automatically, please navigate to the url manually:

   https://app.project-helix.io/login/start?p=1234.

Oh, and I started local server, bound to 127.0.0.1:1234 and am awaiting the completion 
of the process.

<<spinner spinning>>

The authentication process has completed. Thank you. 
I received an access token that I can use to access the Helix Bot on your behalf. If you wish

I can add it automatically to a file [Y/n]: ?
which file: [.env]: ?

ok. I added it to `.env`.

----< or >-----
ok. here's the token for you:
HLX_GITHUB_TOKEN=fsdfgsdfgsdfgdsfgdsfg

You can now close the browser window if it didn't close automatically.
```

**Comment by tripodsan** [comment]
would need https://github.com/adobe/helix-cli/issues/580

**Comment by trieloff** [comment]
Sounds good. When you ask the "should I save this stuff" question, check first that this is an interactive (TTY) environment.

**Comment by tripodsan** [comment]
> ...check first that this is an interactive (TTY) environment.

I think that the entire interactive `hlx auth` should only work on a TTY.
