### ISSUE TITLE
Use `dotenv` and promote the use of a `.env` file.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#580]
using https://www.npmjs.com/package/dotenv 

we could:
- automatically load `.env` to populate the environment variables
- use it as default config when adding values through automation (after user confirmation)

additionally we should
- ensure that `.env` is in `.gitignore` (add it to demo setup, warn user if not)

**Comment by tripodsan** [comment]
@rofe are you looking into this now?

**Comment by rofe** [comment]
@tripodsan Haven't started yet, but I can give it a shot

**Comment by tripodsan** [comment]
adding a message if the env file is not ignored:

```
$ hlx --version

Warning: Your .env file is currently not ignored by git.
This is typically not good because it might contain secrets
which should never be stored in the git repository.

0.13.6-pre.15
```
