### ISSUE TITLE
RSS/PubSubHubBub Support?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#581]
Disclaimer: I have a well-documented over-affection for RSS, so this idea, which sounds awesome in my head might be complete nonsense.

Since looking at the RSS feed implementation for the Adobe Dev Site (https://github.com/adobe/developer.adobe.com/issues/123) I've been wondering if we should have better support for RSS as a data source, including:

1. an RSS pipeline that fetches and parses an RSS feed
2. an RSS entry pipeline that fetches and parses an RSS feed and then returns the selected entry
3. an RSS bot that fetches RSS periodically (or gets pinged by PubSubHubBub) to invalidate everything depending on that feed
4. or an RSS bot that fetches RSS periodically and commits to a GitHub repo (so you won't need 1-3. because the default pipeline can handle it)

**Comment by rofe** [comment]
> 1. an RSS pipeline that fetches and parses an RSS feed

I can definitely see use cases for 1. This could probably piggy-back on the XML pipeline.

> 2. an RSS entry pipeline that fetches and parses an RSS feed and then returns the selected entry

My experience with feeds is definitely rusty, but I don't understand why we would need a separate pipeline for entries. Could you elaborate?

> 3. an RSS bot that fetches RSS periodically (or gets pinged by PubSubHubBub) to invalidate everything depending on that feed

What use case would this implement?

> 4. or an RSS bot that fetches RSS periodically and commits to a GitHub repo (so you won't need 1-3. because the default pipeline can handle it)

I think this would be very elegant!

**Comment by trieloff** [comment]
> My experience with feeds is definitely rusty, but I don't understand why we would need a separate pipeline for entries. Could you elaborate?

I imagine following way of using it:

1. the `feed_html` pipeline creates either a link or an `<esi:include>` for each entry that should get rendered
2. the `entry_html`pipeline will then be used to do the actual rendering of the entry, with access to things like `title`, `author`, `content` (as a DOM thingie like in the Markdown-based pipelines)

We'd use the entry ID as the key for the `entry_html` pipeline, so that an update to the feed won't change the cache status for any of the existing entries, it would simply add a link/include to a new entry that has not yet been processed.

> What use case would this [feed invalidating bot] implement?

Cache efficiency. Instead of having each feed and feed entry cached for a short period of time, just cache it forever and wait for the bot to clear the cache as needed.

**Comment by rofe** [comment]
> Cache efficiency. Instead of having each feed and feed entry cached for a short period of time, just cache it forever and wait for the bot to clear the cache as needed.

Sounds like a good idea. I assume the bot would check the feed's `<sy:update*>` and `<skip*>` etc settings to decide when to invalidate?

**Comment by trieloff** [comment]
You could just brute-force it: just create a hash of the feed and use that as the surrogate key for feed invalidation. As long as the pipeline and the bot calculate the same hash, only updates would actually change cache status.

**Comment by rofe** [comment]
I see. But the bot could still use (and respect) the feed's metadata to determine the frequency of coming back to recalculate the hash.

**Comment by trieloff** [comment]
That's right. And for feeds that support PubSubHubBub, the feed would actually ping the bot once there are updates.
