### ISSUE TITLE
Default Continuous Delivery Pipeline

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#582]
Promoted by discussions on the Adobe Dev site https://github.com/adobe/developer.adobe.com/issues/128 and https://github.com/adobe/developer.adobe.com/pull/122 I wanted to gather my thoughts on enabling continuous deployment for Helix projects.

# Assumptions

1. CD should be the default, so that no project is going live without a good CD workflow
2. CD should be "batteries included", so that `hlx test` can be run to verify a local or remote deployment
3. CD should include performance testing (`hlx perf`)
4. CD should include functional testing (does the site look like I expect)
5. CD should fail fast, so that you get early feedback
6. CD should re-use, not re-invent (this is mostly about packaging)

### When running on a branch

1. `hlx build`
2. `hlx test --local` (run a test against a local simulated instance, shut down the instance after the test)
3. `hlx deploy` (deploys the current branch, updating `helix-config.yaml` in the process so that all strains that refer to the current branch get updated `package` properties pointing to the deployment
4. `hlx test --runtime` (calls each function directly in the runtime, i.e. without Fastly) to make sure that the deployment worked)
5. `hlx publish` (updates the strains so that the strains that cover the development branch are accessible from the web)
6. `hlx test --live` (runs tests against the live website, but enforcing the strain using the `X-Strain` cookie/header – it would automatically filter the strains so that only strains affected by the current branch are tested)
7. `hlx perf` (runs performance tests, again using the `X-Strain` cookie to circumvent strain resolution, and only considers affected strains)
8. `git commit -cm "[ci skip]" && git push` save the `helix-config.yaml` in Git, so that the deployment can be reproduced.

When all of this runs through, the commit will be marked in GitHub as ✅, permitting a merge into `master`.

### When running on master

1. `hlx build`
2. `hlx test --local` (run a test against a local simulated instance, shut down the instance after the test)
3. `hlx deploy` (deploys the current branch, updating `helix-config.yaml` in the process so that all strains that refer to the current branch get updated `package` properties pointing to the deployment
4. `hlx test --runtime` (calls each function directly in the runtime, i.e. without Fastly) to make sure that the deployment worked)
5. `hlx publish` (updates the strains so that the strains that cover the development branch are accessible from the web)
6. `hlx test --live` (runs tests against the live website, but enforcing the strain using the `X-Strain` cookie/header – it would automatically filter the strains so that only strains affected by the current branch are tested)
7. `hlx perf` (runs performance tests, again using the `X-Strain` cookie to circumvent strain resolution, and only considers affected strains)
8. `git commit -cm "[ci skip]" && git push` save the `helix-config.yaml` in Git, so that the deployment can be reproduced.

When this fails, re-trigger the build for the last known good commit on `master`, initiating an automatic rollback.

## Batteries included CD

Users should not need to install `mocha`, `calibre`, `webdriver`, etc. but all of that should be installed by default (or when first running `hlx test` in case the download is too big for an initial `npm install`).

All the user should need to specify are:

- `urls` for each strain that should be tested
- test fixtures describing the expected response
- (optionally) more advanced test scripts like [this](https://github.com/adobe/developer.adobe.com/pull/122/files#diff-a98e76b822807087274e8a6886febb97) that run in-browser and have assertions

## Performance Tests included

With `hlx perf` and Calibre, we have a good system of performance tests. Running them after the main functional test will ensure a more realistic warm cache.

## Functional Tests

Simple functional tests should simply compare the HTML returned from a URL with a fixture that supports wildcards (see https://github.com/adobe/helix-shared/pull/53)

More advanced functional tests should use https://webdriver.io or something similar and allow the user to specify test assertions that are run in the browser

## Fail Fast

The shortest tests should run first, more complex tests later, so that developers get feedback as quickly as possible and so that the risk of a known bad deployment is minimized.

## Re-Use, Don't Re-Invent

Use Webdriver, Selenium, Calibre, etc. instead of re-building the basics.

**Comment by kptdobe** [comment]
As being discussed in #142, the e2e tests cannot rely on the content from a repo in which the content can change, or at least they must be written in a way that the test does not fail if the content changes (valid change). This is maybe what https://github.com/adobe/helix-shared/pull/53 is supposed to support but in any case, it is a tricky piece that needs to be clarified.

**Comment by kptdobe** [comment]
After brainstorming session with @rofe and @basecode, we came up with a list of tests that should run during the process - tentatively trying to summarise, feel free to add if something is missing:
* development phase
  * developer tests
    * unit tests of the `pre.js` code - customer owned
    * unit tests of any project code - customer owned
  * integration tests
    * smoke tests (is there something in the page, 404 - like for static ressources)
    * e2e tests (render real content and validate some expected behaviours - but must be content 
agnostic) - customer owned
    * snapshot tests (render some test content and compare output with known expected output) - customer owned
* CI / CD phase - branch
  * `hlx test --local` would run the full suite
  * `hlx test --runtime` would run the integration tests against the runtime only
  * `hlx test --live` would run the integration tests against the live site
* CI / CD phase - master
  * `hlx test --local` would run the full suite
  * `hlx test --runtime` would run the integration tests against the runtime only
  * `hlx test --live` would run the integration tests against the live site

Another set of tests could be introduced - snapshot tests in between environments: 
* using the production content
  * render a page with the dev environment (hlx up)
  * compare the result with the runtime rendering of the same page (call to runtime)
  * compare the result with the live rendering of the same page (call to live site)
* +/- some environment specific differences (like the urls), the rendering must be the same.
* this would illustrate some environment differences and could be bidirectional:
  * -> works fine in dev but not in production
 * <- Fastly adds a header we do not have on the dev environment (might be fine... or not but to be sorted out)

**Comment by trieloff** [comment]
I like the dev-live-diff test.

**Comment by filmaj** [comment]
Correct me if I'm wrong but I don't see any difference between the steps outlined for a branch vs. master deployment. If that's correct, could we condense this down to a single set of steps, then?

**Comment by trieloff** [comment]
The difference is the automatic rollback for `master` and the status check for branches.

**Comment by trieloff** [comment]
I think we should consider using GitHub Actions as the default CI for Helix customers.
- it will make integration easier
- one less service to support
- we don't need the more advanced CircleCI features for our customer builds
- I don't want to expose our customers to CircleCI support

**Comment by trieloff** [comment]
After circling back with CircleCI (😄) it seems GitHub Actions is indeed the better option as we won't be able to implement the login-less experience with CircleCI.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
