### ISSUE TITLE
Feature: Redirect Management

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#587]
Putting this into `helix-cli`, although the suggested implementation would touch `helix-shared`, and `helix-publish`, too.

Any non-trivial site will have to handle redirects when URLs change (e.g. https://github.com/adobe/developer.adobe.com/issues/140), which in my experience is done through shared Excel or Google docs files that are edited collaboratively.

My proposal to handle redirects in Helix is thus:

1. in `helix-config.yaml`, each Strain gets a `redirects` property
2. `redirects` can point to a file name, relative to the location of `helix-config.yaml` or to a URL
3. if it is a file name ending with `.csv` or `.tsv`, it will be parsed as CSV or TSV
4. if its a a URL, Helix will attempt to retrieve the JSON representation of a publicly shared Google sheet like this: https://spreadsheets.google.com/feeds/list/15PR3EZClNJWwv1FfqVHluJv0OvkwKWoXBnE6LwUxkCQ/od6/public/values

The rough format is like this:

| From (first column)                    | To (second column)                     | Comments (all other columns) |   |
| -------------------------------------- | -------------------------------------- | ---------------------------- | - |
| https://team.project-helix.io          | https://www.project-helix.io/team.html | All comments are ignored     |   |
| https://www.project-helix.io/home.html | https://www.project-helix.io/          | All URLs must be absolute    |   |
|                                        |                                        | empty lines are ignored      |   |

## Notes

- all URLs must be absolute to keep things simple
- no wildcards or patterns and no pattern replacements are allowed
- redirects are conditional on a strain, but can be shared between strains using YAML references

## Implementation

- `helix-shared` implements the parsing of redirect files and returns a map of redirects (post-parsed) on `strain.redirects` with `from` being the key and `to` the value
- `helix-cli` sends the maps of redirects to `helix-publish`
- `helix-publish` uses the new methods in `fastly-native-promises` to create conditional redirects: https://github.com/adobe/fastly-native-promises/issues/35 and https://github.com/adobe/fastly-native-promises/issues/34

**Comment by trieloff** [comment]
@kgera would this work for you?

**Comment by rofe** [comment]
Sounds like a great thing to have.

How about adding conditions to the format? I could imagine customers want to define redirects which are only "active" between a `from` and `to` date/time, or only on Saturdays and Sundays, or...

**Comment by trieloff** [comment]
> I could imagine customers want to define redirects which are only "active" between a `from` and `to` date/time, or only on Saturdays and Sundays, or...

Could conditions on the strain satisfy your use case?

**Comment by kptdobe** [comment]
There are multiple ways to automate the process of exporting a Google spreadsheet into Git. I would not build 4. in Helix, only 1, 2 and 3 (trusting your "in my experience is done through shared Excel", otherwise I would have keep it yaml ;))

**Comment by trieloff** [comment]
I'm fine with dropping number 4, especially looking at the volatility of the Google Sheets API (I had to try three different URLs, each from different phases to get my spreadsheet's JSON). If @davidnuescheler really wants Google Sheets, we can add them later.

**Comment by kptdobe** [comment]
Add later when really needed is a good strategy ;)

**Comment by kgera** [comment]
@trieloff As mentioned in https://github.com/adobe/developer.adobe.com/issues/140#issuecomment-468168262 it would be good to have pattern support too , we can live with the redirect scope definition in excel for for developer website for example until we have the dispatcher but longer term when we move to helix completely it will be needed.

**Comment by trieloff** [comment]
@kgera we won't be able to help with anything after the `#`, as that's never sent to the server.

**Comment by tripodsan** [comment]
> 
@kgera we won't be able to help with anything after the `#`, as that's never sent to the server
.

we could have a special redirect action for this using a javascript redirect. could probably even be responded by fastly.

**Comment by tripodsan** [comment]
**What about versioning?**

**Q**: _Who_ is usually the author/manger of the redirects?
**A**: _ think, it's the website manager or marketing manager ... _

**Q**: Are redirects code or content? I.e. Depend the redirect on code or content? 
**A**: _Content. Since content needs to be there before you can redirect to it._

**Q**: Do redirects need to be updated independent of code and content?
**A**: _Yes._

**Q**: Do we want to test and stage redirects?
**A**: _Yes._

Based on this I think that:
- having a redirect file in the code repo is not really useful. then I'd rather have them as plain string the the `helix-config.yaml`. 
- referencing a (versioned) URL from the config as described is the best approach.
- true code independence can be achieved using a separate config repository (we anyways need to look into how to do this).

**Comment by trieloff** [comment]
> Q: Who is usually the author/manger of the redirects?

Depends. We will have developer-initiated redirects, and author-initiated redirects.

> Q: Are redirects code or content? I.e. Depend the redirect on code or content?

There are both. Moving a file or subtree in the UI is a "content" redirect. Adding a selector to a URL to mapping legacy URLs is a "code" redirect.

> Q: Do redirects need to be updated independent of code and content?
> A: Yes.
>
> Q: Do we want to test and stage redirects?
> A: Yes.

Agree.

**Comment by trieloff** [comment]
This duality could also help with the pattern problem: enable patterns only for "code" redirects (which can be specified inside the YAML file) – and have a `redirects.csv` in the content for "content" redirects.

Turning "code" redirects into Fastly conditions is relatively easy, and can be done during `hlx publish`. I'm wondering what would be a good way to handle "content" redirects:
1. push them to Fastly (but that requires access to Fastly, which we don't always have during content updates)
2. have a `redirects` action and pipeline that is used as a (cached) preflight request from Fastly (with the added overhead for every request)

**Comment by ejthurgo** [comment]
What's the rationale around not allowing patterns in redirects?
This is a super-useful feature and most often allows you to significantly reduce the number of conditions.

Is your intention to perhaps store in an edge dictionary? this would place a limitation on it being a basic key lookup.

If you require versioning, perhaps build the edge dictionary into the VCL, or if you decide to go down a patterns route, a bunch of if-elsif, whilst be cumbersome, would satisfy the requirement.

Are there any other attributes you might want to store with the location? maybe give users the option of the 30X code?

**Comment by trieloff** [comment]
> What's the rationale around not allowing patterns in redirects?
This is a super-useful feature and most often allows you to significantly reduce the number of conditions.

* I don't trust authors who would edit simple Excel files to write proper patterns (different story for developers)
* I'm lazy

But, it looks like we must have patterns anyway, so the question is more about who can configure them how.

> Are there any other attributes you might want to store with the location? maybe give users the option of the 30X code?

For developers yes, for authors, no (see above - the point about complexity, not about me being lazy)

**Comment by ejthurgo** [comment]
> I don't trust authors who would edit simple Excel files to write proper patterns
Fair.

**Comment by trieloff** [comment]
One idea: have the "code" redirects (with patterns, etc) be handled entirely on Fastly, through statically compiled rules. Have "content" redirects be handled as a fallback on 404 (after regular pipeline falls through and after static pipeline falls through).

That would reduce the number of requests to the "content redirect" action massively (because it only gets called on 404s) and it would prevent accidental overlaying of new content.

**Comment by trieloff** [comment]
Yep, I want to have a workflow that is easy for Excel-jockeys.

**Comment by kptdobe** [comment]
@trieloff Please document :)

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
