### ISSUE TITLE
Investigate how to separate code and config

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#605]
Independence of code, content and config is important for proper versioning of the three.

A typical setup would have at least 3 repositories. one for _config_, one for _code_, and one for _content_.

### deploy workflow
- `hlx deploy` would trigger a deploy workflow, taking a `config-repo-url` and a `code-repo-url` as parameter. of course the `config-repo-url` could be a branch part of a pull request.
- the workflow would checkout the _config repo_ and understand the `helix-config.yaml` (or just fetch that file)
- the workflow then checks if the mentioned `code-repo-url` is covered by any strain. if not, abort
- then a normal `hlx build && hlx deploy` is perfomed, deploying the actions and updating (`package` properties) the `helix-config.yaml`
- the updated `helix-config.yaml` is comitted back to the `config-repo-url`

### publish workflow
- `hlx publish` would trigger a publish workflow, taking a taking a `config-repo-url` as parameter.
- the workflow would checkout the _config repo_ and understand the `helix-config.yaml` (or just fetch that file)
- a normal `hlx publish` is performed using the config.

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
