### ISSUE TITLE
Trim down size of binary hlx distribution

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#613]
**Description**
The size of the binary `hlx` distribution went from **37.4mb**  (v0.13.4) to **79.9mb** (v0.13.6), i.e. it more than doubled.

**To Reproduce**
Go to the respective Releases and compare the sizes of the `hlx_install.sh` asset:
- [v0.13.4](https://github.com/adobe/helix-cli/releases/tag/v0.13.4)
- [v0.13.6](https://github.com/adobe/helix-cli/releases/tag/v0.13.6)

**Expected behavior**
The size of `hlx_install.sh` should stay reasonably small (e.g. <50mb).

**Version:**
v0.13.6

**Comment by trieloff** [comment]
This sounds like a great scenario to use `git bisect`. I fear we have added a dependency downstream that should be a dev dependency.

**Comment by stefan-guggisberg** [comment]
I've identified the following 2 changes as the main culprits for the massive increase in size:

* `calibre` update from `1.1.1` to `1.2.0` a66bebd

    This update results in **79mb** increase in disk footprint! That's because the published `1.2.0` npm module includes a `bin` directory with binary calibre builds for mac, linux and windows ... :-(

* `+ test/fixtures/recordings` adds another **15mb** 5247c5c

@trieloff Can we downgrade `calibre` to `1.1.1`?

**Comment by trieloff** [comment]
Yes, we don't need the upgrade and will move away from having calibre included with `helix-perf`

**Comment by trieloff** [comment]
The test recordings should get excluded from the npm and installer package, too.

**Comment by stefan-guggisberg** [comment]
> The test recordings should get excluded from the npm and installer package, too.

The `test` folder is already excluded from the npm package via `.npmignore`. I'll look into excluding it from the installer package.

**Comment by stefan-guggisberg** [comment]
argh! now snyk complains: #613

I guess we could live with the reported snyk issue, especially if we're going to remove calibre anyway.

@trieloff WDYT?

**Comment by trieloff** [comment]
I think we are fine with this right now.

**Comment by stefan-guggisberg** [comment]
fixed in 7552245 (`hlx_install.sh` is down to 36.8mb)
