### ISSUE TITLE
[hlx deploy] fails if project contains a submodule

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#614]
**Description**
It seems that having a submodule in the project triggers an exception during `hlx deploy`.

**To Reproduce**
1. `git clone git@github.com:adobe/project-helix.io.git`
2. `cd project-helix.io`
3. `hlx build`
4. `hlx deploy --wsk-auth <your_wsk_auth_token> --wsk-namespace <your_wsk_namespace>`

Following error appears and stop the process: `Failed to read git object with oid ce24eb86a33320577f1b66498629f21d22cda703` 

**Version:**
run: `$ hlx --version`
0.13.7-pre.0

**Additional context**
Some initial debugging with @stefan-guggisberg reveals that the `isDirty` check is the entry point. Then it seems that `isomorphic-git` does not co-op with submodules (getting git info on `subdomains/helix-cli` folder seems to be the trigger of the error)

**Comment by stefan-guggisberg** [comment]
This is a regression of #523 (replace `shelljs` `git` command line calls with `isomorphic-git` implementation).

I've created an `isomorphic-git` issue: https://github.com/isomorphic-git/isomorphic-git/issues/707

**Comment by stefan-guggisberg** [comment]
fixed in fcdc5726461bb0ed484a255b3657cdda97b95f11

**Comment by tripodsan** [comment]
Thanks for the fix, @stefan-guggisberg, but I'm not sure if it is 100% correct. AFAICS, the check now excludes the submodules completely. so if you have a modified file in the submodule path, then `isDirty` is still wrong. I'll create a new issue for this.

**Comment by stefan-guggisberg** [comment]
are submodules packaged? if yes i agree that dirty submodules should be considered.
