### ISSUE TITLE
Static Assets are not cached in the browser long enough

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#634]
<img width="1234" alt="Screen Shot 2019-03-12 at 17 38 53" src="https://user-images.githubusercontent.com/39613/54218650-3f838580-44ee-11e9-83dd-90893db803cc.png">

```http
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 0
Cache-Control: s-max-age=300
Connection: keep-alive
Content-Length: 485816
Content-Type: text/css; charset=UTF-8
Date: Tue, 12 Mar 2019 16:42:57 GMT
ETag: "m8V1d507R5rwuGlNzaq3Ug=="
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: X-Debug, X-Strain
X-Version: 52; src=47; cli=0.13.6-pre.8; rev=dcdd7f967604e00f1c1882d4cf8727476f720288
```

The Cache-Control header is missing a private cache setting, so that the browser will cache it.

**Comment by trieloff** [comment]
Ideally, we would have really static URLs for all assets, but this means re-inviting the parcel magic that we have thrown out earlier.

**Comment by rofe** [comment]
Is this issue still relevant now that we added shas to the static URLs?

**Comment by trieloff** [comment]
Can be closed.
