### ISSUE TITLE
Allow specifying remote publish service URL

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#647]
For `hlx publish --remote`, we should change `--remote` from a boolean flag to a string flag, with the string indicating the URL of the publishing microservice. This would allow us to do smoke tests of the `helix-publish` micro service.

**Comment by tripodsan** [comment]
what about an env variable?

`HLX_API_PUBLISH=https://adobeioruntime.net/api/v1/web/helix/helix-publish@1.0.1`
