### ISSUE TITLE
The curious case of HTTP 200/OK {}

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#648]
While working on #645 (i.e. adobe/helix-pipeline#209 and adobe/developer.adobe.com-planning#183) I've been looking into the "HTTP 200/OK {}" issue most of us have seen:

- it occurs only in Runtime
- HTTP status is 200, even when things are decidedly **not OK**
- `wsk activation logs` is empty
- even when requesting with `X-Debug: silly`, the logs are super sparse like this:
```
2019-03-14T22:29:49.377Z       stdout: debug: Constructing HTML Pipeline
2019-03-14T22:29:49.377Z       stdout: debug: Creating pipeline
2019-03-14T22:29:49.379Z       stdout: debug: initializing ajv {"useDefaults":true,"coerceTypes":true}
2019-03-14T22:29:49.383Z       stdout: debug: error {"error":{},"request":"92d5b4d8-97ee-465d-a650-aa37f8b34f09","activation":"5d5c5f195c0a457f9c5f195c0aa57f47","function":"html"}
```
- the response is an empty JSON object `{}` (the `Content-Type` is JSON, too)

The error happens when there is a sufficiently hard exception in the *construction* of the pipeline, i.e. when a `require` can't be satisfied as in #645 or when a critical environment variable can't be read as in https://github.com/adobe/helix-pipeline/issues/142. As this happens before the pipeline can be run, the normal error handling of the pipeline never takes.

I've done a bit of (ultimately ineffective) digging around in the `OutputWrapper` to add a `try/catch` block that would return a proper error 500 (and log what it can get), but this wasn't effective. 

I'd be glad for another pair of eyes on the problem.

**Comment by filmaj** [comment]
I don't have much to add about how to address the issue, but figured my experience with this bug may prove useful perspective.

The HTTP status code tripped me up with this at first. I had to tweak the monitoring for the site (via pingdom) to not just look at status code, but also search for specific content on the site (in our case, we look for 'adobe' somewhere on the site).

We are also planning on adding a verification step to our CD pipeline, between when `hlx deploy` and `hlx publish` execute, to ensure that runtime is returning the right output.

So: ultimately, the devsite team is proactively attempting to guard against this issue. Would be nice to see helix do so instead 😉

**Comment by filmaj** [comment]
This came up again in https://github.com/adobe/developer.adobe.com-planning/issues/188

I ended up manually wrapping some `try/catch` blocks around HTML pipeline creation to get more logs. Looks like the wrong `ajv` was packaged (5.5.2 was packaged, need 6.0.0+ to support latest json schema, 6.6.2 is defined in helix-pipeline's package.json). More details in https://github.com/adobe/developer.adobe.com-planning/issues/188

**Comment by stefan-guggisberg** [comment]
related issues:
*  https://github.com/adobe/helix-pipeline/issues/142
*  https://github.com/adobe/helix-pipeline/issues/209
* https://github.com/adobe/helix-cli/issues/408
* https://github.com/adobe/developer.adobe.com-planning/issues/183
* https://github.com/adobe/developer.adobe.com-planning/issues/188

**Comment by stefan-guggisberg** [comment]
I've identified the following 2 issues:

- https://github.com/adobe/helix-pipeline/issues/237
- https://github.com/adobe/openwhisk-loggly-wrapper/issues/18
