### ISSUE TITLE
`hlx up` does not reload changes of local JS required files

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#684]
**Description**
If you `require` a local JS file from a `pre.js`, the changes in that local JS file will not be reloaded after a change, even though `hlx up` says it has rebuilt the project files.

**To Reproduce**
1. `hlx demo test`
2. `cd test/src`
3. Create a `util.js` file with content (completely arbitrary):

```
module.exports.log = function(msg) {
    console.log(`LOG: ${msg}`);
};
```

4. Edit `html.pre.js`: 

```
const util = require('./util');

function pre(payload) {
  util.log('Hello world');
}

module.exports.pre = pre;
```

5. Run `hlx up`
6. See the terminal log output: `LOG: Hello world`
7. Edit `util.js` and change the log output:

```
    console.log(`This is a nicer log prefix: ${msg}`);
```

8. Save and see the terminal log output: `Rebuilding project files...done Xms` (changes have been detected
9. Reload the page

-> See the terminal log output: `LOG: Hello world`. It should be `This is a nicer log prefix: Hello world`.

The only way to get the latest modification is to restart `hlx up`!

**Expected behavior**
Changes are reloaded.

**Version:**
run: `$ hlx --version`
v0.13.11-pre.10

**Comment by tripodsan** [comment]
should be possible to easily delete all modified modules from the resolver cache.
