### ISSUE TITLE
Health Check Action

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#685]
This is inspired by the discussion in https://github.com/adobe/project-helix.io/issues/43 (how to disambiguate between file names that look like selector and actual selectors) and @kptdobe's comments, but it would also contribute to #383

For every deployment, we add a `helix--health` action in the same package. That action will:

- try to call every other action in the same package with some debug options
- return a status report that is compatible with the https://help.pingdom.com/hc/en-us/articles/115000431709-HTTP-Custom-Check
- return a header that lists all valid selector names

We can then call this `helix--health` action from `helix-publish` to determine what the list of valid selector is. Best of all, we have two options: we can use it as a heavily cached pre-flight request or run it when we generate the VCL, resulting in hardcoded selectors (per package).

As an additional feature, we could include the previous value of `package` in the return values. In case the health check fails, this would point to a possible rollback state (without actually having to roll back)

**Comment by trieloff** [comment]
From @kptdobe 
> That was my initial proposal: generate a list in `dynamic.vcl` (or a dedicated file for that). If selector in the list, use as template, otherwise append to content path. Something like that ;)

In order to do this, `helix-publish` would need to have access to the source code repository. I'd like to keep the coupling low, and the health check action might be able to provide this.

**Comment by tripodsan** [comment]
I still think we should create 1 action that handles all templates :-), this action could also be used to report the list of supported selectors and extension.

for the current state, the list of actions of a package describes the set of `selector.extension` tuples it support. so `helix-publish` could use the wsk api directly for fetch this. this would also solve #373.

in any case, abstracting this away in a `helix--health` action might be the most flexible and future proof.

als a first step, we can just include the list of files (manifest) during package time.

**Comment by trieloff** [comment]
I thought that a disadvantage of using the OpenWhisk API in `helix-publish` would be that we need to pass an additional set of credentials to it to access the actions, but I realize we do this anyway.

I agree, starting with the manifest might be the best way to start.

**Comment by rofe** [comment]
I think this is implemented with https://github.com/adobe/helix-pingdom-status.
