### ISSUE TITLE
[hlx deploy] Use an `.env` file to specify environment variables

### ISSUE THREAD

**Issue by dplaton** [adobe/helix-cli#686]
I always have to `export` the `HLX_CIRCLECI_AUTH` or `HLX_WSK_AUTH` variables before deploying.

I should be able to have my environment variables specified in a `.env` file and I can pass this to `hlx deploy`.

**Comment by trieloff** [comment]
We should have support for `.env` files: #580, but I haven't tried this yet (I'm more a "copy and paste the `exports` from 1Password"-kind-of-guy).

If you run into issues with this, feel free to turn this into a bug.

**Comment by dplaton** [comment]
@trieloff You're right, this works. I was expecting a flag to feed the environment file to `hlx` (some developer prefer other names for this file) and I wasn't aware that it "just works".
A documentation update would be nice, I'll file a PR for the docs.

Thanks!
