### ISSUE TITLE
Master Build is Broken

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#693]
It looks like https://github.com/adobe/helix-cli/commit/1e5c9613cbd2aecc3c1f78f4025fdd80485b5f64 broke the build: https://circleci.com/gh/adobe/helix-cli/5966

* Integration test for up command up command delivers modified sources and delivers correct response. - up command delivers modified sources and delivers correct response.

```
AssertionError [ERR_ASSERTION]: '{"body":"---\\ntemplate: homepage\\n---\\n\\n# Soup Demo Test\\n\\nThis is rendered using ~~Sightly~~ HTL.\\n\\n> [!NOTE]\\n> T == '{"body":"---\\ntemplate: homepage\\n---\\n\\n# Soup Demo Test\\n\\nThis is rendered using ~~Sightly~~ HTL.","meta":{"template":
    at IncomingMessage.res.on.on (test/utils.js:83:24)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by kptdobe** [comment]
Interesting.. should be something else because tests were green in the branch (https://circleci.com/gh/adobe/helix-cli/tree/test_json_renderer) and commit just adds another tests. 
Just the unlucky guy who merged at the wrong time ;)

**Comment by kptdobe** [comment]
The failing test runs on my box individually.

**Comment by kptdobe** [comment]
arff no, now it does not. so weird!

**Comment by kptdobe** [comment]
Ah ah... the chances that @trieloff changed the `index.md` of the tests right before we merged my PR was really low. But we did it! Easy fix.

**Comment by kptdobe** [comment]
Should be back to normal.
