### ISSUE TITLE
Retire binary hlx distribution

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#696]
## Overview
Recent binary `hlx` releases are all broken. The last know to work release is `v0.13.8`. See related issues:

* #654
* #657 
* #687 
* #689

## Details
The binary `hlx` executable is build using [node-packer](https://github.com/pmq20/node-packer). `node-packer` embeds `Node 8.3` runtime within the native executable.  

As of #397 (0528466) `Node >=8.9` is required to run the CLI.

OTOH the `node-packer` project is abandoned, the current release is 2 years old (bundling `Node 8.3` runtime). I forked the [project](https://github.com/adobe/node-packer) and ported the runtime to `8.15` and `10.15`, only to run into new issues (e.g. #687, #689, failure to load native addons, etc). There are potentially a lot more issues. Fixing those issues would require a deep dive into v8, libuv, libsquash and Node core C/C++ code, hardly worth the effort.

While there are other projects which create native executables from node apps (`pkg`, `enclose`, `nexe`, `electron` etc) none of them work for `helix-cli` (lack of native addon support, no dynamic requires, etc).

## Proposed Actions
I suggest we stop providing binary `hlx` builds, at least until we find a viable solution.
This would mean we remove any reference from READMEs, docs etc and remove the build job on CircleCi.

**Comment by stefan-guggisberg** [comment]
resolved according to proposal

**Comment by tripodsan** [comment]
@stefan-guggisberg I think this file is no longer needed:
https://github.com/adobe/helix-cli/blob/master/cli_install.sh

**Comment by stefan-guggisberg** [comment]
fixed in de2c914
