### ISSUE TITLE
Document available HLX_* environment variables

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#698]
**Description**
There are a number of `HLX_*` environment variables which can be used in conjunction with the Helix CLI. Some are more self-explanatory than others, but none of them are documented in more detail yet.

#### the relevant arguments for `hlx publish` are:

`HLX_WSK_NAMESPACE`
`HLX_WSK_AUTH`
`HLX_WSK_HOST`
`HLX_FASTLY_AUTH`
`HLX_FASTLY_NAMESPACE`

less useful:
`HLX_REMOTE`
`HLX_API_PUBLISH`

#### the relevant arguments for `hlx deploy` are:

`HLX_WSK_NAMESPACE`
`HLX_WSK_AUTH`
`HLX_WSK_HOST`
`HLX_LOGGLY_AUTH`
`HLX_LOGGLY_HOST`
`HLX_FASTLY_AUTH`
`HLX_FASTLY_NAMESPACE`
`HLX_CIRCLECI_AUTH`

less useful:
`HLX_TARGET`
`HLX_PACKAGE`

**Expectation**
Each variable should have a short description and explain if they are mandated by a `hlx` action or optional, etc.

**Version:**
v0.13.13-pre.2

**Additional context**
See https://github.com/adobe/helix-home/pull/4

**Comment by tripodsan** [comment]
please note that they are all derived from the `hlx ` cli arguments. so it would be important to explain them together. ie the argument is the primary requirement, the fallback to an env variable just a fallback.

**Comment by tripodsan** [comment]
list of all variables: https://github.com/adobe/helix-cli/blob/master/test/fixtures/all.env

**Comment by kptdobe** [comment]
@MarquiseRosier would you mind taking a look at this one ?
