### ISSUE TITLE
Improve Developer Experience for people new to Helix

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#711]
**Is your feature request related to a problem? Please describe.**

The currently available documentation is scattered over several projects, inconsistent and in some areas scarce to non-existent.

Creating a new project and deploying/publishing it is an error prone frustrating process. 

A developer new to Helix will need expert help, explaining cryptic error messages, confusing CLI output, non-intuitive configuration options etc.

**Describe the solution you'd like**

There should be a one stop url for all Helix related documentation, linking/consolidating all existing documentation.

There should be a short concise tutorial guiding through the process of building, deploying and publishing a first Helix project.

The Helix CLI should provide reasonable defaults, meaningful & consistent output and error messages for inexperienced users.

A Developer new to Helix should be able to successfully finish the tutorial without any need for external help.

**Comment by trieloff** [comment]
See also: https://github.com/adobe/helix-home/commit/9d6a5f7c22ffec22ddb2b299c90e24d886a64d59#diff-2dd1a9fb276aebde38ff6ad8d4fdbd5b

**Comment by rofe** [comment]
Let's tackle this in https://github.com/adobe/helix-pages/issues/995 for Helix 3.
