### ISSUE TITLE
helix-static bundle includes entire helix-cli

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#730]
(This is likely very much related to #589, but maybe it can also be looked at in isolation)

## Overview
Surprised by the size of the static.zip (12MB), I looked inside and was surprised to find the entire `helix-cli` module directory in there, taking up about 2/3 of the file size... is there a specific reason for that?

## Details
The remaining 1/3 is used by 48 additional dependencies.

## Proposed Actions
Maybe the list of bundled modules could be reduced to "just" the 3 modules actually used by the [static.js](src/openwhisk/static.js) (and their transient dependencies)?
- `request-promise-native`
- `crypto`
- `mime-types`

**Comment by tripodsan** [comment]
that is actually a very good question :-)
