### ISSUE TITLE
consistently use `context` instead of payload.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#743]
we should use `context` consistently throughout all code, code examples and documentation and not mention `payload` anymore.

**Comment by filmaj** [comment]
So based on this, I tried updating all references to `payload` in devsite over to `context`. However, the build for that PR failed: https://github.com/adobe/developer.adobe.com/pull/74 with the error:

```
[hlx] error: tapping failed: ReferenceError: context is not defined
    at /home/circleci/project/.hlx/build/html.js:53:28
    at Generator.next (<anonymous>)
    at onFulfilled (/home/circleci/project/node_modules/co/index.js:65:19)
    at /home/circleci/project/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/home/circleci/project/node_modules/co/index.js:50:10)
    at Runtime.run (/home/circleci/project/node_modules/@adobe/htlengine/src/runtime/Runtime.js:47:12)
    at run (/home/circleci/project/.hlx/build/html.js:45:18)
    at main (/home/circleci/project/.hlx/build/html.js:73:9)
    at invoker (/home/circleci/project/.hlx/build/html.js:103:32)
```

Looks like the hlx-built `html.js` uses hard-coded reference to `payload`, so I think that means at least the `.htl` files must continue to use `payload` for now.

**Comment by tripodsan** [comment]
right: https://github.com/adobe/parcel-plugin-htl/blob/v2.1.1/src/HTLAsset.js#L35

hmmm... 🤷‍♂️

**Comment by rofe** [comment]
What's wrong with `payload`?

**Comment by tripodsan** [comment]
> What's wrong with `payload`?

well... I can't remember the exact argument, but from the pov of the pipeline, it looks a bit weird to have a `payload` shoved around, since it doesn't really contain any load from the original request.

so it was renamed to `context` and now documented as such:
https://github.com/adobe/helix-pipeline/blob/master/docs/context.schema.md

**Comment by rofe** [comment]
Gotcha, thanks!
