### ISSUE TITLE
not possible to set response headers in `pre.js`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#744]
**Description**
trying to set response headers in `pre.js` doesn't work, because it always overwrites the `response` object inside the `context. altering other properties of the `context` works.

the merging / response handling of pipeline steps is discussed here:
https://github.com/adobe/helix-pipeline/issues/223

**Additional context**
It is not yet clear if this is the intended behaviour, as the `pre.js` should probably not alter response headers directly. 

in any case, the proper approach is to use an extension:

```
// html.pre.js
...
module.exports.after = {
  html: (context) => {
    return {
      response: {
        headers: {
          'Cache-Control': 'private',
        }
      }
    };
  }
};
```

(we should probably expose the `cache` step as extension, or even better have an `emit` step.

**Comment by tripodsan** [comment]
### Open questions
1. should we change the behaviour and allow the `pre.js` alter the response object directly
2. so far we discard the 'context' passed from pre into the htlengine afterwards. fixing the above would mean, that added properties in the `context` would also be added back to the pipeline. the `context` is pretty tightly defined and doesn't allow for extra data. we should probably add a `data` object to the `context` (or `context.content`) in so that the `pre.js` can pass data to the scripts.
3. should we add more extension points, especially one to alter the final response would probably be helpful.
4. should pipeline merge ?

**Comment by filmaj** [comment]
I will try the `after` extension, thanks.

In case it is helpful, my use case is an RSS feed, and I want to have close control of the caching behaviour, so I need to control the cache headers in order to make fastly behave as I want to. I imagine this would be relatively common https://github.com/adobe/developer.adobe.com-planning/issues/123

**Comment by filmaj** [comment]
Question about this: what's the `html` portion of the `after` object determine?

**Comment by filmaj** [comment]
Also, does the response object in `after.html` get merged in with what `pre` returns? Do I have to, for example, return `context`'s `content` along with `response` in the `after.html` handler? Or can I return just the `response` in `after.html`, and just the `content` in `pre`?

**Comment by kptdobe** [comment]
Interesting discovery, indeed!

I think the need was always there:
- https://github.com/adobe/helix-pipeline/blob/master/src/html/set-status.js#L29-L30
- https://github.com/adobe/helix-pipeline/blob/master/src/utils/set-content-type.js#L15
- https://github.com/adobe/helix-pipeline/blob/master/src/html/set-surrogate-key.js#L16
- https://github.com/adobe/helix-pipeline/blob/master/src/html/shared-cache.js#L14

Most of the code executed after the `pre` function checks if some `header` or `status` has been set before. And the only way to set one of this property used to be the `pre.js`. 

Another argument pro: the method signature for all the pipeline function is the same: return a partial context which is merged into the main one. Why the `pre` should be different ?

Another aspect: under certain conditions, I can break the schema validation (simply use the `mdast-add-list-metadata` plugin on your sections), which means that I can change the context for certain existing properties.

**Comment by tripodsan** [comment]
> Also, does the response object in `after.html` get merged in with what `pre` returns? Do I have to, for example, return `context`'s `content` along with `response` in the `after.html` handler? Or can I return just the `response` in `after.html`, and just the `content` in `pre`?

the `before` and `after` handlers are _normal_ pipeline functions. i.e. the pipeline currently merges your return value with the existing `context`.

**Comment by tripodsan** [comment]
if we allow that that `pre.js` can alter the `context`, we need a better way to transporting values to the `htl`. currently, you can set pretty much anything in `context` and then use it in `payload.*` in the htl. if we would merge this back into the pipeline `context`, it would often not validate anymore. (my point **2** above)

**Comment by kptdobe** [comment]
Yes, agreed. 
We would need: 
1. execute the `pre` function
1. merge and validate the context
1. execute the htl runtime
1. merge and validate the context

This would be more aligned with the rest.

> if we allow that that `pre.js` can alter the `context`
For now, even though we do a merge, you can still modify the original object in each pipeline step without returning anything. Reminds me the long discussions on Redux for Screens and the alter or not the object!

**Comment by tripodsan** [comment]
> Reminds me the long discussions on Redux for Screens and the alter or not the object!

https://github.com/adobe/helix-pipeline/issues/228
