### ISSUE TITLE
Make context dump subdirectory names be more meaningful

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#748]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to debug strains that `esi:include` multiple pipelines, because the `logs/debug` directory names aren't meaningful. e.g.:

```
13:08:39 in developer.adobe.com/logs/debug on  rss-cache
➜ l
total 0
drwxr-xr-x   5 maj  staff   160B Apr 10 12:44 .
drwxr-xr-x   8 maj  staff   256B Dec 14 01:53 ..
drwxr-xr-x  19 maj  staff   608B Apr 10 12:44 context_dump_20190310-0714-31.0975_0e8f4141f1c20aca4fc762a87c188e09
drwxr-xr-x  19 maj  staff   608B Apr 10 12:44 context_dump_20190310-0714-32.0135_3e268b1de5be0ed9556bdf00b9579475
drwxr-xr-x  20 maj  staff   640B Apr 10 12:44 context_dump_20190310-0714-32.0280_e142e13a4f2dedaf65a4f0602ab3255b
```

The above is a single request to the devsite homepage, which `esi:includes` a homepage `htl` as well as an RSS feed `htl`.

**Describe the solution you'd like**
 It would be nice to know which `htl` / pipeline each subdirectory refers to just by looking at the subdirectory names. Maybe put the request path or URL, or whatever uniquely identifies each pipeline, directly into the subdirectory name?

**Describe alternatives you've considered**
Currently, I look at `"path"` in each subdirectory `json` files to figure out which `htl` / pipeline the request relates to. e.g.

```
➜ ack \"path\"
context_dump_20190310-0714-31.0975_0e8f4141f1c20aca4fc762a87c188e09/context-20190310-0714-32.0011-step-3.json
24:    "path": "/index.html",

...

context_dump_20190310-0714-32.0135_3e268b1de5be0ed9556bdf00b9579475/context-20190310-0714-32.0196-step-8.json
18:    "path": "/index.default.html",

...

context_dump_20190310-0714-32.0280_e142e13a4f2dedaf65a4f0602ab3255b/context-20190310-0714-33.0277-step-14.json
16:    "path": "/index.feed.html",
```

**Comment by trieloff** [comment]
@kptdobe GitHub now has a native "move issue" feature, which is a bit better than the bot.
