### ISSUE TITLE
Modifications below a submodule are not detected as _dirty_

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#781]
**Description**
with #614, it is now possible to use submodules (for better or worse). however, the `isDirty()` check ignores the submodule, so modifications below a submodule are not considered dirty. this is unexpected if it contains sources or static files, since the developer expects that what is packages with the current `sha`, would also be the one that is in the git repository.

**Comment by tripodsan** [comment]
adding this to the test case highlights the issue:

https://github.com/adobe/helix-cli/blob/9bb976e443ffde9444750fcc45237732eb0486ec/test/testGitUtils.js#L102

```diff
diff --git a/test/testGitUtils.js b/test/testGitUtils.js
index 7f4efea..8f9ecd5 100644
--- a/test/testGitUtils.js
+++ b/test/testGitUtils.js
@@ -100,6 +100,9 @@ describe('Testing GitUtils', () => {
     shell.exec('git commit -m "added submodule"');
     assert.equal(await GitUtils.isDirty(testRoot, GIT_USER_HOME), false);

+    await fse.writeFile(path.resolve(moduleRoot, 'README.md'), 'Hello, world.\n', 'utf-8');
+    assert.equal(await GitUtils.isDirty(testRoot, GIT_USER_HOME), true);
+
     await fse.remove(moduleRoot);
   });
```

**Comment by stefan-guggisberg** [comment]
are submodules packaged?

**Comment by tripodsan** [comment]
> are submodules packaged?

well, it depends on the layout. someone could have a `./src/my-utils` submodule. in this case, yes.
but I guess, this is not realistic, and we still can tackle the problem when someone notices :-)

**Comment by tripodsan** [comment]
closing for now. I don't think this is important.
