### ISSUE TITLE
improve _dirty_ detection

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#783]
during `hlx deploy`, the cli tests if the current checkout is has modifications and enforces a _dirty_ deploy. this is to prevent accidental deployment an unstable development state, which might affect a production environment.

the deployed state is mainly defined by the following conditions:

1. the `package.json` and source files in `src`. since the runtime actions are compiled and pacakged based on the projects dependencies and the source files.
1. `helix-config.yaml`. the strains that match the current checkout will eventually be updated with the new action package. 
1. the static files in `htdocs`. since the static files (especially js/css) are treated like code, one might consider them also a contributing to the deployment state. (we should probably add the `sha` also to the `ref` of the static repo, if it matches the current one.

All other local modifications do not contribute to the deployment state.

### Suggestion
Make the `isDirty()` check more precise, by only considering the conditions above.

### further actions

other improvements could include:

- auto commit the modified `helix-config.yaml` after successful deployment in order to record the updated `package` properties.
- update the `ref` in the static urls, if they match the currently checked out repository.

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
