### ISSUE TITLE
unified logging concept cli / petridish / git-server

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#79]
It would be great to use a standardized logging concept withinh the console apps.
winston supports categories: https://github.com/winstonjs/winston/blob/master/README.md#working-with-multiple-loggers-in-winston and we could use this:

- each class/file acquires the logger via `winston.loggers.get()` (eg. `winston.loggers.get('git-server')`
- _onInit_ of a module, it checks if the respective category is already present (`winston.loggers.has()`) and if not, configures it.
- maybe create a `helix-winston-config` module for harmonization.

**Comment by trieloff** [comment]
I'd throw the runtime itself into the mix, too. I think you want to drill-down/filter your logs by:

- component/environment (git-server, cli, parcel, petridish, openwhisk)
- customer code (file name)
- request ID

**Comment by tripodsan** [comment]
I just realized that each module uses its own instance of winston. so the global logger context would need to be passed around.

**Comment by trieloff** [comment]
We should have only two places where Winston instances get created:

- in development: in `helix-cli`
- in production: in `openwhisk-loggly-wrapper`

**Comment by tripodsan** [comment]
we should also look into https://www.npmjs.com/package/bunyan, which has some cool features,
such as _child loggers_:
> Bunyan has a concept of a child logger to specialize a logger for a sub-component of your application, i.e. to create a new logger with additional bound fields that will be included in its log records. A child logger is created with log.child(...).

this would allow to pass a child logger to, let's say petridish, which then can be configured differently.
