### ISSUE TITLE
update the purge config during hlx publish

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#793]
with the implementation of the [purge-config](https://github.com/adobe/helix-bot-action-config/tree/master) it is now possible to automatically update the purge config for the affected repositories during publishing. 

### suggested changes

1. add a new step to `hlx publish`, called `configureHelixBot`. this can be suppressed using `--no-bot-update`
2. check if a `HLX_GITHUB_TOKEN` is provided. if not, issue a warning:
```
Warning: no HLX_GITHUB_TOKEN is provided but is required in order to 
upgrade the helix bot configuration with the purge information. 
run `hlx auth` to obtain one.
```
3. send a POST request to the purge-config action with a list of affected content-repositories and the fastly coordinates
4. show a result to the user:
```
updated the purge-configuration of the following repositories:
- adobe/project-helix.io#master (default, testing)
- tripodsan/project-helix-test#dev (dev)

the following repositories are referenced by strains but don't have the helix-bot setup:
- adobe/test-content#master (test-strain)
```

also see: https://github.com/adobe/helix-bot/issues/4,

**Comment by tripodsan** [comment]
![2019-04-24_11-33-32](https://user-images.githubusercontent.com/917628/56628628-77512180-6685-11e9-8962-f17593fb662b.gif)

**Comment by tripodsan** [comment]
fixed with #796.

:tada: This PR is included in version 0.15.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@adobe/helix-cli)
- [GitHub release](https://github.com/adobe/helix-cli/releases/tag/v0.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by filmaj** [comment]
May I ask what this does? Should I use this flag? I see a github token is needed, but what does it do?

**Comment by tripodsan** [comment]
In short: All content repositories should have the [helix bot](https://github.com/apps/helix-bot) installed. the bot will be notified on changes (of the content) and then send a purge request to fastly.

steps to setup:

1. ensure the [helix bot](https://github.com/apps/helix-bot) is added to your content repository
2. use `hlx auth` to obtain a `HLX_GITHUB_TOKEN` and add it to your local `.env` file
3. the next time you run `hlx publish` it will automatically setup the purge config in your content repositories.

what's missing:

- ability to provide _public_key_ to allow decryption of the helix-bot config by a developer
- automatically invalidate the config if purging fails
- subdirectory repository support (currently the entire content repository is considered when purging)
- smart use of surrogate keys in order to avoid purge all

**Comment by stefan-guggisberg** [comment]
Please provide documentation.
