### ISSUE TITLE
[hlx rollback] easy way of rolling a deployment back to a previous state

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#81]
We should provide an easy way of rolling a deployment back to a previous state (as an emergency operation in case something goes wrong in production). 

I could imagine generating a deployment ID and re-running the deployment for this particular version. 

For clean deployments this should be relatively easy, as we can just restore the `ref` at the time of deployment. For `--dirty` deployments we might have to think of a workaround.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
