### ISSUE TITLE
Documentation: How to setup helix bot

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#828]
In short: All content repositories should have the [helix bot](https://github.com/apps/helix-bot) installed. the bot will be notified on changes (of the content) and then send a purge request to fastly.

steps to setup:

1. ensure the [helix bot](https://github.com/apps/helix-bot) is added to your content repository
2. use `hlx auth` to obtain a `HLX_GITHUB_TOKEN` and add it to your local `.env` file
3. the next time you run `hlx publish` it will automatically setup the purge config in your content repositories.
4. with the bot setup, any `push` to the content repository will notify the bot, which will invoke a `purgeAll` in fastly for the service that you used during `hlx publish`.

what's missing:

- ability to provide _public_key_ to allow decryption of the helix-bot config by a developer
- automatically invalidate the config if purging fails
- subdirectory repository support (currently the entire content repository is considered when purging)
- smart use of surrogate keys in order to avoid purge all

_Originally posted by @tripodsan in https://github.com/adobe/helix-cli/issues/793#issuecomment-486475027_

**Comment by kptdobe** [comment]
@tripodsan Are you still planning to document the bot? Otherwise, plz close the issue.

**Comment by tripodsan** [comment]
well, _someone_ needs to document it, eventually.

**Comment by stefan-guggisberg** [comment]
> well, someone needs to document it, eventually.

yes. ideally the person most familiar with the topic ;)

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
