### ISSUE TITLE
local-repo doesn't support sub directories strains

### ISSUE THREAD

**Issue by stevengill** [adobe/helix-cli#857]
**Description**
Not sure if this is something that can get fixed. Not really a priority. For strains that point at subdirectories, the `local-repo` option to `helix-cli` doesn't use the local repo. The strain content url is `https://github.com/abhishekchandran/contributor.en/help#master`. I run the following command `hlx up --local-repo=PathToLocalContirbutor.EN`. I believe `content-url is used to match local-repo with strain. So in this scenario, because the path I pass to `--local-repo` is missing the subdirectory (`help`), it doesn't recognize it. 

I can't pass `PathToLocalContirbutor.EN/help` to `local-repo`. Helix throws an error saying it is not a git repo in those situations. 

Note: This works fine for non-subdirectory strains. 

**To Reproduce**
1. Setup a strain with the content-url pointing to a subdirectory in a git url
2. use `local-repo` to point to the local version of the above content repo
3. Make changes to the local repo and see that it isn't being used. 

**Expected behavior**
Expected to use my local content repo vs the git one

**Version:**
2.1.6

**Comment by tripodsan** [comment]
works for me... I think you have a typo in your content url; the `.git` extension is missing:

```diff
diff --git a/helix-config.yaml b/helix-config.yaml
index bbcc1f6..ffcd665 100644
--- a/helix-config.yaml
+++ b/helix-config.yaml
@@ -52,7 +52,7 @@ strains:
   - name: contributor-docs-staging
     <<: *basestrain
     url: https://adobedevsite.helix-demo.xyz/contributor/docs
-    content: https://github.com/abhishekchandran/contributor.en/help#master
+    content: https://github.com/abhishekchandran/contributor.en.git/help#master
     directoryIndex: introduction.html
     package: developer-adobe-com/633d4dd15734e619449fd1b121d6e97d5a21b6ce
   # - name: staging
```

running with a modified package.json:

```diff
$ git diff package.json
diff --git a/package.json b/package.json
index b4f400f..ef4e75a 100644
--- a/package.json
+++ b/package.json
@@ -20,7 +20,7 @@
     "build": "hlx clean && hlx build",
     "deploy": "hlx deploy --no-auto --default HTTP_TIMEOUT 5000",
     "publish": "hlx publish",
-    "start": "hlx up --host adobedevsite.helix-demo.xyz --local-repo=."
+    "start": "hlx up --host adobedevsite.helix-demo.xyz --local-repo=. --local-repo=../contributor.en"
   },
   "repository": {
     "type": "git",
```

and requesting http://localhost:3000/contributor/docs/introduction.html works for me.

**Comment by tripodsan** [comment]
closing *WORKS FOR ME*

**Comment by stevengill** [comment]
Strange. Just tried your changes. Still isn't loading my local one for me. 🤷‍♂

**Comment by tripodsan** [comment]
do you see those entries when starting hlx?:

```
[hlx] debug: git emulating ssh://git@github.com/adobe/developer.adobe.com.git via http://127.0.0.1:65382/helix/github.com--adobe--developer.adobe.com.git#TocSupport from './'
[hlx] debug: git emulating https://github.com/abhishekchandran/contributor.en.git via http://127.0.0.1:65382/helix/github.com--abhishekchandran--contributor.en.git#master from './../contributor.en'
```

**Comment by tripodsan** [comment]
also, when requesting a resource that doesn't exist:

http://localhost:3000/contributor/docs/foo/introduction.html

you should see something like:

```
[hlx] error: Could not find Markdown at http://127.0.0.1:65382/raw/helix/github.com--abhishekchandran--contributor.en/master/help/foo/introduction.md
```

important here is the `help` in the error path.

**Comment by stevengill** [comment]
I'm not seeing the `git emulating` debug logs. 

When i go to foo/introduction, I get 
```
[hlx] debug: fetching Markdown from https://raw.github.com/abhishekchandran/contributor.en/master/help/foo/introduction.md
[hlx] error: Could not find Markdown at https://raw.github.com/abhishekchandran/contributor.en/master/help/foo/introduction.md
```

my package.json 
```
    "start": "hlx up --host adobedevsite.helix-demo.xyz --local-repo=. --local-repo=../../docs/contributor.en"
```

my strain
```
- name: contributor-docs-staging
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/contributor/docs
    content: https://github.com/abhishekchandran/contributor.en.git/help#master
    directoryIndex: introduction.html
    package: developer-adobe-com/633d4dd15734e619449fd1b121d6e97d5a21b6ce
```

**Comment by stevengill** [comment]
hmm, how does helix determine local-repo to strain relationship? Does it look at git remotes? That might be my problem as I don't actually have abhishekchandran/contributor.en.git as a remote in my contributor.en i think...Adding that now

**Comment by stevengill** [comment]
So doing a fresh clone of `abhishekchandran/contributor.en.git` instead of relying on my own fork's clone worked. So I'm guessing the local-repo to strain comparison looks at the `origin` remote (Adding a new remote to my existing repo didn't work). 

Thanks for your help @tripodsan

**Comment by tripodsan** [comment]
maybe we could add something like: `--local-repo=<remote name>:../contributor.en`

`hlx up --local-repo=abihecks_repo:../contributor.en`

**Comment by tripodsan** [comment]
https://github.com/adobe/helix-cli/issues/860
