### ISSUE TITLE
open page pre.js being triggered when loading home page - not open page

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#858]
**Description**
**EDIT**: The esi include bit has been solved.
~The [following section of our main `html.htl`](https://github.com/adobe/developer.adobe.com/blob/open-rebased/src/html.htl#L32-L36) template seems not to be honoured:~

```
<body class="spectrum spectrum--light spectrum-Typography">
    <esi:include src="/global.topnav.html" />
    <esi:include src="${payload.dispatch.url}" />
    <esi:include src="/global.footer.html" />
    <script src="/global/intersection-observer.js" type="text/javascript"></script>
```

~The `/global.topnav.html` template is correctly included. The template at the dispatch URL is not, even though the `hlx up` instance reports it (via the log in `html.pre.js`) as being set correctly:~

```
[hlx] info: dispatch url: index.default.html
[hlx] info: open pre.js
```

~The `<esi:include src="/global.footer.html" />` template is not included either, nor anything after these lines from the `html.htl` template.~

What's more, and this may be a separate problem, but loading http://localhost:3000 also seems to trigger the `src/open_html.pre.js` - whereas the expectation is that it should trigger the `default_html.pre.js`, though that may be because the `esi:include` of `index.default.html` is failing, so it falls back to that? Hard for me to tell, but I see that in the `hlx up` output per above.

**To Reproduce**
1. Clone the `open-rebased` branch from github.com/adobe/developer.adobe.com
2. `npm install`
3. run `npm start`

Note the output from `hlx up` that says `open pre.js`.

**Expected behavior**
Loading http://localhost:3000 does not trigger the `open_html.pre.js`, and so `hlx up` does NOT output `open pre.js`.

**Version:**
2.1.6

**Comment by ryanbetts** [comment]
This behavior only occurs when the `</esi:includes>` are siblings.

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-pipeline/issues/317

use `<esi:include src="..."></esi:include>` for now.

**Comment by filmaj** [comment]
OK, that solves that!

What about the incorrect-pre.js-being-triggered? After updating the esi:include tags as per your recommendation, I see this in the `hlx up` output:

```
[hlx] info: request url: /index.html
[hlx] info: request path: /index.html
[hlx] info: action path: /index.md
[hlx] info: action rootPath:
[hlx] info: strain header: default
[hlx] info: dispatch url: index.default.html
[hlx] warn: Whitelist forbids embedding of URL: https://adobeioruntime.net/api/v1/web/io-solutions/adobe-oauth-playground/oauth.html
[hlx] info: open pre.js
[hlx] info: open pre.js
```

To be fair, the `default_html.htl` has _no_ pre.js since its just static HTML. But then, why is `open_html.pre.js` being run?

**Comment by tripodsan** [comment]
@filmaj does it really execute the `open_pre.js` or does it mearly try to _open_ the `pre.js` ?

**Comment by filmaj** [comment]
I believe it executes, here's the entirety of the file:

```
async function pre(context, action) {
  const { logger } = action;
  logger.info('open pre.js');
  return context;
}

module.exports.pre = pre;
```

**Comment by tripodsan** [comment]
```
[PATCH] rename debug statements to correct filename

fixes #858
---
 src/footer_html.pre.js | 2 +-
 src/topnav_html.pre.js | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/footer_html.pre.js b/src/footer_html.pre.js
index 6aedd98..e6734e5 100644
--- a/src/footer_html.pre.js
+++ b/src/footer_html.pre.js
@@ -17,7 +17,7 @@
 // that calls next (after modifying the payload a bit)
 async function pre(payload, action) {
   const { logger } = action;
-  logger.info('open pre.js');
+  logger.info('footer pre.js');
   return payload;
 }

diff --git a/src/topnav_html.pre.js b/src/topnav_html.pre.js
index 6aedd98..7e8a1f1 100644
--- a/src/topnav_html.pre.js
+++ b/src/topnav_html.pre.js
@@ -17,7 +17,7 @@
 // that calls next (after modifying the payload a bit)
 async function pre(payload, action) {
   const { logger } = action;
-  logger.info('open pre.js');
+  logger.info('topnav pre.js');
   return payload;
 }

--
2.14.1
```

**Comment by tripodsan** [comment]
typo in scripts... closing for now.

**Comment by filmaj** [comment]
OMG.. that is extremely embarrassing.. sorry to waste your time. 🤦‍♂
