### ISSUE TITLE
[hlx strain] shows unknown arguments error for logglyHost, logglyAuth

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#86]
```bash
$ hlx strain --fastly-namespace=3l2MjGcHgWw5NUJz7OKYH3
Unknown arguments: logglyHost, logglyAuth
```

`fastly-namespace` is set via environment variable.

**Comment by tripodsan** [comment]
the fix is not good, as it breaks #64. we need to find a better environment solution for this.
I'll re-open #64 and find a different solution.
