### ISSUE TITLE
--local-repo should detect correct git remote

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#860]
the current `--local-repo` uses the `origin` remote url to tell helix-simulator, which git url should be taken locally. 

in cases where several remotes are defined, e.g. having an `upstream` of a forked repository, it is not possible to use this.

### suggestion

allow a `{remote-name}:` prefix to tell hlx which remote to use. eg:

`hlx up --local-repo=upstream:../my-content`

If no explicit remote is specified, it should fallback to the remote defined for the branch:
```
git for-each-ref --format='%(push:short)' refs/heads/trunk
```

**Comment by tripodsan** [comment]
@stefan-guggisberg is there a way to get the remote for a branch from isomorphicgit?

**Comment by stefan-guggisberg** [comment]
@tripodsan don't think so. i checked and couldn't find anything

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
