### ISSUE TITLE
When running locally, esi:includes from content strains get picked up by proxy strain

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#864]
**Description**

**To Reproduce**
1. Clone the `open-rebased` branch from github.com/adobe/developer.adobe.com
2. `npm install`
3. `npm start`
4. Load localhost:3000/open
5. See the following output from `hlx up`:

```
[hlx] info: request url: /open/index.html
[hlx] info: request path: /open/index.html
[hlx] info: action path: /index.md
[hlx] info: action rootPath: /open
[hlx] info: strain header: open-staging
[hlx] info: dispatch url: index.open.html
[hlx] info: Proxy GET request to https://www.adobe.io:443/global.topnav.html
[hlx] info: Proxy GET request to https://www.adobe.io:443/index.open.html
[hlx] info: Proxy GET request to https://www.adobe.io:443/global.footer.html
```

The proxy outputs at the bottom refer to [`esi:include`s that are part of the global `html.htl`](https://github.com/adobe/developer.adobe.com/blob/open-rebased/src/html.htl#L33-L35):

```
<esi:include src="global.topnav.html"></esi:include>
<esi:include src="${payload.dispatch.url}"></esi:include>
<esi:include src="global.footer.html"></esi:include>
```

You can also reproduce this by loading localhost:3000/xd/docs, except that page only has the global topnav and footer as includes.

**Expected behavior**
esi-includes don't get proxied.

**Version:**
2.1.1

**Comment by tripodsan** [comment]
@filmaj but this is because your fallback strain is a proxy strain:

https://github.com/adobe/developer.adobe.com/blob/fea80a0ec4681989613875884abf84193034ab89/helix-config.yaml#L59-L61

this also happens on a request to '/'.

**Comment by tripodsan** [comment]
the esi spec says:

> Relative URIs will be resolved relative to the template

In our case, the base url should probably be the request url, i.e:

requesting `/xd/docs/index.html` should include `/xd/docs/global.topnav.html`

**Comment by tripodsan** [comment]
so probably you need https://github.com/adobe/helix-simulator/issues/220

**Comment by filmaj** [comment]
The problem here is not whether we are `esi:include`'ing relative to a subdirectory or with an absolute path.

The problem is that we are trying to include HTL templates revisioned in our project under `src/topnav_html.htl`, `src/topnav_html.pre.js`, `src/footer_html.htl` and `src/footer_html.pre.js` - but we can't. Instead they are being handled by the proxy strain. 

In our global template we have the following bits that are included and are 'sub-templates':

```<esi:include src="global.topnav.html"></esi:include>
<esi:include src="${payload.dispatch.url}"></esi:include>
<esi:include src="global.footer.html"></esi:include>```

How can we include the above and NOT have it be picked up by the proxy strain? Ultimately we need both: proxy strain to handle the majority of the traffic as we roll out new helix-based pages using HTL templates, pre.js, etc., but roll them out one by one.

**Comment by trieloff** [comment]
Do `global.topnav.html`, `${payload.dispatch.url}`, and `global.footer.html` loaded correctly when requesting them directly?

**Comment by filmaj** [comment]
No, when running `npm start -- --no-open` and then `curl`ing these resources directly, they all get picked up by the proxy:

```
[hlx] info:     __ __    ___
[hlx] info:    / // /__ / (_)_ __
[hlx] info:   / _  / -_) / /\ \ /
[hlx] info:  /_//_/\__/_/_//_\_\ v2.2.1
[hlx] info:
Building project files...done 1867ms
[hlx] info: starting project
[hlx] info: Local Helix Dev server up and running: http://localhost:3000/
[hlx] info: Proxy GET request to https://www.adobe.io:443/global.topnav.html
[hlx] info: Proxy GET request to https://www.adobe.io:443/global.footer.html
[hlx] info: Proxy GET request to https://www.adobe.io:443/index.default.html
[hlx] info: Proxy GET request to https://www.adobe.io:443/index.open.html
```

I suppose the above is expected behaviour for a proxy - but then how do we build a site that has this kind of fallback-catchall-proxy _and_ includes content strains and other complex/composite templates pieced together with `esi:include` and HTL-based HTML pipelines?

**Comment by trieloff** [comment]
Once we have advanced conditions, this would be easier, but I see following ways:

1. write a VCL `condition` for the Proxy strain and the default strain that excludes `*.topnav|footer|default|open.html` from the Proxy strain and includes it in the default strain (note: this will stop working when we build proper conditions, and it won't work in the simulator)
2. create three or four strains for the resources you want to include, each with a `url` property (note: this will require fiddling with the base path in each of the strains)
3. create a strain `global` that matches the `url: /global` and points to your code repo. Then include `/global/global.topnav.html` instead of `/global.topnav.html` (i.e. create a condition that is easy to match)

**Comment by filmaj** [comment]
> 3. create a strain global that matches the url: /global and points to your code repo. Then include /global/global.topnav.html instead of /global.topnav.html (i.e. create a condition that is easy to match)

Actually we kind of do this already for static assets, we have a `static` strain set up dedicated for static assets (and so they don't get picked up by the proxy strain):

```
  - name: static-staging
    <<: *basestrain
    url: https://adobedevsite.helix-demo.xyz/static/
    package: developer-adobe-com/88564b66195f1562ae41fbb395acf8ace49446db
```

Prefixing our `esi:include` URLs with `/static/` seems to do the trick!

**Comment by filmaj** [comment]
Not sure whether to keep this open, or if this workaround is sufficient. If the workaround is sufficient then feel free to close the issue.
