### ISSUE TITLE
hlx up: cannot read property 'devDependencies' of undefined

### ISSUE THREAD

**Issue by bdelacretaz** [adobe/helix-cli#881]
**Description**
I'm getting a `Cannot read property 'devDependencies' of undefined` after running hlx demo and hlx up from a empty folder.

**To Reproduce**

    export H=...full path of helix-cli/index.js
    mkdir empty-folder
    cd empty-folder
    $H demo xxx
    cd xxx
    $H up

which says:

    ....html.pre.js: Cannot read property 'devDependencies' of undefined
    at AdapterJSAsset.getPackage (...helix-cli/src/parcel/AdapterJSAsset.js:43:9)

**Version:**
at commit 0855c48

**Comment by trieloff** [comment]
Quick workaround: run `npm init` in your project.

**Comment by stefan-guggisberg** [comment]
This should have been detected by tests. Tests are failing for me locally (5 failing tests for up command). 

How did the current code end up on master without build failures?

**Comment by tripodsan** [comment]
> How did the current code end up on master without build failures?

they work for me :-)
