### ISSUE TITLE
[hlx publish] should warn/fail when invoked with invalid repos

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#89]
`hlx deploy` when no remote is set (i.e. you went through `hlx init` but never pushed to GitHub)
- should not create a `content` node in `strains.yaml`
- should warn that the current deployment is not able to access any content

`hlx strains` when no valid `content` object is found:
- should fail with a nice error message

Right now, it just tries to deploy the impossible, and fails.

**Comment by tripodsan** [comment]
I think this should only apply to `hlx publish`. `hlx deploy` doesn't really care about the content, just the code.

`hlx publish` should:
- get a list of all runtime strains that are not _localhost_
- check if the repository url specified by `content` and `static` exist
- report the ones that don't exist and abort the publish process.

**Comment by tripodsan** [comment]
this is implemented with the recent config changes.
