### ISSUE TITLE
should publish complain if git checkout is dirty?

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#897]
`hlx deploy` requires the git checkout to be clean (unless the `--dirty` flag is used). Shouldn't `hlx publish` have the same requirement - especially since `hlx deploy` modified the `helix-config.yaml` again, adding the package IDs?

**Comment by filmaj** [comment]
Hah, I just had the same question yesterday when working on partial deploy/publish to enable previewing pull requests (https://github.com/adobe/developer.adobe.com/pull/173).

**Comment by trieloff** [comment]
I don't think so. But it might be wise to commit after running a successful publish, so that the state of your system is documented.
