### ISSUE TITLE
Support authenticated GitHub access

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-cli#901]
**Is your feature request related to a problem? Please describe.**
Currently content is fetched from VCL (Fastly) & serverless actions (AdobeIO Runtime) via unauthenticated GitHub raw requests. As a result private GitHub repos are not accessible. Furthermore unauthenticated GitHub raw requests might become subject to potential rate limiting/throttling.

**Describe the solution you'd like**
If there's a `HLX_GITHUB_TOKEN` environment variable `hlx publish` could add it to the `secrets` edge dictionary, thus make it available to custom VCL and AdobeIO Runtime calls (via parameter).

**Related issues** 
 - adobe/helix-cli#901 (`hlx publish --github-token`)
 - adobe/helix-publish#165
 - adobe/helix-pipeline#72 
 - adobe/helix-dispatch#71
 - adobe/helix-resolve-git-ref#1
 - adobe/helix-static#46

**Comment by rofe** [comment]
How would we handle the use case where both code and content repos are private, but require different access tokens (for example a company would like to have all their subsites rendered using the same code, which is under the web team’s control, while different marketing teams maintain their content repos and publish them using the common code repo)?

PS: The issue title describes the implementation, not the feature, which is: support private GitHub repositories ;)

**Comment by stefan-guggisberg** [comment]
> How would we handle the use case where both code and content repos are private, but require different access tokens (for example a company would like to have all their subsites rendered using the same code, which is under the web team’s control, while different marketing teams maintain their content repos and publish them using the common code repo)?

Do you think this is a common use case? If not I would prefer to first address the simple use case first.

> PS: The issue title describes the implementation, not the feature, which is: support private GitHub repositories ;)

Feel free to change it ;) The initial feature I had in mind was supporting authenticated GitHub access to alleviate potential rate limiting/throttling issues.

**Comment by tripodsan** [comment]
we already use a `--github-token` (https://github.com/adobe/helix-cli/blob/master/src/publish.js#L94) which is obtained via `hlx auth` and used to access by the bot to access to repository to update the purge config.

I'm not sure if it will not cause confusions:

(assuming the token is added via `HLX_GITHUB_TOKEN` or passed via `--github-token`)

case 1: bot **not** installed, the user created a personal access token
- `hlx publish` will tell, that they should install the bot ✅
- _fetch_ can read the private repo ✅

case 2: bot installed, the user created a personal access token
-  `hlx publish` succeed, and the purge is config updated ✅
- _fetch_ can read the private repo ✅

case 3: bot **not** installed, the user added the `hlx auth` token
- `hlx publish` will tell, that they should install the bot ✅
- _fetch_ can not read the private repo ❌    

case 4: bot  installed, the user added the `hlx auth` token
-  `hlx publish` succeed, and the purge is config updated ✅
- _fetch_ can read the private repo ✅

case 5: bot  installed, the user added the `hlx auth` token, but bot needed to invalidate the tokens
-  `hlx publish` fails to update the purge config ❌
- _fetch_ can not read the private repo ❌

**Comment by rofe** [comment]
> Feel free to change it

I created a separate issue for clarity: #912

**Comment by stefan-guggisberg** [comment]
@tripodsan so`hlx auth` is already providing support for private repos?

**Comment by tripodsan** [comment]
> @tripodsan so `hlx auth` is already providing support for private repos?

not really. all it does is an oauth handshake with github in order to receive a token that let's the user access his repositories in behalf of the helix bot.

so it enables access to private repositories, as long as the helix bot is installed, either org wide, or on the repository.

see https://github.com/adobe/helix-bot-action-login/blob/master/docs/github-authentication.md
and https://github.com/adobe/helix-cli/issues/579
and https://github.com/adobe/helix-bot/issues/33

**Comment by stefan-guggisberg** [comment]
> so it enables access to private repositories, as long as the helix bot is installed, either org wide, or on the repository.

I am still confused. How would the `helix bot` enable `VCL` code or runtime actions to access private content and/or code repos?

**Comment by tripodsan** [comment]
> I am still confused. How would the `helix bot` enable `VCL` code or runtime actions to access private content and/or code repos?

it doesn't. we need to pass the `HLX_GITHUB_TOKEN` (or the `--github-token` argument) to `helix-publish` during `hlx publish`. and `helix-publish` needs to update the VCL, so that it can be included it to the requests to the actions.

**Comment by stefan-guggisberg** [comment]
Ok, that's exactly what I planned to do but got confused by comment (https://github.com/adobe/helix-cli/issues/901#issuecomment-495375400) :-)

**Comment by stefan-guggisberg** [comment]
Ok, we're on the same page. That's what I planned to do but got confused by https://github.com/adobe/helix-cli/issues/901#issuecomment-495375400

**Comment by stefan-guggisberg** [comment]
resolved via #1138
