### ISSUE TITLE
Ability to override `hlx up` gateway timeout to github

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#911]
**Is your feature request related to a problem? Please describe.**
I regularly develop on slow / intermittent internet. As such, helix sites that rely on GitHub for content repos can sometimes be frustrating for me to work with as I would regularly see:

```
[hlx] error: Gateway timout of 1000 milliseconds exceeded for https://raw.github.com/bdelacretaz/project-helix.io/overview-diagram/doc/getting-started/how-helix-works.md
```

**Describe the solution you'd like**
A command-line flag for `hlx up` to allow me to override the 1000ms timeout.

**Describe alternatives you've considered**
While the `--local-repo` flag is helpful, and I use it all the time, sometimes I also don't want to go through the trouble of setting up a new content repo for a one-off purpose. For example, reviewing someone's pull request, I won't have a long-term need to have that PR's content repo fork on my machine. Overriding the timeout lets me be lazier!

**Comment by trieloff** [comment]
`helix-pipeline` supports overriding the `HTTP_TIMEOUT` but I don't think that `hlx up` has the equivalent to `hlx deploy -p key value` yet.

**Comment by tripodsan** [comment]
I would keep it distinct from `-p` to avoid accidental  deployment of dev variables.

what about:

```
hlx up --action-param HTTP_TIMEOUT 10000
```

and:

```env
HLX_ACTION_PARAM=HTTP_TIMEOUT\=10000
```

**Comment by rofe** [comment]
Update: use
```sh
hlx up --dev-default HTTP_TIMEOUT 10000
```
(env doesn't work)
