### ISSUE TITLE
--local-repo=. should be default

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#913]
**Description**
once deployed, the content repo is set to the git origin and the local development uses the remote repository, which is not intuitive.

## suggest

make `--local-repo` the default. if devs want to test the remote content repository, they can specify `--no-local-repo`

**Comment by kptdobe** [comment]
Related to #711

**Comment by stefan-guggisberg** [comment]
Reopening, the fix caused a regression (#1189)and had to be reverted. Issue still exists.

**Comment by tripodsan** [comment]
as I mentioned somewhere else, the initial idea of this issue was, that for local development, it should force a local repo, if not specified otherwise.

- new repo, no origin -> simulator takes care. don't specify `--local-repo=.`
- repo with origin -> default to `--local-repo=.`
- if any other `--local-repo` or `--no-local-repo` is specified, use as specified.
