### ISSUE TITLE
Simplify `hlx` and move operational commands to `hops`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#927]
### Overview
for a new user, the current `hlx` command line is very convoluted. for simple local development, the available commands should be hidden or moved to `helix-ops` aka `hops`.

#### local dev commands

```
$ hlx --help
Usage: hlx <command> [options]

Commands:
  hlx demo <name> [dir]  Create example helix project.
  hlx up [files...]      Run a Helix development server
  hlx clean              Remove generated files and caches.
  hlx completion         generate completion script
```

#### operations commands

```
$ hops --help
Usage: hops <command> [options]

Commands:
  hlx build [files..]    Compile the template functions and build package
  hlx package            Create Adobe I/O runtime packages
  hlx deploy             Deploy packaged functions to Adobe I/O runtime
  hlx perf               Test performance
  hlx publish            Activate strains in the Fastly CDN and publish the site
  hlx clean              Remove generated files and caches.
  hlx auth               Authenticate against 3rd party systems for development
                         and deployment
  hlx completion         generate completion script
```

### 1. stage
- create new binary entry-point `hops`
- `hops` will support all the commands that `hlx` supports today
- `hlx` will hide the advanced commands, but still support them

### 2. stage
- `hops` will only support the _operations_ commands (eg. not `up`)
- `hlx` will only support the _non operations_ command 

### Alternative names 

- `hops`
- `hlxops`

**Comment by filmaj** [comment]
Splitting this into two commands seems convoluted to me 🤷‍♂

**Comment by trieloff** [comment]
`hops` should also have a completion script

**Comment by trieloff** [comment]
@filmaj the idea is that you won't see `hops` unless you check your CI script or perform troubleshooting. We want to hide almost everything that's in `hops` behind automation.

**Comment by bdelacretaz** [comment]
+1 for these changes along with https://github.com/adobe/helix-cli/issues/241 and mentioning https://github.com/adobe/helix-home/issues/40 here, the developer experience theme.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
