### ISSUE TITLE
Repurpose hlx demo

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#933]
**Describe the solution you'd like**
Since the starting point for getting started will be Helix Pages in the future (see also #929), we no longer need to support the ability to generate demo projects in the CLI. 

**Describe alternatives you've considered**
Alternatively, we should invest in making them work (and [look great](https://github.com/adobe/helix-pages/issues/3)) in Helix Pages

**Comment by stefan-guggisberg** [comment]
If we remove `hlx demo` we should provide properly maintained example projects on gh that can be cloned or copied, as discussed at the bsl hackathon.

Those example projects

**Comment by stefan-guggisberg** [comment]
If we remove `hlx demo` we should provide properly maintained example projects on gh which can be cloned or copied, as discussed at the bsl hackathon.

Those example projects should cover simple to more advanced use cases.

**Comment by rofe** [comment]
True. See https://github.com/adobe/helix-pages/issues/14

**Comment by rofe** [comment]
On second thought, let's keep `hlx demo`, but have it clone/fork an example repo from https://github.com/adobe/helix-pages/issues/14 instead of maintaining and copying a static project from within the CLI. So for example `hlx demo --type=n mydemo` would check out example repo number `n` into `mydemodir` and thereby save the user the extra step of later linking the demo project to a github repo.

`hlx demo` without `--type` argument could turn into wizard:
```
Which type of demo would you like hlx to create for you?
  1 - simple demo (https://github.com/adobe/helix-demo-1)
  2 - custom styling (https://github.com/adobe/helix-demo-2)
  3 - custom code (https://github.com/adobe/helix-demo-3)
  ...
Please type the number of the desired demo to continue [1]
```
The existing types `simple` and `full` should probably be deprecated -  unless they can be mapped to a demo number intuitively.

**Comment by bdelacretaz** [comment]
I like the idea and ideally ``hlx``finds the example repos automatically based on a GitHub query, like

    select all repos
    from the "adobe" organization
    which have the "helix, hlx-example" topics
    and for which tests are passing

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
