### ISSUE TITLE
ESI/Statification of CSS/JS increases response time, even when cached

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-cli#935]
Looking at the status page it looks like the response times more than doubled recently for the project helix homepage

![839A525B-9FC6-4E14-B355-4F391F9D2F0C](https://user-images.githubusercontent.com/5289336/58516156-4e301f00-8164-11e9-8125-56776c10b5a9.jpeg)

**Comment by trieloff** [comment]
I don't think this is what's happening. The average response time definitely has gone up, but requesting either of the URLs mentioned in this thread repeatedly is fast.

As Pingdom is rotating between locations (and thus Fastly edge nodes), we might be seeing that the ESI is being processed in the wrong location: edge, cluster, shield? (I don't know)

**Comment by kptdobe** [comment]
A little bit of analysis shows:

- the perf started to degrade on May 27
- this is the day of a `hlx deploy` / `hlx publish`
- previous  `hlx deploy` / `hlx publish` was Apr 3/4.
- the project code has not really changed for 6 months - only change that happened that exact day is https://github.com/adobe/project-helix.io/commit/8c72b83e665d6a4ce664b8704850b7abd2ac72f4#diff-463cb3ad76ac5060b566c29e806a5c29 which does not introduce any new feature or something, just some different DOM

Quick and obvious conclusion: something in hlx code has changed and slows down the same project code. Considering the number of features we introduced, only performance tracing could revealing where it is slower than before.

I `hlx deploy publish` today (June 9) using hlx v4.2.2, we can see if performances change.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
