### ISSUE TITLE
Slow startup for `hlx up`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#945]
**Description**
The time it takes for `hlx up` to be ready is quite long. I assume that module loading is quite expensive, even until the first output is shown.

Add the following to `index.js`:

```
const Module = require('module');

const { require: oldRequire } = Module.prototype;
Module.prototype.require = function require(name) {
  const t0 = process.hrtime();
  const mod = oldRequire.call(this, name);
  const t1 = process.hrtime();
  const ds = t1[0] - t0[0]; // seconds
  const dn = t1[1] - t0[1]; // nanoseconds
  console.log(`require,${name},${ds * 1000 + dn / 1000000}`);
  return mod;
};
```

then run: 
```
hlx up --port 123456789 | fgrep require | sort -gr -k 3 -t , | head -20 | cut -d, -f 2,3 | column -t -s ,
```

```
./up.cmd                                                                                993.683755
@adobe/helix-simulator                                                                  546.2972990000001
./HelixProject.js                                                                       545.572743
./build.cmd                                                                             393.381367
parcel-bundler                                                                          392.212688
./src/Bundler                                                                           391.635748
./HelixServer.js                                                                        259.025988
./src/config/config-utils.js                                                            213.074269
/Users/tripod/codez/helix/project-helix/modules/helix-cli/src/parcel/AdapterJSAsset.js  166.48091399999998
parcel-bundler/src/assets/JSAsset                                                       165.992124
./packagers                                                                             158.08692
./JSConcatPackager                                                                      147.009447
@adobe/helix-shared                                                                     145.712565
@adobe/helix-shared                                                                     134.348746
./GitManager.js                                                                         132.104466
@adobe/git-server/lib/server.js                                                         131.508031
../transforms/babel/transform                                                           130.88885100000005
./config                                                                                129.48038199999996
./env                                                                                   126.13306599999999
@babel/preset-env                                                                       125.34995700000002
```

**Note**

The times above are milliseconds. The sorted output is a bit misleading, since the `requires` are invoked recursively. e.g. `helix-simulator` is required by `up.cmd`, so the **546ms** of the simulator is included in the **993ms** of the up command.

**Version:**
`4.0.6`

**Comment by tripodsan** [comment]
also interesting is, that some modules, like `helix-shared` are loaded twice. once from cli and once via simulator. this due to version incompatibilities.

| Path | name | time (ms) |
|------|------|-----------|
| helix-cli/src/up.cmd.js                                                    |  ./up.cmd                            | 2190.3034 |
| helix-simulator/src/index.js                                               |  @adobe/helix-simulator              | 1046.830179 |
| helix-simulator/src/HelixProject.js                                        |  ./HelixProject.js                   | 1046.015635 |
| helix-cli/src/build.cmd.js                                                 |  ./build.cmd                         | 1034.149018 |
| helix-cli/node_modules/parcel-bundler/index.js                             |  parcel-bundler                      | 1031.674623 |
| helix-cli/node_modules/parcel-bundler/src/Bundler.js                       |  ./src/Bundler                       | 1030.557817 |
| helix-cli/node_modules/parcel-bundler/src/packagers/index.js               |  ./packagers                         | 504.845426 |
| helix-cli/node_modules/parcel-bundler/src/packagers/JSConcatPackager.js    |  ./JSConcatPackager                  | 477.674562 |
| helix-cli/src/config/config-utils.js                                       |  ./src/config/config-utils.js        | 470.731213 |
| helix-simulator/src/HelixServer.js                                         |  ./HelixServer.js                    | 463.887002 |
| helix-cli/node_modules/@adobe/helix-shared/src/index.js                    |  @adobe/helix-shared                 | 337.517463 |
| helix-cli/node_modules/parcel-bundler/src/assets/JSAsset.js                |  parcel-bundler/src/assets/JSAsset   | 295.631405 |
| helix-simulator/node_modules/@adobe/helix-shared/src/index.js              |  @adobe/helix-shared                 | 286.78486699999996 |
| helix-cli/node_modules/babylon-walk/lib/index.js                           |  babylon-walk                        | 254.128897 |
| helix-cli/node_modules/parcel-bundler/src/Resolver.js                      |  ./Resolver                          | 253.40443800000003 |
| helix-simulator/src/GitManager.js                                          |  ./GitManager.js                     | 250.230013 |
| helix-cli/node_modules/parcel-bundler/src/transforms/babel/transform.js    |  ../transforms/babel/transform       | 249.777561 |
| helix-simulator/node_modules/@adobe/git-server/lib/server.js               |  @adobe/git-server/lib/server.js     | 249.151031 |
| helix-cli/node_modules/parcel-bundler/src/transforms/babel/config.js       |  ./config                            | 247.473016 |
| helix-cli/node_modules/parcel-bundler/src/transforms/babel/env.js          |  ./env                               | 242.117831 |
| helix-cli/node_modules/@babel/preset-env/lib/index.js                      |  @babel/preset-env                   | 240.456636 |
| helix-simulator/node_modules/nodesi/index.js                               |  nodesi                              | 228.343416 |
| helix-simulator/node_modules/nodesi/lib/esi.js                             |  ./lib/esi                           | 226.411549 |
| helix-simulator/node_modules/nodesi/lib/data-provider.js                   |  ./data-provider                     | 223.582182 |
| helix-simulator/node_modules/good-guy-http/lib/index.js                    |  good-guy-http                       | 222.764134 |
| helix-cli/node_modules/parcel-bundler/src/utils/glob.js                    |  ./utils/glob                        | 221.229735 |
| helix-cli/node_modules/fast-glob/index.js                                  |  fast-glob                           | 220.29455700000005 |
| helix-cli/node_modules/fast-glob/out/index.js                              |  ./out/index                         | 219.35258 |
| helix-cli/node_modules/@babel/preset-env/lib/available-plugins.js          |  ./available-plugins                 | 216.4676 |
| helix-cli/node_modules/parcel-bundler/src/scope-hoisting/concat.js         |  ../scope-hoisting/concat            | 201.976942 |
| helix-simulator/node_modules/good-guy-http/node_modules/request/index.js   |  request                             | 197.273802 |
| helix-simulator/node_modules/@adobe/git-server/lib/app.js                  |  ./app                               | 196.8097 |
| helix-cli/node_modules/fast-glob/out/managers/tasks.js                     |  ./managers/tasks                    | 186.62640299999998 |
| helix-cli/node_modules/fast-glob/out/utils/pattern.js                      |  ../utils/pattern                    | 185.64273200000002 |
| helix-cli/node_modules/babel-types/lib/index.js                            |  babel-types                         | 183.23125 |
| helix-cli/node_modules/fast-glob/node_modules/micromatch/index.js          |  micromatch                          | 180.37743 |
| helix-simulator/node_modules/good-guy-http/node_modules/request/request.js |  ./request                           | 175.790344 |
| helix-cli/node_modules/@adobe/helix-shared/src/Logger.js                   |  ./Logger.js                         | 141.689267 |
| helix-cli/node_modules/fast-glob/node_modules/braces/index.js              |  braces                              | 140.01491899999996 |

**Comment by kptdobe** [comment]
@tripodsan Do you still think it is slow ? Should we close the issue ?

**Comment by tripodsan** [comment]
I still think it is slow...but maybe after the logger changes, we should revisit this.
