### ISSUE TITLE
Assimilate parcel-plugin-htl into cli

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#952]
Currently, we have a tight integration between `htlengine`, `parcel`, `parcel-plugin-htl` and `helix-cli`. the original idea was, that through parcel plugins, we can easily offer 3rd party scripts.

However, the 2-stage transformation from script to template-code to wsk-action is not trivial, and always needs custom treatment in helix-cli. the extra dependency to `parcel-plugin-htl` is artificial and comes with extra maintenance cost.

- `parcel-plugin-htl` is very specific to helix-cli
- `parcel-plugin-jst` is not used and not tested
- abandoning `parcel-plugin-*` would make `parcel` and implementation detail
- integration between plugin-generated code and wsk-wrapper is very tight.

# Suggestion

1. move the relevant code from `parcel-plugin-htl` to `helix-cli`
2. deprecate the `@adobe/parcel-plugin-*` packages
3. archive the `@adobe/parcel-plugin-*` repositories

/cc @trieloff

**Comment by trieloff** [comment]
Makes sense. We can think of easier extensibility for custom template languages when there is a pressing need. For now, I think we are well-served with HTL and JSX.
