### ISSUE TITLE
Missing dependencies when using the globally install helix-cli

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#966]
**Description**
`@babel/*` dependencies are missing with using the globally installed helix-cli.

**To Reproduce**
I use project https://github.com/adobe/helix-pages:
1. `npm install -g @adobe/helix-cli`
2. In the project, run `hlx clean; hlx build; hlx package`
3. Then, run `ll .hlx/build/html.zip`: ` 8920814 Jun  7 08:29 .hlx/build/html.zip`
4. Deploy and publish the project, I get activation error:

```
"error": "Initialization has failed due to: Error: Cannot find module '@babel/runtime-corejs2/helpers/interopRequireDefault'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/nodejsAction/XXbedOKc/node_modules/@adobe/htlengine/node_modules/xregexp/lib/index.js:3:30)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)"
```

Now do:

1. `git clone https://github.com/adobe/helix-cli.git`
2. `cd helix-cli`
3. `npm install; npm link`
4. In the project, run `hlx clean; hlx build; hlx package`
3. Then, run `ll .hlx/build/html.zip`: `10193801 Jun  7 08:14 .hlx/build/html.zip`
4. Deploy and publish the project, works as expected!

At least `@babel/*` dependencies are missing in the first case. 12Mo of dependencies seem to be missing.

**Version:**
run: `$ hlx --version`
4.2.2 in both cases

cc @tripodsan

**Comment by tripodsan** [comment]
I cannot reproduce this...I always use the global helix:

```
$ which hlx
/data/nvm/versions/node/v10.15.3/bin/hlx
```

**Comment by tripodsan** [comment]
the difference is in where the modules are located.

**helix-cli clone**
```
$ npm ls @babel/runtime-corejs2
@adobe/helix-cli@4.2.2 /Users/tripod/codez/helix/project-helix/modules/helix-cli
└─┬ xregexp@4.2.4
  └── @babel/runtime-corejs2@7.4.5
```

**global helix-cli**
```
$ npm ls @babel/runtime-corejs2
@adobe/helix-cli@4.2.3 /data/nvm/versions/node/v10.15.3/lib/node_modules/@adobe/helix-cli
└─┬ @adobe/htlengine@3.1.0
  └─┬ xregexp@4.2.4
    └── @babel/runtime-corejs2@7.4.5
```

The problem is, that xregexp is a devDependency of `helix-cli` and is therefore loaded differently.

**Comment by tripodsan** [comment]
- htlengine uses `xregexp@4.2.4`
- but helix-cli uses `xregexp@2.0.0` through openwhisk.

this causes the wrong xregexp to be present somehow in a global install

**Comment by tripodsan** [comment]
I think eventually, using a distinct `helix-runtime` package wold probably be better. this way we could separate the module we strictly only need in the actions.

**Comment by tripodsan** [comment]
this introduced a regressen, such as the opposite now doesn't work anymore. i.e. using a locally cloned helix-cli.
