### ISSUE TITLE
ESI includes should benefit from query string automatically

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#970]
If I request `/index.htm?a=1&b=2&c=3`, the ESI includes I may use in my template do not get the query string automatically: I have to include them myself. While this is doable at the project level via a stringification of the `context.request.params` object + an append manually in my ESI includes, I think this should be done automatically.

**Comment by tripodsan** [comment]
I don't think we should propagate any request parameters automatically to the esi includes. otherwise it is not controllable. maybe we should add a `context.request.queryString` to help facilitate this, if someone wants to add it.

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-pipeline/issues/366

**Comment by tripodsan** [comment]
closing this as **won't fix**
